// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/routing/routing.proto

package routingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteQuery 路由查询请求
type RouteQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePeerId  []byte                 `protobuf:"bytes,1,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`
	TargetPeerId  []byte                 `protobuf:"bytes,2,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	MaxHops       int32                  `protobuf:"varint,3,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	MaxPaths      int32                  `protobuf:"varint,4,opt,name=max_paths,json=maxPaths,proto3" json:"max_paths,omitempty"`
	Policy        int32                  `protobuf:"varint,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteQuery) Reset() {
	*x = RouteQuery{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQuery) ProtoMessage() {}

func (x *RouteQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQuery.ProtoReflect.Descriptor instead.
func (*RouteQuery) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RouteQuery) GetSourcePeerId() []byte {
	if x != nil {
		return x.SourcePeerId
	}
	return nil
}

func (x *RouteQuery) GetTargetPeerId() []byte {
	if x != nil {
		return x.TargetPeerId
	}
	return nil
}

func (x *RouteQuery) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *RouteQuery) GetMaxPaths() int32 {
	if x != nil {
		return x.MaxPaths
	}
	return 0
}

func (x *RouteQuery) GetPolicy() int32 {
	if x != nil {
		return x.Policy
	}
	return 0
}

// RouteResponse 路由查询响应
type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteInfo           `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetRoutes() []*RouteInfo {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RouteInfo 路由信息
type RouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPeerId  []byte                 `protobuf:"bytes,1,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	NextHop       []byte                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Path          [][]byte               `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Hops          int32                  `protobuf:"varint,5,opt,name=hops,proto3" json:"hops,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RouteInfo) GetTargetPeerId() []byte {
	if x != nil {
		return x.TargetPeerId
	}
	return nil
}

func (x *RouteInfo) GetNextHop() []byte {
	if x != nil {
		return x.NextHop
	}
	return nil
}

func (x *RouteInfo) GetPath() [][]byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RouteInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RouteInfo) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *RouteInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PathInfo 路径信息
type PathInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nodes          [][]byte               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalLatencyMs int64                  `protobuf:"varint,2,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	Hops           int32                  `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	Valid          bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PathInfo) Reset() {
	*x = PathInfo{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathInfo) ProtoMessage() {}

func (x *PathInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathInfo.ProtoReflect.Descriptor instead.
func (*PathInfo) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{3}
}

func (x *PathInfo) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PathInfo) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *PathInfo) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *PathInfo) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *PathInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// PathQuery 路径查询
type PathQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []byte                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        []byte                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MaxPaths      int32                  `protobuf:"varint,3,opt,name=max_paths,json=maxPaths,proto3" json:"max_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathQuery) Reset() {
	*x = PathQuery{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathQuery) ProtoMessage() {}

func (x *PathQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathQuery.ProtoReflect.Descriptor instead.
func (*PathQuery) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{4}
}

func (x *PathQuery) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PathQuery) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PathQuery) GetMaxPaths() int32 {
	if x != nil {
		return x.MaxPaths
	}
	return 0
}

// PathResponse 路径响应
type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*PathInfo            `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{5}
}

func (x *PathResponse) GetPaths() []*PathInfo {
	if x != nil {
		return x.Paths
	}
	return nil
}

// NodeMetrics 节点指标
type NodeMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,3,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	BandwidthUsage  int64                  `protobuf:"varint,4,opt,name=bandwidth_usage,json=bandwidthUsage,proto3" json:"bandwidth_usage,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,5,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	IsReachable     bool                   `protobuf:"varint,6,opt,name=is_reachable,json=isReachable,proto3" json:"is_reachable,omitempty"`
	LastSeen        int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{6}
}

func (x *NodeMetrics) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *NodeMetrics) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *NodeMetrics) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *NodeMetrics) GetBandwidthUsage() int64 {
	if x != nil {
		return x.BandwidthUsage
	}
	return 0
}

func (x *NodeMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeMetrics) GetIsReachable() bool {
	if x != nil {
		return x.IsReachable
	}
	return false
}

func (x *NodeMetrics) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// NodeMetricsList 节点指标列表
type NodeMetricsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*NodeMetrics         `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetricsList) Reset() {
	*x = NodeMetricsList{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetricsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetricsList) ProtoMessage() {}

func (x *NodeMetricsList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetricsList.ProtoReflect.Descriptor instead.
func (*NodeMetricsList) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{7}
}

func (x *NodeMetricsList) GetMetrics() []*NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// LoadReport 负载报告
type LoadReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,2,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	BandwidthUsage  int64                  `protobuf:"varint,3,opt,name=bandwidth_usage,json=bandwidthUsage,proto3" json:"bandwidth_usage,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoadReport) Reset() {
	*x = LoadReport{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReport) ProtoMessage() {}

func (x *LoadReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReport.ProtoReflect.Descriptor instead.
func (*LoadReport) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{8}
}

func (x *LoadReport) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *LoadReport) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *LoadReport) GetBandwidthUsage() int64 {
	if x != nil {
		return x.BandwidthUsage
	}
	return 0
}

func (x *LoadReport) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *LoadReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// LoadQuery 负载查询
type LoadQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadQuery) Reset() {
	*x = LoadQuery{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadQuery) ProtoMessage() {}

func (x *LoadQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadQuery.ProtoReflect.Descriptor instead.
func (*LoadQuery) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{9}
}

func (x *LoadQuery) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// LoadResponse 负载响应
type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load          *LoadReport            `protobuf:"bytes,1,opt,name=load,proto3" json:"load,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{10}
}

func (x *LoadResponse) GetLoad() *LoadReport {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *LoadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// RelayRequest 中继请求
type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePeerId  []byte                 `protobuf:"bytes,1,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`
	TargetPeerId  []byte                 `protobuf:"bytes,2,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{11}
}

func (x *RelayRequest) GetSourcePeerId() []byte {
	if x != nil {
		return x.SourcePeerId
	}
	return nil
}

func (x *RelayRequest) GetTargetPeerId() []byte {
	if x != nil {
		return x.TargetPeerId
	}
	return nil
}

func (x *RelayRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RelayRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// RelayResponse 中继响应
type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RelayNode     []byte                 `protobuf:"bytes,3,opt,name=relay_node,json=relayNode,proto3" json:"relay_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{12}
}

func (x *RelayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RelayResponse) GetRelayNode() []byte {
	if x != nil {
		return x.RelayNode
	}
	return nil
}

// ReachabilityQuery 可达性查询
type ReachabilityQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReachabilityQuery) Reset() {
	*x = ReachabilityQuery{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityQuery) ProtoMessage() {}

func (x *ReachabilityQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityQuery.ProtoReflect.Descriptor instead.
func (*ReachabilityQuery) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{13}
}

func (x *ReachabilityQuery) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

// ReachabilityResponse 可达性响应
type ReachabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReachableNodes [][]byte               `protobuf:"bytes,1,rep,name=reachable_nodes,json=reachableNodes,proto3" json:"reachable_nodes,omitempty"`
	RelayNodes     [][]byte               `protobuf:"bytes,2,rep,name=relay_nodes,json=relayNodes,proto3" json:"relay_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReachabilityResponse) Reset() {
	*x = ReachabilityResponse{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityResponse) ProtoMessage() {}

func (x *ReachabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityResponse.ProtoReflect.Descriptor instead.
func (*ReachabilityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{14}
}

func (x *ReachabilityResponse) GetReachableNodes() [][]byte {
	if x != nil {
		return x.ReachableNodes
	}
	return nil
}

func (x *ReachabilityResponse) GetRelayNodes() [][]byte {
	if x != nil {
		return x.RelayNodes
	}
	return nil
}

// GatewayStateSync Gateway 状态同步
type GatewayStateSync struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReachableNodes [][]byte               `protobuf:"bytes,1,rep,name=reachable_nodes,json=reachableNodes,proto3" json:"reachable_nodes,omitempty"`
	RelayNodes     [][]byte               `protobuf:"bytes,2,rep,name=relay_nodes,json=relayNodes,proto3" json:"relay_nodes,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayStateSync) Reset() {
	*x = GatewayStateSync{}
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStateSync) ProtoMessage() {}

func (x *GatewayStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_routing_routing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStateSync.ProtoReflect.Descriptor instead.
func (*GatewayStateSync) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP(), []int{15}
}

func (x *GatewayStateSync) GetReachableNodes() [][]byte {
	if x != nil {
		return x.ReachableNodes
	}
	return nil
}

func (x *GatewayStateSync) GetRelayNodes() [][]byte {
	if x != nil {
		return x.RelayNodes
	}
	return nil
}

func (x *GatewayStateSync) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_lib_proto_realm_routing_routing_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_routing_routing_proto_rawDesc = "" +
	"\n" +
	")pkg/lib/proto/realm/routing/routing.proto\x12\rrealm.routing\"\xa8\x01\n" +
	"\n" +
	"RouteQuery\x12$\n" +
	"\x0esource_peer_id\x18\x01 \x01(\fR\fsourcePeerId\x12$\n" +
	"\x0etarget_peer_id\x18\x02 \x01(\fR\ftargetPeerId\x12\x19\n" +
	"\bmax_hops\x18\x03 \x01(\x05R\amaxHops\x12\x1b\n" +
	"\tmax_paths\x18\x04 \x01(\x05R\bmaxPaths\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\x05R\x06policy\"q\n" +
	"\rRouteResponse\x120\n" +
	"\x06routes\x18\x01 \x03(\v2\x18.realm.routing.RouteInfoR\x06routes\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa9\x01\n" +
	"\tRouteInfo\x12$\n" +
	"\x0etarget_peer_id\x18\x01 \x01(\fR\ftargetPeerId\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\fR\anextHop\x12\x12\n" +
	"\x04path\x18\x03 \x03(\fR\x04path\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12\x12\n" +
	"\x04hops\x18\x05 \x01(\x05R\x04hops\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"\x93\x01\n" +
	"\bPathInfo\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\fR\x05nodes\x12(\n" +
	"\x10total_latency_ms\x18\x02 \x01(\x03R\x0etotalLatencyMs\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\x05R\x04hops\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"X\n" +
	"\tPathQuery\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\fR\x06target\x12\x1b\n" +
	"\tmax_paths\x18\x03 \x01(\x05R\bmaxPaths\"=\n" +
	"\fPathResponse\x12-\n" +
	"\x05paths\x18\x01 \x03(\v2\x17.realm.routing.PathInfoR\x05paths\"\xf6\x01\n" +
	"\vNodeMetrics\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12)\n" +
	"\x10connection_count\x18\x03 \x01(\x05R\x0fconnectionCount\x12'\n" +
	"\x0fbandwidth_usage\x18\x04 \x01(\x03R\x0ebandwidthUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x05 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fis_reachable\x18\x06 \x01(\bR\visReachable\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\"G\n" +
	"\x0fNodeMetricsList\x124\n" +
	"\ametrics\x18\x01 \x03(\v2\x1a.realm.routing.NodeMetricsR\ametrics\"\xb4\x01\n" +
	"\n" +
	"LoadReport\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12)\n" +
	"\x10connection_count\x18\x02 \x01(\x05R\x0fconnectionCount\x12'\n" +
	"\x0fbandwidth_usage\x18\x03 \x01(\x03R\x0ebandwidthUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"$\n" +
	"\tLoadQuery\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\"S\n" +
	"\fLoadResponse\x12-\n" +
	"\x04load\x18\x01 \x01(\v2\x19.realm.routing.LoadReportR\x04load\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x8a\x01\n" +
	"\fRelayRequest\x12$\n" +
	"\x0esource_peer_id\x18\x01 \x01(\fR\fsourcePeerId\x12$\n" +
	"\x0etarget_peer_id\x18\x02 \x01(\fR\ftargetPeerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"^\n" +
	"\rRelayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"relay_node\x18\x03 \x01(\fR\trelayNode\".\n" +
	"\x11ReachabilityQuery\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\"`\n" +
	"\x14ReachabilityResponse\x12'\n" +
	"\x0freachable_nodes\x18\x01 \x03(\fR\x0ereachableNodes\x12\x1f\n" +
	"\vrelay_nodes\x18\x02 \x03(\fR\n" +
	"relayNodes\"z\n" +
	"\x10GatewayStateSync\x12'\n" +
	"\x0freachable_nodes\x18\x01 \x03(\fR\x0ereachableNodes\x12\x1f\n" +
	"\vrelay_nodes\x18\x02 \x03(\fR\n" +
	"relayNodes\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampBAZ?github.com/dep2p/go-dep2p/pkg/lib/proto/realm/routing;routingpbb\x06proto3"

var (
	file_pkg_lib_proto_realm_routing_routing_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_routing_routing_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_routing_routing_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_routing_routing_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_routing_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_routing_routing_proto_rawDesc), len(file_pkg_lib_proto_realm_routing_routing_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_routing_routing_proto_rawDescData
}

var file_pkg_lib_proto_realm_routing_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_lib_proto_realm_routing_routing_proto_goTypes = []any{
	(*RouteQuery)(nil),           // 0: realm.routing.RouteQuery
	(*RouteResponse)(nil),        // 1: realm.routing.RouteResponse
	(*RouteInfo)(nil),            // 2: realm.routing.RouteInfo
	(*PathInfo)(nil),             // 3: realm.routing.PathInfo
	(*PathQuery)(nil),            // 4: realm.routing.PathQuery
	(*PathResponse)(nil),         // 5: realm.routing.PathResponse
	(*NodeMetrics)(nil),          // 6: realm.routing.NodeMetrics
	(*NodeMetricsList)(nil),      // 7: realm.routing.NodeMetricsList
	(*LoadReport)(nil),           // 8: realm.routing.LoadReport
	(*LoadQuery)(nil),            // 9: realm.routing.LoadQuery
	(*LoadResponse)(nil),         // 10: realm.routing.LoadResponse
	(*RelayRequest)(nil),         // 11: realm.routing.RelayRequest
	(*RelayResponse)(nil),        // 12: realm.routing.RelayResponse
	(*ReachabilityQuery)(nil),    // 13: realm.routing.ReachabilityQuery
	(*ReachabilityResponse)(nil), // 14: realm.routing.ReachabilityResponse
	(*GatewayStateSync)(nil),     // 15: realm.routing.GatewayStateSync
}
var file_pkg_lib_proto_realm_routing_routing_proto_depIdxs = []int32{
	2, // 0: realm.routing.RouteResponse.routes:type_name -> realm.routing.RouteInfo
	3, // 1: realm.routing.PathResponse.paths:type_name -> realm.routing.PathInfo
	6, // 2: realm.routing.NodeMetricsList.metrics:type_name -> realm.routing.NodeMetrics
	8, // 3: realm.routing.LoadResponse.load:type_name -> realm.routing.LoadReport
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_routing_routing_proto_init() }
func file_pkg_lib_proto_realm_routing_routing_proto_init() {
	if File_pkg_lib_proto_realm_routing_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_routing_routing_proto_rawDesc), len(file_pkg_lib_proto_realm_routing_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_routing_routing_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_routing_routing_proto_depIdxs,
		MessageInfos:      file_pkg_lib_proto_realm_routing_routing_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_routing_routing_proto = out.File
	file_pkg_lib_proto_realm_routing_routing_proto_goTypes = nil
	file_pkg_lib_proto_realm_routing_routing_proto_depIdxs = nil
}
