// DeP2P Peer Protocol Definitions
// 节点相关消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: peer/peer.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddressType 地址类型
//
// 用于区分不同来源的地址，便于连接策略优化：
// - DIRECT: 直连地址，优先使用
// - RELAY: 中继地址，作为兜底
// - OBSERVED: 观测到的地址（其他节点报告）
type AddressType int32

const (
	// ADDRESS_TYPE_UNSPECIFIED 未指定类型（向后兼容）
	AddressType_ADDRESS_TYPE_UNSPECIFIED AddressType = 0
	// ADDRESS_TYPE_DIRECT 直连地址
	AddressType_ADDRESS_TYPE_DIRECT AddressType = 1
	// ADDRESS_TYPE_RELAY 中继地址
	AddressType_ADDRESS_TYPE_RELAY AddressType = 2
	// ADDRESS_TYPE_OBSERVED 观测地址（他人报告）
	AddressType_ADDRESS_TYPE_OBSERVED AddressType = 3
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "ADDRESS_TYPE_UNSPECIFIED",
		1: "ADDRESS_TYPE_DIRECT",
		2: "ADDRESS_TYPE_RELAY",
		3: "ADDRESS_TYPE_OBSERVED",
	}
	AddressType_value = map[string]int32{
		"ADDRESS_TYPE_UNSPECIFIED": 0,
		"ADDRESS_TYPE_DIRECT":      1,
		"ADDRESS_TYPE_RELAY":       2,
		"ADDRESS_TYPE_OBSERVED":    3,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_peer_proto_enumTypes[0].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_peer_peer_proto_enumTypes[0]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{0}
}

// PeerID 节点 ID
type PeerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerID) Reset() {
	*x = PeerID{}
	mi := &file_peer_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerID) ProtoMessage() {}

func (x *PeerID) ProtoReflect() protoreflect.Message {
	mi := &file_peer_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerID.ProtoReflect.Descriptor instead.
func (*PeerID) Descriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PeerID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// AddrInfo 节点地址信息
type AddrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *PeerID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	mi := &file_peer_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peer_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{1}
}

func (x *AddrInfo) GetId() *PeerID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AddrInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// PeerRecord 节点记录
type PeerRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id 节点 ID
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// seq 序列号
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// addresses 地址列表（向后兼容，混合类型）
	Addresses []*AddressInfo `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// direct_addrs 直连地址列表（v2.0 推荐使用）
	//
	// 节点的公网或内网可达地址，优先用于连接。
	DirectAddrs [][]byte `protobuf:"bytes,4,rep,name=direct_addrs,json=directAddrs,proto3" json:"direct_addrs,omitempty"`
	// relay_addrs 中继地址列表（v2.0 推荐使用）
	//
	// 通过 Relay 节点可达的地址，格式: /p2p/relay-peer-id/p2p-circuit/p2p/target-peer-id
	// 当直连失败时作为兜底。
	RelayAddrs    [][]byte `protobuf:"bytes,5,rep,name=relay_addrs,json=relayAddrs,proto3" json:"relay_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRecord) Reset() {
	*x = PeerRecord{}
	mi := &file_peer_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecord) ProtoMessage() {}

func (x *PeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_peer_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecord.ProtoReflect.Descriptor instead.
func (*PeerRecord) Descriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{2}
}

func (x *PeerRecord) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PeerRecord) GetAddresses() []*AddressInfo {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerRecord) GetDirectAddrs() [][]byte {
	if x != nil {
		return x.DirectAddrs
	}
	return nil
}

func (x *PeerRecord) GetRelayAddrs() [][]byte {
	if x != nil {
		return x.RelayAddrs
	}
	return nil
}

// AddressInfo 地址信息
type AddressInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// multiaddr 地址（multiaddr 编码）
	Multiaddr []byte `protobuf:"bytes,1,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	// type 地址类型
	//
	// v2.0 新增：用于区分 direct/relay/observed 地址
	Type AddressType `protobuf:"varint,2,opt,name=type,proto3,enum=dep2p.peer.AddressType" json:"type,omitempty"`
	// ttl 地址有效期（秒）
	//
	// 0 表示使用默认 TTL
	Ttl uint64 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// certified 是否经过认证
	//
	// true 表示地址经过 AutoNAT 或其他机制验证
	Certified     bool `protobuf:"varint,4,opt,name=certified,proto3" json:"certified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_peer_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peer_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{3}
}

func (x *AddressInfo) GetMultiaddr() []byte {
	if x != nil {
		return x.Multiaddr
	}
	return nil
}

func (x *AddressInfo) GetType() AddressType {
	if x != nil {
		return x.Type
	}
	return AddressType_ADDRESS_TYPE_UNSPECIFIED
}

func (x *AddressInfo) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *AddressInfo) GetCertified() bool {
	if x != nil {
		return x.Certified
	}
	return false
}

// SignedPeerRecord 签名的节点记录
type SignedPeerRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPeerRecord) Reset() {
	*x = SignedPeerRecord{}
	mi := &file_peer_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPeerRecord) ProtoMessage() {}

func (x *SignedPeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_peer_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPeerRecord.ProtoReflect.Descriptor instead.
func (*SignedPeerRecord) Descriptor() ([]byte, []int) {
	return file_peer_peer_proto_rawDescGZIP(), []int{4}
}

func (x *SignedPeerRecord) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *SignedPeerRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPeerRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedPeerRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_peer_peer_proto protoreflect.FileDescriptor

const file_peer_peer_proto_rawDesc = "" +
	"\n" +
	"\x0fpeer/peer.proto\x12\n" +
	"dep2p.peer\"\x18\n" +
	"\x06PeerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"D\n" +
	"\bAddrInfo\x12\"\n" +
	"\x02id\x18\x01 \x01(\v2\x12.dep2p.peer.PeerIDR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\"\xb2\x01\n" +
	"\n" +
	"PeerRecord\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x125\n" +
	"\taddresses\x18\x03 \x03(\v2\x17.dep2p.peer.AddressInfoR\taddresses\x12!\n" +
	"\fdirect_addrs\x18\x04 \x03(\fR\vdirectAddrs\x12\x1f\n" +
	"\vrelay_addrs\x18\x05 \x03(\fR\n" +
	"relayAddrs\"\x88\x01\n" +
	"\vAddressInfo\x12\x1c\n" +
	"\tmultiaddr\x18\x01 \x01(\fR\tmultiaddr\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.dep2p.peer.AddressTypeR\x04type\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\x12\x1c\n" +
	"\tcertified\x18\x04 \x01(\bR\tcertified\"\x82\x01\n" +
	"\x10SignedPeerRecord\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature*w\n" +
	"\vAddressType\x12\x1c\n" +
	"\x18ADDRESS_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ADDRESS_TYPE_DIRECT\x10\x01\x12\x16\n" +
	"\x12ADDRESS_TYPE_RELAY\x10\x02\x12\x19\n" +
	"\x15ADDRESS_TYPE_OBSERVED\x10\x03B'Z%github.com/dep2p/dep2p/pkg/proto/peerb\x06proto3"

var (
	file_peer_peer_proto_rawDescOnce sync.Once
	file_peer_peer_proto_rawDescData []byte
)

func file_peer_peer_proto_rawDescGZIP() []byte {
	file_peer_peer_proto_rawDescOnce.Do(func() {
		file_peer_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_peer_proto_rawDesc), len(file_peer_peer_proto_rawDesc)))
	})
	return file_peer_peer_proto_rawDescData
}

var file_peer_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peer_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peer_peer_proto_goTypes = []any{
	(AddressType)(0),         // 0: dep2p.peer.AddressType
	(*PeerID)(nil),           // 1: dep2p.peer.PeerID
	(*AddrInfo)(nil),         // 2: dep2p.peer.AddrInfo
	(*PeerRecord)(nil),       // 3: dep2p.peer.PeerRecord
	(*AddressInfo)(nil),      // 4: dep2p.peer.AddressInfo
	(*SignedPeerRecord)(nil), // 5: dep2p.peer.SignedPeerRecord
}
var file_peer_peer_proto_depIdxs = []int32{
	1, // 0: dep2p.peer.AddrInfo.id:type_name -> dep2p.peer.PeerID
	4, // 1: dep2p.peer.PeerRecord.addresses:type_name -> dep2p.peer.AddressInfo
	0, // 2: dep2p.peer.AddressInfo.type:type_name -> dep2p.peer.AddressType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_peer_peer_proto_init() }
func file_peer_peer_proto_init() {
	if File_peer_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_peer_proto_rawDesc), len(file_peer_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_peer_proto_goTypes,
		DependencyIndexes: file_peer_peer_proto_depIdxs,
		EnumInfos:         file_peer_peer_proto_enumTypes,
		MessageInfos:      file_peer_peer_proto_msgTypes,
	}.Build()
	File_peer_peer_proto = out.File
	file_peer_peer_proto_goTypes = nil
	file_peer_peer_proto_depIdxs = nil
}
