// DeP2P Messaging Protocol Definitions
// 消息传递协议消息定义
//
// Protocol: /dep2p/app/<realmID>/messaging/1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: messaging/messaging.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
type MessageType int32

const (
	MessageType_DIRECT    MessageType = 0 // 点对点消息
	MessageType_BROADCAST MessageType = 1 // 广播消息
	MessageType_ACK       MessageType = 2 // 确认消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "DIRECT",
		1: "BROADCAST",
		2: "ACK",
	}
	MessageType_value = map[string]int32{
		"DIRECT":    0,
		"BROADCAST": 1,
		"ACK":       2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messaging_messaging_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messaging_messaging_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

// Priority 消息优先级
type Priority int32

const (
	Priority_LOW    Priority = 0
	Priority_NORMAL Priority = 1
	Priority_HIGH   Priority = 2
	Priority_URGENT Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "LOW",
		1: "NORMAL",
		2: "HIGH",
		3: "URGENT",
	}
	Priority_value = map[string]int32{
		"LOW":    0,
		"NORMAL": 1,
		"HIGH":   2,
		"URGENT": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_messaging_messaging_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_messaging_messaging_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

// status 确认状态
type Ack_Status int32

const (
	Ack_RECEIVED  Ack_Status = 0 // 已接收
	Ack_PROCESSED Ack_Status = 1 // 已处理
	Ack_FAILED    Ack_Status = 2 // 处理失败
)

// Enum value maps for Ack_Status.
var (
	Ack_Status_name = map[int32]string{
		0: "RECEIVED",
		1: "PROCESSED",
		2: "FAILED",
	}
	Ack_Status_value = map[string]int32{
		"RECEIVED":  0,
		"PROCESSED": 1,
		"FAILED":    2,
	}
)

func (x Ack_Status) Enum() *Ack_Status {
	p := new(Ack_Status)
	*p = x
	return p
}

func (x Ack_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_messaging_messaging_proto_enumTypes[2].Descriptor()
}

func (Ack_Status) Type() protoreflect.EnumType {
	return &file_messaging_messaging_proto_enumTypes[2]
}

func (x Ack_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack_Status.Descriptor instead.
func (Ack_Status) EnumDescriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{1, 0}
}

// Message 消息
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 消息 ID（UUID）
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// from 发送者 PeerID
	From []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// to 接收者 PeerID（点对点消息）
	To []byte `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// topic 主题（广播消息）
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// type 消息类型
	Type MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=dep2p.messaging.MessageType" json:"type,omitempty"`
	// priority 优先级
	Priority Priority `protobuf:"varint,6,opt,name=priority,proto3,enum=dep2p.messaging.Priority" json:"priority,omitempty"`
	// payload 消息载荷
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// timestamp 发送时间戳
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ttl 消息存活时间（秒）
	Ttl uint32 `protobuf:"varint,9,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// signature 消息签名
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	// metadata 元数据
	Metadata      map[string][]byte `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messaging_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_DIRECT
}

func (x *Message) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ack 确认消息
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id 被确认的消息 ID
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// from 确认者 PeerID
	From          []byte     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Status        Ack_Status `protobuf:"varint,3,opt,name=status,proto3,enum=dep2p.messaging.Ack_Status" json:"status,omitempty"`
	Timestamp     uint64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_messaging_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Ack) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Ack) GetStatus() Ack_Status {
	if x != nil {
		return x.Status
	}
	return Ack_RECEIVED
}

func (x *Ack) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Query 消息查询
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from 发送者过滤
	From []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// to 接收者过滤
	To []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// topic 主题过滤
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// after 时间过滤（之后）
	After uint64 `protobuf:"varint,4,opt,name=after,proto3" json:"after,omitempty"`
	// before 时间过滤（之前）
	Before uint64 `protobuf:"varint,5,opt,name=before,proto3" json:"before,omitempty"`
	// limit 结果限制
	Limit         uint32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_messaging_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Query) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Query) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Query) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *Query) GetBefore() uint64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *Query) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// QueryResponse 查询响应
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Cursor        []byte                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_messaging_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_messaging_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QueryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QueryResponse) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

var File_messaging_messaging_proto protoreflect.FileDescriptor

const file_messaging_messaging_proto_rawDesc = "" +
	"\n" +
	"\x19messaging/messaging.proto\x12\x0fdep2p.messaging\"\xa5\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\fR\x02to\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x120\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1c.dep2p.messaging.MessageTypeR\x04type\x125\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x19.dep2p.messaging.PriorityR\bpriority\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12\x10\n" +
	"\x03ttl\x18\t \x01(\rR\x03ttl\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x12B\n" +
	"\bmetadata\x18\v \x03(\v2&.dep2p.messaging.Message.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.dep2p.messaging.Ack.StatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"1\n" +
	"\x06Status\x12\f\n" +
	"\bRECEIVED\x10\x00\x12\r\n" +
	"\tPROCESSED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\"\x85\x01\n" +
	"\x05Query\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x14\n" +
	"\x05after\x18\x04 \x01(\x04R\x05after\x12\x16\n" +
	"\x06before\x18\x05 \x01(\x04R\x06before\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\"x\n" +
	"\rQueryResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.dep2p.messaging.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\fR\x06cursor*1\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\r\n" +
	"\tBROADCAST\x10\x01\x12\a\n" +
	"\x03ACK\x10\x02*5\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\n" +
	"\n" +
	"\x06URGENT\x10\x03B,Z*github.com/dep2p/dep2p/pkg/proto/messagingb\x06proto3"

var (
	file_messaging_messaging_proto_rawDescOnce sync.Once
	file_messaging_messaging_proto_rawDescData []byte
)

func file_messaging_messaging_proto_rawDescGZIP() []byte {
	file_messaging_messaging_proto_rawDescOnce.Do(func() {
		file_messaging_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messaging_messaging_proto_rawDesc), len(file_messaging_messaging_proto_rawDesc)))
	})
	return file_messaging_messaging_proto_rawDescData
}

var file_messaging_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_messaging_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messaging_messaging_proto_goTypes = []any{
	(MessageType)(0),      // 0: dep2p.messaging.MessageType
	(Priority)(0),         // 1: dep2p.messaging.Priority
	(Ack_Status)(0),       // 2: dep2p.messaging.Ack.Status
	(*Message)(nil),       // 3: dep2p.messaging.Message
	(*Ack)(nil),           // 4: dep2p.messaging.Ack
	(*Query)(nil),         // 5: dep2p.messaging.Query
	(*QueryResponse)(nil), // 6: dep2p.messaging.QueryResponse
	nil,                   // 7: dep2p.messaging.Message.MetadataEntry
}
var file_messaging_messaging_proto_depIdxs = []int32{
	0, // 0: dep2p.messaging.Message.type:type_name -> dep2p.messaging.MessageType
	1, // 1: dep2p.messaging.Message.priority:type_name -> dep2p.messaging.Priority
	7, // 2: dep2p.messaging.Message.metadata:type_name -> dep2p.messaging.Message.MetadataEntry
	2, // 3: dep2p.messaging.Ack.status:type_name -> dep2p.messaging.Ack.Status
	3, // 4: dep2p.messaging.QueryResponse.messages:type_name -> dep2p.messaging.Message
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_messaging_messaging_proto_init() }
func file_messaging_messaging_proto_init() {
	if File_messaging_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messaging_messaging_proto_rawDesc), len(file_messaging_messaging_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messaging_messaging_proto_goTypes,
		DependencyIndexes: file_messaging_messaging_proto_depIdxs,
		EnumInfos:         file_messaging_messaging_proto_enumTypes,
		MessageInfos:      file_messaging_messaging_proto_msgTypes,
	}.Build()
	File_messaging_messaging_proto = out.File
	file_messaging_messaging_proto_goTypes = nil
	file_messaging_messaging_proto_depIdxs = nil
}
