// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/memberleave/member_leave.proto

package memberleavepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeaveReason 离开原因
type LeaveReason int32

const (
	// LEAVE_REASON_UNKNOWN 未知原因
	LeaveReason_LEAVE_REASON_UNKNOWN LeaveReason = 0
	// LEAVE_REASON_GRACEFUL 优雅离开（主动关闭）
	LeaveReason_LEAVE_REASON_GRACEFUL LeaveReason = 1
	// LEAVE_REASON_KICKED 被踢出（管理员操作）
	LeaveReason_LEAVE_REASON_KICKED LeaveReason = 2
	// LEAVE_REASON_WITNESS 见证人报告（其他成员检测到断开）
	LeaveReason_LEAVE_REASON_WITNESS LeaveReason = 3
)

// Enum value maps for LeaveReason.
var (
	LeaveReason_name = map[int32]string{
		0: "LEAVE_REASON_UNKNOWN",
		1: "LEAVE_REASON_GRACEFUL",
		2: "LEAVE_REASON_KICKED",
		3: "LEAVE_REASON_WITNESS",
	}
	LeaveReason_value = map[string]int32{
		"LEAVE_REASON_UNKNOWN":  0,
		"LEAVE_REASON_GRACEFUL": 1,
		"LEAVE_REASON_KICKED":   2,
		"LEAVE_REASON_WITNESS":  3,
	}
)

func (x LeaveReason) Enum() *LeaveReason {
	p := new(LeaveReason)
	*p = x
	return p
}

func (x LeaveReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaveReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lib_proto_realm_memberleave_member_leave_proto_enumTypes[0].Descriptor()
}

func (LeaveReason) Type() protoreflect.EnumType {
	return &file_pkg_lib_proto_realm_memberleave_member_leave_proto_enumTypes[0]
}

func (x LeaveReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaveReason.Descriptor instead.
func (LeaveReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescGZIP(), []int{0}
}

// MemberLeave 成员离开消息
//
// 当成员优雅离开 Realm 时广播此消息，通知其他成员立即更新成员列表。
// 检测延迟目标：< 100ms
//
// 安全约束：
//   - 必须包含发送者签名
//   - 时间戳有效期：30s
//   - 防重放：每个 peer_id + realm_id + timestamp 组合只处理一次
type MemberLeave struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id 离开成员的 Peer ID（bytes 格式）
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// realm_id Realm ID（bytes 格式，与成员管理协议一致）
	RealmId []byte `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// reason 离开原因
	Reason LeaveReason `protobuf:"varint,3,opt,name=reason,proto3,enum=realm.memberleave.LeaveReason" json:"reason,omitempty"`
	// timestamp 消息时间戳（Unix 纳秒）
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// signature 签名（使用 peer_id 对应的私钥签名）
	// 签名内容：peer_id || realm_id || reason || timestamp
	Signature     []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLeave) Reset() {
	*x = MemberLeave{}
	mi := &file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLeave) ProtoMessage() {}

func (x *MemberLeave) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLeave.ProtoReflect.Descriptor instead.
func (*MemberLeave) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescGZIP(), []int{0}
}

func (x *MemberLeave) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *MemberLeave) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *MemberLeave) GetReason() LeaveReason {
	if x != nil {
		return x.Reason
	}
	return LeaveReason_LEAVE_REASON_UNKNOWN
}

func (x *MemberLeave) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MemberLeave) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MemberLeaveAck 成员离开确认
//
// 可选的确认消息，用于验证离开通知已被接收。
type MemberLeaveAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id 发送确认的 Peer ID
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// leaving_peer_id 离开的 Peer ID
	LeavingPeerId []byte `protobuf:"bytes,2,opt,name=leaving_peer_id,json=leavingPeerId,proto3" json:"leaving_peer_id,omitempty"`
	// timestamp 确认时间戳
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLeaveAck) Reset() {
	*x = MemberLeaveAck{}
	mi := &file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLeaveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLeaveAck) ProtoMessage() {}

func (x *MemberLeaveAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLeaveAck.ProtoReflect.Descriptor instead.
func (*MemberLeaveAck) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescGZIP(), []int{1}
}

func (x *MemberLeaveAck) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *MemberLeaveAck) GetLeavingPeerId() []byte {
	if x != nil {
		return x.LeavingPeerId
	}
	return nil
}

func (x *MemberLeaveAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_lib_proto_realm_memberleave_member_leave_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDesc = "" +
	"\n" +
	"2pkg/lib/proto/realm/memberleave/member_leave.proto\x12\x11realm.memberleave\"\xb5\x01\n" +
	"\vMemberLeave\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\fR\arealmId\x126\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x1e.realm.memberleave.LeaveReasonR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"o\n" +
	"\x0eMemberLeaveAck\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12&\n" +
	"\x0fleaving_peer_id\x18\x02 \x01(\fR\rleavingPeerId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp*u\n" +
	"\vLeaveReason\x12\x18\n" +
	"\x14LEAVE_REASON_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15LEAVE_REASON_GRACEFUL\x10\x01\x12\x17\n" +
	"\x13LEAVE_REASON_KICKED\x10\x02\x12\x18\n" +
	"\x14LEAVE_REASON_WITNESS\x10\x03BIZGgithub.com/dep2p/go-dep2p/pkg/lib/proto/realm/memberleave;memberleavepbb\x06proto3"

var (
	file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDesc), len(file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDescData
}

var file_pkg_lib_proto_realm_memberleave_member_leave_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_lib_proto_realm_memberleave_member_leave_proto_goTypes = []any{
	(LeaveReason)(0),       // 0: realm.memberleave.LeaveReason
	(*MemberLeave)(nil),    // 1: realm.memberleave.MemberLeave
	(*MemberLeaveAck)(nil), // 2: realm.memberleave.MemberLeaveAck
}
var file_pkg_lib_proto_realm_memberleave_member_leave_proto_depIdxs = []int32{
	0, // 0: realm.memberleave.MemberLeave.reason:type_name -> realm.memberleave.LeaveReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_memberleave_member_leave_proto_init() }
func file_pkg_lib_proto_realm_memberleave_member_leave_proto_init() {
	if File_pkg_lib_proto_realm_memberleave_member_leave_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDesc), len(file_pkg_lib_proto_realm_memberleave_member_leave_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_memberleave_member_leave_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_memberleave_member_leave_proto_depIdxs,
		EnumInfos:         file_pkg_lib_proto_realm_memberleave_member_leave_proto_enumTypes,
		MessageInfos:      file_pkg_lib_proto_realm_memberleave_member_leave_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_memberleave_member_leave_proto = out.File
	file_pkg_lib_proto_realm_memberleave_member_leave_proto_goTypes = nil
	file_pkg_lib_proto_realm_memberleave_member_leave_proto_depIdxs = nil
}
