// DeP2P Hole Punch Protocol Definitions
// NAT 打洞协议消息定义
// 规范: https://github.com/libp2p/specs/blob/master/relay/DCUtR.md

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: holepunch/holepunch.proto

package holepunch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type 打洞消息类型
type Type int32

const (
	Type_CONNECT Type = 0 // 连接请求
	Type_SYNC    Type = 1 // 同步消息
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "CONNECT",
		1: "SYNC",
	}
	Type_value = map[string]int32{
		"CONNECT": 0,
		"SYNC":    1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_holepunch_holepunch_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_holepunch_holepunch_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_holepunch_holepunch_proto_rawDescGZIP(), []int{0}
}

// HolePunch 打洞消息
type HolePunch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 消息类型
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.holepunch.Type" json:"type,omitempty"`
	// obs_addrs 观察到的地址列表（multiaddr 格式）
	ObsAddrs      [][]byte `protobuf:"bytes,2,rep,name=obs_addrs,json=obsAddrs,proto3" json:"obs_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolePunch) Reset() {
	*x = HolePunch{}
	mi := &file_holepunch_holepunch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolePunch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunch) ProtoMessage() {}

func (x *HolePunch) ProtoReflect() protoreflect.Message {
	mi := &file_holepunch_holepunch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunch.ProtoReflect.Descriptor instead.
func (*HolePunch) Descriptor() ([]byte, []int) {
	return file_holepunch_holepunch_proto_rawDescGZIP(), []int{0}
}

func (x *HolePunch) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_CONNECT
}

func (x *HolePunch) GetObsAddrs() [][]byte {
	if x != nil {
		return x.ObsAddrs
	}
	return nil
}

var File_holepunch_holepunch_proto protoreflect.FileDescriptor

const file_holepunch_holepunch_proto_rawDesc = "" +
	"\n" +
	"\x19holepunch/holepunch.proto\x12\x0fdep2p.holepunch\"S\n" +
	"\tHolePunch\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.dep2p.holepunch.TypeR\x04type\x12\x1b\n" +
	"\tobs_addrs\x18\x02 \x03(\fR\bobsAddrs*\x1d\n" +
	"\x04Type\x12\v\n" +
	"\aCONNECT\x10\x00\x12\b\n" +
	"\x04SYNC\x10\x01B,Z*github.com/dep2p/dep2p/pkg/proto/holepunchb\x06proto3"

var (
	file_holepunch_holepunch_proto_rawDescOnce sync.Once
	file_holepunch_holepunch_proto_rawDescData []byte
)

func file_holepunch_holepunch_proto_rawDescGZIP() []byte {
	file_holepunch_holepunch_proto_rawDescOnce.Do(func() {
		file_holepunch_holepunch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_holepunch_holepunch_proto_rawDesc), len(file_holepunch_holepunch_proto_rawDesc)))
	})
	return file_holepunch_holepunch_proto_rawDescData
}

var file_holepunch_holepunch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_holepunch_holepunch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_holepunch_holepunch_proto_goTypes = []any{
	(Type)(0),         // 0: dep2p.holepunch.Type
	(*HolePunch)(nil), // 1: dep2p.holepunch.HolePunch
}
var file_holepunch_holepunch_proto_depIdxs = []int32{
	0, // 0: dep2p.holepunch.HolePunch.type:type_name -> dep2p.holepunch.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_holepunch_holepunch_proto_init() }
func file_holepunch_holepunch_proto_init() {
	if File_holepunch_holepunch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_holepunch_holepunch_proto_rawDesc), len(file_holepunch_holepunch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_holepunch_holepunch_proto_goTypes,
		DependencyIndexes: file_holepunch_holepunch_proto_depIdxs,
		EnumInfos:         file_holepunch_holepunch_proto_enumTypes,
		MessageInfos:      file_holepunch_holepunch_proto_msgTypes,
	}.Build()
	File_holepunch_holepunch_proto = out.File
	file_holepunch_holepunch_proto_goTypes = nil
	file_holepunch_holepunch_proto_depIdxs = nil
}
