// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/witness/witness.proto

package witnesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DetectionMethod 检测方法
//
// 描述见证人如何检测到节点断开的方法。
type DetectionMethod int32

const (
	// DETECTION_METHOD_UNKNOWN 未知检测方法
	DetectionMethod_DETECTION_METHOD_UNKNOWN DetectionMethod = 0
	// DETECTION_METHOD_QUIC_CLOSE QUIC 连接正常关闭
	// 对方发送 CONNECTION_CLOSE 帧（优雅断开）
	DetectionMethod_DETECTION_METHOD_QUIC_CLOSE DetectionMethod = 1
	// DETECTION_METHOD_QUIC_TIMEOUT QUIC 空闲超时
	// 超过 MaxIdleTimeout（6s）未收到任何数据包
	DetectionMethod_DETECTION_METHOD_QUIC_TIMEOUT DetectionMethod = 2
	// DETECTION_METHOD_PING_FAILED Liveness Ping 失败
	// 连续 3 次 Ping 超时（兜底检测机制）
	DetectionMethod_DETECTION_METHOD_PING_FAILED DetectionMethod = 3
	// DETECTION_METHOD_RELAY_CIRCUIT Relay 电路关闭
	// Relay 服务器检测到中继电路断开
	DetectionMethod_DETECTION_METHOD_RELAY_CIRCUIT DetectionMethod = 4
)

// Enum value maps for DetectionMethod.
var (
	DetectionMethod_name = map[int32]string{
		0: "DETECTION_METHOD_UNKNOWN",
		1: "DETECTION_METHOD_QUIC_CLOSE",
		2: "DETECTION_METHOD_QUIC_TIMEOUT",
		3: "DETECTION_METHOD_PING_FAILED",
		4: "DETECTION_METHOD_RELAY_CIRCUIT",
	}
	DetectionMethod_value = map[string]int32{
		"DETECTION_METHOD_UNKNOWN":       0,
		"DETECTION_METHOD_QUIC_CLOSE":    1,
		"DETECTION_METHOD_QUIC_TIMEOUT":  2,
		"DETECTION_METHOD_PING_FAILED":   3,
		"DETECTION_METHOD_RELAY_CIRCUIT": 4,
	}
)

func (x DetectionMethod) Enum() *DetectionMethod {
	p := new(DetectionMethod)
	*p = x
	return p
}

func (x DetectionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lib_proto_realm_witness_witness_proto_enumTypes[0].Descriptor()
}

func (DetectionMethod) Type() protoreflect.EnumType {
	return &file_pkg_lib_proto_realm_witness_witness_proto_enumTypes[0]
}

func (x DetectionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionMethod.Descriptor instead.
func (DetectionMethod) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP(), []int{0}
}

// ConfirmationType 确认类型
//
// 见证人对断开报告的确认响应。
type ConfirmationType int32

const (
	// CONFIRMATION_TYPE_ABSTAIN 弃权
	// 见证人无法确认（如未与目标节点有过连接）
	ConfirmationType_CONFIRMATION_TYPE_ABSTAIN ConfirmationType = 0
	// CONFIRMATION_TYPE_AGREE 同意
	// 见证人也检测到目标节点断开
	ConfirmationType_CONFIRMATION_TYPE_AGREE ConfirmationType = 1
	// CONFIRMATION_TYPE_DISAGREE 反对
	// 见证人仍能与目标节点通信
	ConfirmationType_CONFIRMATION_TYPE_DISAGREE ConfirmationType = 2
)

// Enum value maps for ConfirmationType.
var (
	ConfirmationType_name = map[int32]string{
		0: "CONFIRMATION_TYPE_ABSTAIN",
		1: "CONFIRMATION_TYPE_AGREE",
		2: "CONFIRMATION_TYPE_DISAGREE",
	}
	ConfirmationType_value = map[string]int32{
		"CONFIRMATION_TYPE_ABSTAIN":  0,
		"CONFIRMATION_TYPE_AGREE":    1,
		"CONFIRMATION_TYPE_DISAGREE": 2,
	}
)

func (x ConfirmationType) Enum() *ConfirmationType {
	p := new(ConfirmationType)
	*p = x
	return p
}

func (x ConfirmationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lib_proto_realm_witness_witness_proto_enumTypes[1].Descriptor()
}

func (ConfirmationType) Type() protoreflect.EnumType {
	return &file_pkg_lib_proto_realm_witness_witness_proto_enumTypes[1]
}

func (x ConfirmationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationType.Descriptor instead.
func (ConfirmationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP(), []int{1}
}

// WitnessReport 见证报告
//
// 当节点检测到另一成员断开时，向 Realm 广播此消息。
// 其他成员收到后会验证并响应 WitnessConfirmation。
//
// 安全约束：
//   - 必须包含报告者签名
//   - 时间戳有效期：10s
//   - 限速：每分钟最多 10 个报告（防止 DoS）
type WitnessReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report_id 报告唯一标识（UUID 或 hash）
	ReportId []byte `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// reporter_id 报告者 Peer ID
	ReporterId []byte `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	// target_id 被报告断开的目标 Peer ID
	TargetId []byte `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// realm_id Realm ID
	RealmId []byte `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// detection_method 检测方法
	DetectionMethod DetectionMethod `protobuf:"varint,5,opt,name=detection_method,json=detectionMethod,proto3,enum=realm.witness.DetectionMethod" json:"detection_method,omitempty"`
	// timestamp 报告时间戳（Unix 纳秒）
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// last_contact_timestamp 最后一次成功通信的时间戳（Unix 纳秒）
	// 用于帮助其他见证人判断是否有更新的联系记录
	LastContactTimestamp int64 `protobuf:"varint,7,opt,name=last_contact_timestamp,json=lastContactTimestamp,proto3" json:"last_contact_timestamp,omitempty"`
	// last_contact_proof 最后联系证明（可选）
	// 可以是最后一次交换的消息 hash 或协议交互记录
	// 用于证明报告者确实与目标节点有过通信
	LastContactProof []byte `protobuf:"bytes,8,opt,name=last_contact_proof,json=lastContactProof,proto3" json:"last_contact_proof,omitempty"`
	// signature 报告者签名
	// 签名内容：report_id || reporter_id || target_id || realm_id || detection_method || timestamp
	Signature     []byte `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessReport) Reset() {
	*x = WitnessReport{}
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessReport) ProtoMessage() {}

func (x *WitnessReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessReport.ProtoReflect.Descriptor instead.
func (*WitnessReport) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP(), []int{0}
}

func (x *WitnessReport) GetReportId() []byte {
	if x != nil {
		return x.ReportId
	}
	return nil
}

func (x *WitnessReport) GetReporterId() []byte {
	if x != nil {
		return x.ReporterId
	}
	return nil
}

func (x *WitnessReport) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *WitnessReport) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *WitnessReport) GetDetectionMethod() DetectionMethod {
	if x != nil {
		return x.DetectionMethod
	}
	return DetectionMethod_DETECTION_METHOD_UNKNOWN
}

func (x *WitnessReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WitnessReport) GetLastContactTimestamp() int64 {
	if x != nil {
		return x.LastContactTimestamp
	}
	return 0
}

func (x *WitnessReport) GetLastContactProof() []byte {
	if x != nil {
		return x.LastContactProof
	}
	return nil
}

func (x *WitnessReport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// WitnessConfirmation 见证确认
//
// 见证人对 WitnessReport 的响应，表示是否同意目标节点已断开。
//
// 投票规则：
//   - 快速路径（成员数 < 10 且 QUIC_CLOSE）：单票 AGREE 且无反对即可确认
//   - 标准路径：简单多数（> 50% AGREE）确认
//   - 任何 DISAGREE 触发重新验证
type WitnessConfirmation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report_id 对应的报告 ID
	ReportId []byte `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// witness_id 见证人 Peer ID
	WitnessId []byte `protobuf:"bytes,2,opt,name=witness_id,json=witnessId,proto3" json:"witness_id,omitempty"`
	// confirmation_type 确认类型
	ConfirmationType ConfirmationType `protobuf:"varint,3,opt,name=confirmation_type,json=confirmationType,proto3,enum=realm.witness.ConfirmationType" json:"confirmation_type,omitempty"`
	// timestamp 确认时间戳（Unix 纳秒）
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// last_contact_timestamp 见证人与目标节点的最后联系时间
	// 如果比报告者更新，说明目标节点可能仍在线
	LastContactTimestamp int64 `protobuf:"varint,5,opt,name=last_contact_timestamp,json=lastContactTimestamp,proto3" json:"last_contact_timestamp,omitempty"`
	// reason 确认原因说明（可选，用于调试）
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// signature 见证人签名
	// 签名内容：report_id || witness_id || confirmation_type || timestamp
	Signature     []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessConfirmation) Reset() {
	*x = WitnessConfirmation{}
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessConfirmation) ProtoMessage() {}

func (x *WitnessConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessConfirmation.ProtoReflect.Descriptor instead.
func (*WitnessConfirmation) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP(), []int{1}
}

func (x *WitnessConfirmation) GetReportId() []byte {
	if x != nil {
		return x.ReportId
	}
	return nil
}

func (x *WitnessConfirmation) GetWitnessId() []byte {
	if x != nil {
		return x.WitnessId
	}
	return nil
}

func (x *WitnessConfirmation) GetConfirmationType() ConfirmationType {
	if x != nil {
		return x.ConfirmationType
	}
	return ConfirmationType_CONFIRMATION_TYPE_ABSTAIN
}

func (x *WitnessConfirmation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WitnessConfirmation) GetLastContactTimestamp() int64 {
	if x != nil {
		return x.LastContactTimestamp
	}
	return 0
}

func (x *WitnessConfirmation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WitnessConfirmation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// WitnessVotingResult 见证投票结果
//
// 汇总所有见证确认后的最终结果。
// 用于内部状态跟踪，不在网络上传输。
type WitnessVotingResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report_id 对应的报告 ID
	ReportId []byte `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// target_id 目标 Peer ID
	TargetId []byte `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// confirmed 是否确认断开
	Confirmed bool `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// agree_count 同意票数
	AgreeCount int32 `protobuf:"varint,4,opt,name=agree_count,json=agreeCount,proto3" json:"agree_count,omitempty"`
	// disagree_count 反对票数
	DisagreeCount int32 `protobuf:"varint,5,opt,name=disagree_count,json=disagreeCount,proto3" json:"disagree_count,omitempty"`
	// abstain_count 弃权票数
	AbstainCount int32 `protobuf:"varint,6,opt,name=abstain_count,json=abstainCount,proto3" json:"abstain_count,omitempty"`
	// total_witnesses 总见证人数
	TotalWitnesses int32 `protobuf:"varint,7,opt,name=total_witnesses,json=totalWitnesses,proto3" json:"total_witnesses,omitempty"`
	// decision_timestamp 决策时间戳
	DecisionTimestamp int64 `protobuf:"varint,8,opt,name=decision_timestamp,json=decisionTimestamp,proto3" json:"decision_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WitnessVotingResult) Reset() {
	*x = WitnessVotingResult{}
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessVotingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessVotingResult) ProtoMessage() {}

func (x *WitnessVotingResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_witness_witness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessVotingResult.ProtoReflect.Descriptor instead.
func (*WitnessVotingResult) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP(), []int{2}
}

func (x *WitnessVotingResult) GetReportId() []byte {
	if x != nil {
		return x.ReportId
	}
	return nil
}

func (x *WitnessVotingResult) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *WitnessVotingResult) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *WitnessVotingResult) GetAgreeCount() int32 {
	if x != nil {
		return x.AgreeCount
	}
	return 0
}

func (x *WitnessVotingResult) GetDisagreeCount() int32 {
	if x != nil {
		return x.DisagreeCount
	}
	return 0
}

func (x *WitnessVotingResult) GetAbstainCount() int32 {
	if x != nil {
		return x.AbstainCount
	}
	return 0
}

func (x *WitnessVotingResult) GetTotalWitnesses() int32 {
	if x != nil {
		return x.TotalWitnesses
	}
	return 0
}

func (x *WitnessVotingResult) GetDecisionTimestamp() int64 {
	if x != nil {
		return x.DecisionTimestamp
	}
	return 0
}

var File_pkg_lib_proto_realm_witness_witness_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_witness_witness_proto_rawDesc = "" +
	"\n" +
	")pkg/lib/proto/realm/witness/witness.proto\x12\rrealm.witness\"\xf0\x02\n" +
	"\rWitnessReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\fR\breportId\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\fR\n" +
	"reporterId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\fR\btargetId\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\fR\arealmId\x12I\n" +
	"\x10detection_method\x18\x05 \x01(\x0e2\x1e.realm.witness.DetectionMethodR\x0fdetectionMethod\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x124\n" +
	"\x16last_contact_timestamp\x18\a \x01(\x03R\x14lastContactTimestamp\x12,\n" +
	"\x12last_contact_proof\x18\b \x01(\fR\x10lastContactProof\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\"\xa9\x02\n" +
	"\x13WitnessConfirmation\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\fR\breportId\x12\x1d\n" +
	"\n" +
	"witness_id\x18\x02 \x01(\fR\twitnessId\x12L\n" +
	"\x11confirmation_type\x18\x03 \x01(\x0e2\x1f.realm.witness.ConfirmationTypeR\x10confirmationType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x124\n" +
	"\x16last_contact_timestamp\x18\x05 \x01(\x03R\x14lastContactTimestamp\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xb2\x02\n" +
	"\x13WitnessVotingResult\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\fR\breportId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\fR\btargetId\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\x12\x1f\n" +
	"\vagree_count\x18\x04 \x01(\x05R\n" +
	"agreeCount\x12%\n" +
	"\x0edisagree_count\x18\x05 \x01(\x05R\rdisagreeCount\x12#\n" +
	"\rabstain_count\x18\x06 \x01(\x05R\fabstainCount\x12'\n" +
	"\x0ftotal_witnesses\x18\a \x01(\x05R\x0etotalWitnesses\x12-\n" +
	"\x12decision_timestamp\x18\b \x01(\x03R\x11decisionTimestamp*\xb9\x01\n" +
	"\x0fDetectionMethod\x12\x1c\n" +
	"\x18DETECTION_METHOD_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bDETECTION_METHOD_QUIC_CLOSE\x10\x01\x12!\n" +
	"\x1dDETECTION_METHOD_QUIC_TIMEOUT\x10\x02\x12 \n" +
	"\x1cDETECTION_METHOD_PING_FAILED\x10\x03\x12\"\n" +
	"\x1eDETECTION_METHOD_RELAY_CIRCUIT\x10\x04*n\n" +
	"\x10ConfirmationType\x12\x1d\n" +
	"\x19CONFIRMATION_TYPE_ABSTAIN\x10\x00\x12\x1b\n" +
	"\x17CONFIRMATION_TYPE_AGREE\x10\x01\x12\x1e\n" +
	"\x1aCONFIRMATION_TYPE_DISAGREE\x10\x02BAZ?github.com/dep2p/go-dep2p/pkg/lib/proto/realm/witness;witnesspbb\x06proto3"

var (
	file_pkg_lib_proto_realm_witness_witness_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_witness_witness_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_witness_witness_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_witness_witness_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_witness_witness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_witness_witness_proto_rawDesc), len(file_pkg_lib_proto_realm_witness_witness_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_witness_witness_proto_rawDescData
}

var file_pkg_lib_proto_realm_witness_witness_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_lib_proto_realm_witness_witness_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_lib_proto_realm_witness_witness_proto_goTypes = []any{
	(DetectionMethod)(0),        // 0: realm.witness.DetectionMethod
	(ConfirmationType)(0),       // 1: realm.witness.ConfirmationType
	(*WitnessReport)(nil),       // 2: realm.witness.WitnessReport
	(*WitnessConfirmation)(nil), // 3: realm.witness.WitnessConfirmation
	(*WitnessVotingResult)(nil), // 4: realm.witness.WitnessVotingResult
}
var file_pkg_lib_proto_realm_witness_witness_proto_depIdxs = []int32{
	0, // 0: realm.witness.WitnessReport.detection_method:type_name -> realm.witness.DetectionMethod
	1, // 1: realm.witness.WitnessConfirmation.confirmation_type:type_name -> realm.witness.ConfirmationType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_witness_witness_proto_init() }
func file_pkg_lib_proto_realm_witness_witness_proto_init() {
	if File_pkg_lib_proto_realm_witness_witness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_witness_witness_proto_rawDesc), len(file_pkg_lib_proto_realm_witness_witness_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_witness_witness_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_witness_witness_proto_depIdxs,
		EnumInfos:         file_pkg_lib_proto_realm_witness_witness_proto_enumTypes,
		MessageInfos:      file_pkg_lib_proto_realm_witness_witness_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_witness_witness_proto = out.File
	file_pkg_lib_proto_realm_witness_witness_proto_goTypes = nil
	file_pkg_lib_proto_realm_witness_witness_proto_depIdxs = nil
}
