// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/auth/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_REQUEST     MessageType = 1
	MessageType_MESSAGE_TYPE_CHALLENGE   MessageType = 2
	MessageType_MESSAGE_TYPE_RESPONSE    MessageType = 3
	MessageType_MESSAGE_TYPE_RESULT      MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_REQUEST",
		2: "MESSAGE_TYPE_CHALLENGE",
		3: "MESSAGE_TYPE_RESPONSE",
		4: "MESSAGE_TYPE_RESULT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_REQUEST":     1,
		"MESSAGE_TYPE_CHALLENGE":   2,
		"MESSAGE_TYPE_RESPONSE":    3,
		"MESSAGE_TYPE_RESULT":      4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lib_proto_realm_auth_auth_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_lib_proto_realm_auth_auth_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{0}
}

// AuthMode 认证模式
type AuthMode int32

const (
	AuthMode_AUTH_MODE_UNSPECIFIED AuthMode = 0
	AuthMode_AUTH_MODE_PSK         AuthMode = 1
	AuthMode_AUTH_MODE_CERT        AuthMode = 2
	AuthMode_AUTH_MODE_CUSTOM      AuthMode = 3
)

// Enum value maps for AuthMode.
var (
	AuthMode_name = map[int32]string{
		0: "AUTH_MODE_UNSPECIFIED",
		1: "AUTH_MODE_PSK",
		2: "AUTH_MODE_CERT",
		3: "AUTH_MODE_CUSTOM",
	}
	AuthMode_value = map[string]int32{
		"AUTH_MODE_UNSPECIFIED": 0,
		"AUTH_MODE_PSK":         1,
		"AUTH_MODE_CERT":        2,
		"AUTH_MODE_CUSTOM":      3,
	}
)

func (x AuthMode) Enum() *AuthMode {
	p := new(AuthMode)
	*p = x
	return p
}

func (x AuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_lib_proto_realm_auth_auth_proto_enumTypes[1].Descriptor()
}

func (AuthMode) Type() protoreflect.EnumType {
	return &file_pkg_lib_proto_realm_auth_auth_proto_enumTypes[1]
}

func (x AuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMode.Descriptor instead.
func (AuthMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{1}
}

// Message 认证协议消息
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息类型
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=realm.auth.MessageType" json:"type,omitempty"`
	// 消息载荷（根据类型解析）
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Request
	//	*Message_Challenge
	//	*Message_Response
	//	*Message_Result
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Message) GetChallenge() *AuthChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Message_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *Message) GetResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Message) GetResult() *AuthResult {
	if x != nil {
		if x, ok := x.Payload.(*Message_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Request struct {
	Request *AuthRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Message_Challenge struct {
	Challenge *AuthChallenge `protobuf:"bytes,3,opt,name=challenge,proto3,oneof"`
}

type Message_Response struct {
	Response *AuthResponse `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

type Message_Result struct {
	Result *AuthResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

func (*Message_Request) isMessage_Payload() {}

func (*Message_Challenge) isMessage_Payload() {}

func (*Message_Response) isMessage_Payload() {}

func (*Message_Result) isMessage_Payload() {}

// AuthRequest 认证请求
type AuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求节点 ID
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Realm ID
	RealmId string `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// 认证模式
	Mode AuthMode `protobuf:"varint,3,opt,name=mode,proto3,enum=realm.auth.AuthMode" json:"mode,omitempty"`
	// 请求时间戳（Unix 秒）
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 协议版本
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AuthRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *AuthRequest) GetMode() AuthMode {
	if x != nil {
		return x.Mode
	}
	return AuthMode_AUTH_MODE_UNSPECIFIED
}

func (x *AuthRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AuthChallenge 认证挑战
type AuthChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 随机 nonce
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// 挑战时间戳（Unix 秒）
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Realm ID
	RealmId       string `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AuthChallenge) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthChallenge) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

// AuthResponse 认证响应
type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 认证证明
	Proof []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	// 响应时间戳（Unix 秒）
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 节点 ID
	PeerId        string `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *AuthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// AuthResult 认证结果
type AuthResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 认证是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果失败）
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// 结果时间戳（Unix 秒）
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// TTL（认证有效期，秒）
	Ttl           int64 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthResult) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_pkg_lib_proto_realm_auth_auth_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_auth_auth_proto_rawDesc = "" +
	"\n" +
	"#pkg/lib/proto/realm/auth/auth.proto\x12\n" +
	"realm.auth\"\x9b\x02\n" +
	"\aMessage\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.realm.auth.MessageTypeR\x04type\x123\n" +
	"\arequest\x18\x02 \x01(\v2\x17.realm.auth.AuthRequestH\x00R\arequest\x129\n" +
	"\tchallenge\x18\x03 \x01(\v2\x19.realm.auth.AuthChallengeH\x00R\tchallenge\x126\n" +
	"\bresponse\x18\x04 \x01(\v2\x18.realm.auth.AuthResponseH\x00R\bresponse\x120\n" +
	"\x06result\x18\x05 \x01(\v2\x16.realm.auth.AuthResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xa3\x01\n" +
	"\vAuthRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.realm.auth.AuthModeR\x04mode\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"^\n" +
	"\rAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\"[\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\"l\n" +
	"\n" +
	"AuthResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x03R\x03ttl*\x95\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MESSAGE_TYPE_REQUEST\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_CHALLENGE\x10\x02\x12\x19\n" +
	"\x15MESSAGE_TYPE_RESPONSE\x10\x03\x12\x17\n" +
	"\x13MESSAGE_TYPE_RESULT\x10\x04*b\n" +
	"\bAuthMode\x12\x19\n" +
	"\x15AUTH_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rAUTH_MODE_PSK\x10\x01\x12\x12\n" +
	"\x0eAUTH_MODE_CERT\x10\x02\x12\x14\n" +
	"\x10AUTH_MODE_CUSTOM\x10\x03B;Z9github.com/dep2p/go-dep2p/pkg/lib/proto/realm/auth;authpbb\x06proto3"

var (
	file_pkg_lib_proto_realm_auth_auth_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_auth_auth_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_auth_auth_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_auth_auth_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_auth_auth_proto_rawDesc), len(file_pkg_lib_proto_realm_auth_auth_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_auth_auth_proto_rawDescData
}

var file_pkg_lib_proto_realm_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_lib_proto_realm_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_lib_proto_realm_auth_auth_proto_goTypes = []any{
	(MessageType)(0),      // 0: realm.auth.MessageType
	(AuthMode)(0),         // 1: realm.auth.AuthMode
	(*Message)(nil),       // 2: realm.auth.Message
	(*AuthRequest)(nil),   // 3: realm.auth.AuthRequest
	(*AuthChallenge)(nil), // 4: realm.auth.AuthChallenge
	(*AuthResponse)(nil),  // 5: realm.auth.AuthResponse
	(*AuthResult)(nil),    // 6: realm.auth.AuthResult
}
var file_pkg_lib_proto_realm_auth_auth_proto_depIdxs = []int32{
	0, // 0: realm.auth.Message.type:type_name -> realm.auth.MessageType
	3, // 1: realm.auth.Message.request:type_name -> realm.auth.AuthRequest
	4, // 2: realm.auth.Message.challenge:type_name -> realm.auth.AuthChallenge
	5, // 3: realm.auth.Message.response:type_name -> realm.auth.AuthResponse
	6, // 4: realm.auth.Message.result:type_name -> realm.auth.AuthResult
	1, // 5: realm.auth.AuthRequest.mode:type_name -> realm.auth.AuthMode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_auth_auth_proto_init() }
func file_pkg_lib_proto_realm_auth_auth_proto_init() {
	if File_pkg_lib_proto_realm_auth_auth_proto != nil {
		return
	}
	file_pkg_lib_proto_realm_auth_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Request)(nil),
		(*Message_Challenge)(nil),
		(*Message_Response)(nil),
		(*Message_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_auth_auth_proto_rawDesc), len(file_pkg_lib_proto_realm_auth_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_auth_auth_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_auth_auth_proto_depIdxs,
		EnumInfos:         file_pkg_lib_proto_realm_auth_auth_proto_enumTypes,
		MessageInfos:      file_pkg_lib_proto_realm_auth_auth_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_auth_auth_proto = out.File
	file_pkg_lib_proto_realm_auth_auth_proto_goTypes = nil
	file_pkg_lib_proto_realm_auth_auth_proto_depIdxs = nil
}
