// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/proto/rendezvous/rendezvous.proto

package rendezvous

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType Rendezvous 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// 注册请求/响应
	MessageType_MESSAGE_TYPE_REGISTER          MessageType = 1
	MessageType_MESSAGE_TYPE_REGISTER_RESPONSE MessageType = 2
	// 取消注册请求/响应
	MessageType_MESSAGE_TYPE_UNREGISTER          MessageType = 3
	MessageType_MESSAGE_TYPE_UNREGISTER_RESPONSE MessageType = 4
	// 发现请求/响应
	MessageType_MESSAGE_TYPE_DISCOVER          MessageType = 5
	MessageType_MESSAGE_TYPE_DISCOVER_RESPONSE MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_REGISTER",
		2: "MESSAGE_TYPE_REGISTER_RESPONSE",
		3: "MESSAGE_TYPE_UNREGISTER",
		4: "MESSAGE_TYPE_UNREGISTER_RESPONSE",
		5: "MESSAGE_TYPE_DISCOVER",
		6: "MESSAGE_TYPE_DISCOVER_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":         0,
		"MESSAGE_TYPE_REGISTER":            1,
		"MESSAGE_TYPE_REGISTER_RESPONSE":   2,
		"MESSAGE_TYPE_UNREGISTER":          3,
		"MESSAGE_TYPE_UNREGISTER_RESPONSE": 4,
		"MESSAGE_TYPE_DISCOVER":            5,
		"MESSAGE_TYPE_DISCOVER_RESPONSE":   6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_rendezvous_rendezvous_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_proto_rendezvous_rendezvous_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0}
}

// ResponseStatus 响应状态
type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED         ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_OK                  ResponseStatus = 1
	ResponseStatus_RESPONSE_STATUS_E_INVALID_NAMESPACE ResponseStatus = 100
	ResponseStatus_RESPONSE_STATUS_E_INVALID_TTL       ResponseStatus = 101
	ResponseStatus_RESPONSE_STATUS_E_INVALID_COOKIE    ResponseStatus = 102
	ResponseStatus_RESPONSE_STATUS_E_NOT_AUTHORIZED    ResponseStatus = 103
	ResponseStatus_RESPONSE_STATUS_E_INTERNAL_ERROR    ResponseStatus = 200
	ResponseStatus_RESPONSE_STATUS_E_UNAVAILABLE       ResponseStatus = 201
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0:   "RESPONSE_STATUS_UNSPECIFIED",
		1:   "RESPONSE_STATUS_OK",
		100: "RESPONSE_STATUS_E_INVALID_NAMESPACE",
		101: "RESPONSE_STATUS_E_INVALID_TTL",
		102: "RESPONSE_STATUS_E_INVALID_COOKIE",
		103: "RESPONSE_STATUS_E_NOT_AUTHORIZED",
		200: "RESPONSE_STATUS_E_INTERNAL_ERROR",
		201: "RESPONSE_STATUS_E_UNAVAILABLE",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED":         0,
		"RESPONSE_STATUS_OK":                  1,
		"RESPONSE_STATUS_E_INVALID_NAMESPACE": 100,
		"RESPONSE_STATUS_E_INVALID_TTL":       101,
		"RESPONSE_STATUS_E_INVALID_COOKIE":    102,
		"RESPONSE_STATUS_E_NOT_AUTHORIZED":    103,
		"RESPONSE_STATUS_E_INTERNAL_ERROR":    200,
		"RESPONSE_STATUS_E_UNAVAILABLE":       201,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_rendezvous_rendezvous_proto_enumTypes[1].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_rendezvous_rendezvous_proto_enumTypes[1]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{1}
}

// Message Rendezvous 协议消息
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 消息类型
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.rendezvous.MessageType" json:"type,omitempty"`
	// 请求消息（根据类型选择其一）
	Register   *Register   `protobuf:"bytes,2,opt,name=register,proto3" json:"register,omitempty"`
	Unregister *Unregister `protobuf:"bytes,3,opt,name=unregister,proto3" json:"unregister,omitempty"`
	Discover   *Discover   `protobuf:"bytes,4,opt,name=discover,proto3" json:"discover,omitempty"`
	// 响应消息（根据类型选择其一）
	RegisterResponse *RegisterResponse `protobuf:"bytes,5,opt,name=register_response,json=registerResponse,proto3" json:"register_response,omitempty"`
	DiscoverResponse *DiscoverResponse `protobuf:"bytes,6,opt,name=discover_response,json=discoverResponse,proto3" json:"discover_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetRegister() *Register {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *Message) GetUnregister() *Unregister {
	if x != nil {
		return x.Unregister
	}
	return nil
}

func (x *Message) GetDiscover() *Discover {
	if x != nil {
		return x.Discover
	}
	return nil
}

func (x *Message) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		return x.RegisterResponse
	}
	return nil
}

func (x *Message) GetDiscoverResponse() *DiscoverResponse {
	if x != nil {
		return x.DiscoverResponse
	}
	return nil
}

// Register 注册请求
type Register struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace 命名空间
	// 格式示例:
	//   - "blockchain/mainnet/peers"
	//   - "<realm_id>/topic/<name>"
	//   - "service/<service_type>"
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// peer_id 注册节点ID (32字节)
	PeerId []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// addrs 节点地址列表 (multiaddr 格式)
	Addrs []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// ttl 注册有效期 (秒)
	// 0 表示使用服务端默认值
	Ttl uint64 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// signed_record 可选的签名记录
	// 用于验证注册者身份
	SignedRecord  []byte `protobuf:"bytes,5,opt,name=signed_record,json=signedRecord,proto3" json:"signed_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{1}
}

func (x *Register) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Register) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *Register) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Register) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Register) GetSignedRecord() []byte {
	if x != nil {
		return x.SignedRecord
	}
	return nil
}

// RegisterResponse 注册响应
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 响应状态
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.rendezvous.ResponseStatus" json:"status,omitempty"`
	// status_text 状态说明文本
	StatusText string `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	// ttl 实际使用的 TTL (秒)
	// 服务端可能会调整客户端请求的 TTL
	Ttl           uint64 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *RegisterResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *RegisterResponse) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// Unregister 取消注册请求
type Unregister struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace 命名空间
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// peer_id 节点ID
	PeerId        []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unregister) Reset() {
	*x = Unregister{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unregister) ProtoMessage() {}

func (x *Unregister) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unregister.ProtoReflect.Descriptor instead.
func (*Unregister) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{3}
}

func (x *Unregister) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Unregister) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// Discover 发现请求
type Discover struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace 命名空间
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// limit 最大返回数量
	// 0 表示使用服务端默认值
	Limit uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// cookie 分页 cookie
	// 用于获取下一页结果，首次请求为空
	Cookie        []byte `protobuf:"bytes,3,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discover) Reset() {
	*x = Discover{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discover) ProtoMessage() {}

func (x *Discover) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discover.ProtoReflect.Descriptor instead.
func (*Discover) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{4}
}

func (x *Discover) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Discover) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Discover) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

// DiscoverResponse 发现响应
type DiscoverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 响应状态
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.rendezvous.ResponseStatus" json:"status,omitempty"`
	// status_text 状态说明文本
	StatusText string `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	// registrations 注册列表
	Registrations []*Registration `protobuf:"bytes,3,rep,name=registrations,proto3" json:"registrations,omitempty"`
	// cookie 下一页 cookie
	// 为空表示没有更多结果
	Cookie        []byte `protobuf:"bytes,4,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *DiscoverResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *DiscoverResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

func (x *DiscoverResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

// Registration 注册记录
type Registration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace 命名空间
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// peer_id 节点ID
	PeerId []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// addrs 节点地址列表
	Addrs []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// ttl 剩余有效期 (秒)
	Ttl uint64 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// registered_at 注册时间
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// signed_record 可选的签名记录
	SignedRecord  []byte `protobuf:"bytes,6,opt,name=signed_record,json=signedRecord,proto3" json:"signed_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rendezvous_rendezvous_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP(), []int{6}
}

func (x *Registration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Registration) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *Registration) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Registration) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Registration) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Registration) GetSignedRecord() []byte {
	if x != nil {
		return x.SignedRecord
	}
	return nil
}

var File_pkg_proto_rendezvous_rendezvous_proto protoreflect.FileDescriptor

const file_pkg_proto_rendezvous_rendezvous_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/rendezvous/rendezvous.proto\x12\x10dep2p.rendezvous\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\aMessage\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.dep2p.rendezvous.MessageTypeR\x04type\x126\n" +
	"\bregister\x18\x02 \x01(\v2\x1a.dep2p.rendezvous.RegisterR\bregister\x12<\n" +
	"\n" +
	"unregister\x18\x03 \x01(\v2\x1c.dep2p.rendezvous.UnregisterR\n" +
	"unregister\x126\n" +
	"\bdiscover\x18\x04 \x01(\v2\x1a.dep2p.rendezvous.DiscoverR\bdiscover\x12O\n" +
	"\x11register_response\x18\x05 \x01(\v2\".dep2p.rendezvous.RegisterResponseR\x10registerResponse\x12O\n" +
	"\x11discover_response\x18\x06 \x01(\v2\".dep2p.rendezvous.DiscoverResponseR\x10discoverResponse\"\x8e\x01\n" +
	"\bRegister\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x04R\x03ttl\x12#\n" +
	"\rsigned_record\x18\x05 \x01(\fR\fsignedRecord\"\x7f\n" +
	"\x10RegisterResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .dep2p.rendezvous.ResponseStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\"C\n" +
	"\n" +
	"Unregister\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\"V\n" +
	"\bDiscover\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06cookie\x18\x03 \x01(\fR\x06cookie\"\xcb\x01\n" +
	"\x10DiscoverResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .dep2p.rendezvous.ResponseStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12D\n" +
	"\rregistrations\x18\x03 \x03(\v2\x1e.dep2p.rendezvous.RegistrationR\rregistrations\x12\x16\n" +
	"\x06cookie\x18\x04 \x01(\fR\x06cookie\"\xd3\x01\n" +
	"\fRegistration\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x04R\x03ttl\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12#\n" +
	"\rsigned_record\x18\x06 \x01(\fR\fsignedRecord*\xec\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MESSAGE_TYPE_REGISTER\x10\x01\x12\"\n" +
	"\x1eMESSAGE_TYPE_REGISTER_RESPONSE\x10\x02\x12\x1b\n" +
	"\x17MESSAGE_TYPE_UNREGISTER\x10\x03\x12$\n" +
	" MESSAGE_TYPE_UNREGISTER_RESPONSE\x10\x04\x12\x19\n" +
	"\x15MESSAGE_TYPE_DISCOVER\x10\x05\x12\"\n" +
	"\x1eMESSAGE_TYPE_DISCOVER_RESPONSE\x10\x06*\xac\x02\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESPONSE_STATUS_OK\x10\x01\x12'\n" +
	"#RESPONSE_STATUS_E_INVALID_NAMESPACE\x10d\x12!\n" +
	"\x1dRESPONSE_STATUS_E_INVALID_TTL\x10e\x12$\n" +
	" RESPONSE_STATUS_E_INVALID_COOKIE\x10f\x12$\n" +
	" RESPONSE_STATUS_E_NOT_AUTHORIZED\x10g\x12%\n" +
	" RESPONSE_STATUS_E_INTERNAL_ERROR\x10\xc8\x01\x12\"\n" +
	"\x1dRESPONSE_STATUS_E_UNAVAILABLE\x10\xc9\x01B0Z.github.com/dep2p/go-dep2p/pkg/proto/rendezvousb\x06proto3"

var (
	file_pkg_proto_rendezvous_rendezvous_proto_rawDescOnce sync.Once
	file_pkg_proto_rendezvous_rendezvous_proto_rawDescData []byte
)

func file_pkg_proto_rendezvous_rendezvous_proto_rawDescGZIP() []byte {
	file_pkg_proto_rendezvous_rendezvous_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rendezvous_rendezvous_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rendezvous_rendezvous_proto_rawDesc), len(file_pkg_proto_rendezvous_rendezvous_proto_rawDesc)))
	})
	return file_pkg_proto_rendezvous_rendezvous_proto_rawDescData
}

var file_pkg_proto_rendezvous_rendezvous_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_rendezvous_rendezvous_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_rendezvous_rendezvous_proto_goTypes = []any{
	(MessageType)(0),              // 0: dep2p.rendezvous.MessageType
	(ResponseStatus)(0),           // 1: dep2p.rendezvous.ResponseStatus
	(*Message)(nil),               // 2: dep2p.rendezvous.Message
	(*Register)(nil),              // 3: dep2p.rendezvous.Register
	(*RegisterResponse)(nil),      // 4: dep2p.rendezvous.RegisterResponse
	(*Unregister)(nil),            // 5: dep2p.rendezvous.Unregister
	(*Discover)(nil),              // 6: dep2p.rendezvous.Discover
	(*DiscoverResponse)(nil),      // 7: dep2p.rendezvous.DiscoverResponse
	(*Registration)(nil),          // 8: dep2p.rendezvous.Registration
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_proto_rendezvous_rendezvous_proto_depIdxs = []int32{
	0,  // 0: dep2p.rendezvous.Message.type:type_name -> dep2p.rendezvous.MessageType
	3,  // 1: dep2p.rendezvous.Message.register:type_name -> dep2p.rendezvous.Register
	5,  // 2: dep2p.rendezvous.Message.unregister:type_name -> dep2p.rendezvous.Unregister
	6,  // 3: dep2p.rendezvous.Message.discover:type_name -> dep2p.rendezvous.Discover
	4,  // 4: dep2p.rendezvous.Message.register_response:type_name -> dep2p.rendezvous.RegisterResponse
	7,  // 5: dep2p.rendezvous.Message.discover_response:type_name -> dep2p.rendezvous.DiscoverResponse
	1,  // 6: dep2p.rendezvous.RegisterResponse.status:type_name -> dep2p.rendezvous.ResponseStatus
	1,  // 7: dep2p.rendezvous.DiscoverResponse.status:type_name -> dep2p.rendezvous.ResponseStatus
	8,  // 8: dep2p.rendezvous.DiscoverResponse.registrations:type_name -> dep2p.rendezvous.Registration
	9,  // 9: dep2p.rendezvous.Registration.registered_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_proto_rendezvous_rendezvous_proto_init() }
func file_pkg_proto_rendezvous_rendezvous_proto_init() {
	if File_pkg_proto_rendezvous_rendezvous_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rendezvous_rendezvous_proto_rawDesc), len(file_pkg_proto_rendezvous_rendezvous_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_rendezvous_rendezvous_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rendezvous_rendezvous_proto_depIdxs,
		EnumInfos:         file_pkg_proto_rendezvous_rendezvous_proto_enumTypes,
		MessageInfos:      file_pkg_proto_rendezvous_rendezvous_proto_msgTypes,
	}.Build()
	File_pkg_proto_rendezvous_rendezvous_proto = out.File
	file_pkg_proto_rendezvous_rendezvous_proto_goTypes = nil
	file_pkg_proto_rendezvous_rendezvous_proto_depIdxs = nil
}
