// DeP2P Key Protocol Definitions
// 密钥相关消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: key/key.proto

package key

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyType 密钥类型
type KeyType int32

const (
	KeyType_KEY_TYPE_UNSPECIFIED KeyType = 0
	KeyType_RSA                  KeyType = 1
	KeyType_Ed25519              KeyType = 2
	KeyType_Secp256k1            KeyType = 3
	KeyType_ECDSA                KeyType = 4
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEY_TYPE_UNSPECIFIED",
		1: "RSA",
		2: "Ed25519",
		3: "Secp256k1",
		4: "ECDSA",
	}
	KeyType_value = map[string]int32{
		"KEY_TYPE_UNSPECIFIED": 0,
		"RSA":                  1,
		"Ed25519":              2,
		"Secp256k1":            3,
		"ECDSA":                4,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_key_key_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_key_key_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_key_key_proto_rawDescGZIP(), []int{0}
}

// PublicKey 公钥
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KeyType                `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.key.KeyType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_key_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_key_key_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PublicKey) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PrivateKey 私钥
type PrivateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KeyType                `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.key.KeyType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	mi := &file_key_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_key_key_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateKey) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PrivateKey) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// KeyPair 密钥对
type KeyPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     *PublicKey             `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    *PrivateKey            `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPair) Reset() {
	*x = KeyPair{}
	mi := &file_key_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair) ProtoMessage() {}

func (x *KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_key_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair.ProtoReflect.Descriptor instead.
func (*KeyPair) Descriptor() ([]byte, []int) {
	return file_key_key_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPair) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KeyPair) GetPrivateKey() *PrivateKey {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

// Signature 签名
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KeyType                `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.key.KeyType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_key_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_key_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_key_key_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *Signature) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_key_key_proto protoreflect.FileDescriptor

const file_key_key_proto_rawDesc = "" +
	"\n" +
	"\rkey/key.proto\x12\tdep2p.key\"G\n" +
	"\tPublicKey\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.dep2p.key.KeyTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"H\n" +
	"\n" +
	"PrivateKey\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.dep2p.key.KeyTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"v\n" +
	"\aKeyPair\x123\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2\x14.dep2p.key.PublicKeyR\tpublicKey\x126\n" +
	"\vprivate_key\x18\x02 \x01(\v2\x15.dep2p.key.PrivateKeyR\n" +
	"privateKey\"G\n" +
	"\tSignature\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.dep2p.key.KeyTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*S\n" +
	"\aKeyType\x12\x18\n" +
	"\x14KEY_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RSA\x10\x01\x12\v\n" +
	"\aEd25519\x10\x02\x12\r\n" +
	"\tSecp256k1\x10\x03\x12\t\n" +
	"\x05ECDSA\x10\x04B&Z$github.com/dep2p/dep2p/pkg/proto/keyb\x06proto3"

var (
	file_key_key_proto_rawDescOnce sync.Once
	file_key_key_proto_rawDescData []byte
)

func file_key_key_proto_rawDescGZIP() []byte {
	file_key_key_proto_rawDescOnce.Do(func() {
		file_key_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_key_proto_rawDesc), len(file_key_key_proto_rawDesc)))
	})
	return file_key_key_proto_rawDescData
}

var file_key_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_key_key_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_key_key_proto_goTypes = []any{
	(KeyType)(0),       // 0: dep2p.key.KeyType
	(*PublicKey)(nil),  // 1: dep2p.key.PublicKey
	(*PrivateKey)(nil), // 2: dep2p.key.PrivateKey
	(*KeyPair)(nil),    // 3: dep2p.key.KeyPair
	(*Signature)(nil),  // 4: dep2p.key.Signature
}
var file_key_key_proto_depIdxs = []int32{
	0, // 0: dep2p.key.PublicKey.type:type_name -> dep2p.key.KeyType
	0, // 1: dep2p.key.PrivateKey.type:type_name -> dep2p.key.KeyType
	1, // 2: dep2p.key.KeyPair.public_key:type_name -> dep2p.key.PublicKey
	2, // 3: dep2p.key.KeyPair.private_key:type_name -> dep2p.key.PrivateKey
	0, // 4: dep2p.key.Signature.type:type_name -> dep2p.key.KeyType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_key_key_proto_init() }
func file_key_key_proto_init() {
	if File_key_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_key_proto_rawDesc), len(file_key_key_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_key_key_proto_goTypes,
		DependencyIndexes: file_key_key_proto_depIdxs,
		EnumInfos:         file_key_key_proto_enumTypes,
		MessageInfos:      file_key_key_proto_msgTypes,
	}.Build()
	File_key_key_proto = out.File
	file_key_key_proto_goTypes = nil
	file_key_key_proto_depIdxs = nil
}
