// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/member/member.proto

package memberpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemberInfo 成员信息
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RealmId       string                 `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,7,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BytesSent     int64                  `protobuf:"varint,9,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived int64                  `protobuf:"varint,10,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	MessagesSent  int64                  `protobuf:"varint,11,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *MemberInfo) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *MemberInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MemberInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *MemberInfo) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *MemberInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *MemberInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *MemberInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MemberInfo) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *MemberInfo) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *MemberInfo) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

// MemberList 成员列表
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Members       []*MemberInfo          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberList) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *MemberList) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// MemberListRequest 成员列表请求
type MemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListRequest) Reset() {
	*x = MemberListRequest{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListRequest) ProtoMessage() {}

func (x *MemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListRequest.ProtoReflect.Descriptor instead.
func (*MemberListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{2}
}

func (x *MemberListRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

// MemberListResponse 成员列表响应
type MemberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *MemberList            `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListResponse) Reset() {
	*x = MemberListResponse{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListResponse) ProtoMessage() {}

func (x *MemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListResponse.ProtoReflect.Descriptor instead.
func (*MemberListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{3}
}

func (x *MemberListResponse) GetList() *MemberList {
	if x != nil {
		return x.List
	}
	return nil
}

// MemberDeltaRequest 增量同步请求
type MemberDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	SinceVersion  uint64                 `protobuf:"varint,2,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDeltaRequest) Reset() {
	*x = MemberDeltaRequest{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDeltaRequest) ProtoMessage() {}

func (x *MemberDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDeltaRequest.ProtoReflect.Descriptor instead.
func (*MemberDeltaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{4}
}

func (x *MemberDeltaRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *MemberDeltaRequest) GetSinceVersion() uint64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

// MemberDeltaResponse 增量同步响应
type MemberDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         []*MemberInfo          `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed       [][]byte               `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"` // peer_ids
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDeltaResponse) Reset() {
	*x = MemberDeltaResponse{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDeltaResponse) ProtoMessage() {}

func (x *MemberDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDeltaResponse.ProtoReflect.Descriptor instead.
func (*MemberDeltaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{5}
}

func (x *MemberDeltaResponse) GetAdded() []*MemberInfo {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *MemberDeltaResponse) GetRemoved() [][]byte {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *MemberDeltaResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// HeartbeatRequest 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_member_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_lib_proto_realm_member_member_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_member_member_proto_rawDesc = "" +
	"\n" +
	"'pkg/lib/proto/realm/member/member.proto\x12\frealm.member\"\xa8\x03\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x14\n" +
	"\x05addrs\x18\a \x03(\fR\x05addrs\x12B\n" +
	"\bmetadata\x18\b \x03(\v2&.realm.member.MemberInfo.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\t \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\n" +
	" \x01(\x03R\rbytesReceived\x12#\n" +
	"\rmessages_sent\x18\v \x01(\x03R\fmessagesSent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\n" +
	"MemberList\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x122\n" +
	"\amembers\x18\x02 \x03(\v2\x18.realm.member.MemberInfoR\amembers\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\".\n" +
	"\x11MemberListRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\"B\n" +
	"\x12MemberListResponse\x12,\n" +
	"\x04list\x18\x01 \x01(\v2\x18.realm.member.MemberListR\x04list\"T\n" +
	"\x12MemberDeltaRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12#\n" +
	"\rsince_version\x18\x02 \x01(\x04R\fsinceVersion\"y\n" +
	"\x13MemberDeltaResponse\x12.\n" +
	"\x05added\x18\x01 \x03(\v2\x18.realm.member.MemberInfoR\x05added\x12\x18\n" +
	"\aremoved\x18\x02 \x03(\fR\aremoved\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"C\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB?Z=github.com/dep2p/go-dep2p/pkg/lib/proto/realm/member;memberpbb\x06proto3"

var (
	file_pkg_lib_proto_realm_member_member_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_member_member_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_member_member_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_member_member_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_member_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_member_member_proto_rawDesc), len(file_pkg_lib_proto_realm_member_member_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_member_member_proto_rawDescData
}

var file_pkg_lib_proto_realm_member_member_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_lib_proto_realm_member_member_proto_goTypes = []any{
	(*MemberInfo)(nil),          // 0: realm.member.MemberInfo
	(*MemberList)(nil),          // 1: realm.member.MemberList
	(*MemberListRequest)(nil),   // 2: realm.member.MemberListRequest
	(*MemberListResponse)(nil),  // 3: realm.member.MemberListResponse
	(*MemberDeltaRequest)(nil),  // 4: realm.member.MemberDeltaRequest
	(*MemberDeltaResponse)(nil), // 5: realm.member.MemberDeltaResponse
	(*HeartbeatRequest)(nil),    // 6: realm.member.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 7: realm.member.HeartbeatResponse
	nil,                         // 8: realm.member.MemberInfo.MetadataEntry
}
var file_pkg_lib_proto_realm_member_member_proto_depIdxs = []int32{
	8, // 0: realm.member.MemberInfo.metadata:type_name -> realm.member.MemberInfo.MetadataEntry
	0, // 1: realm.member.MemberList.members:type_name -> realm.member.MemberInfo
	1, // 2: realm.member.MemberListResponse.list:type_name -> realm.member.MemberList
	0, // 3: realm.member.MemberDeltaResponse.added:type_name -> realm.member.MemberInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_member_member_proto_init() }
func file_pkg_lib_proto_realm_member_member_proto_init() {
	if File_pkg_lib_proto_realm_member_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_member_member_proto_rawDesc), len(file_pkg_lib_proto_realm_member_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_member_member_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_member_member_proto_depIdxs,
		MessageInfos:      file_pkg_lib_proto_realm_member_member_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_member_member_proto = out.File
	file_pkg_lib_proto_realm_member_member_proto_goTypes = nil
	file_pkg_lib_proto_realm_member_member_proto_depIdxs = nil
}
