// DeP2P DHT Protocol Definitions
// Kademlia DHT 协议消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: dht/dht.proto

package dht

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType DHT 消息类型
type MessageType int32

const (
	MessageType_PUT_VALUE     MessageType = 0 // 存储值
	MessageType_GET_VALUE     MessageType = 1 // 获取值
	MessageType_ADD_PROVIDER  MessageType = 2 // 添加提供者
	MessageType_GET_PROVIDERS MessageType = 3 // 获取提供者
	MessageType_FIND_NODE     MessageType = 4 // 查找节点
	MessageType_PING          MessageType = 5 // Ping
	// v2.0 新增：PeerRecord 操作
	MessageType_PUT_PEER_RECORD MessageType = 6 // 发布 PeerRecord
	MessageType_GET_PEER_RECORD MessageType = 7 // 获取 PeerRecord
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PUT_VALUE",
		1: "GET_VALUE",
		2: "ADD_PROVIDER",
		3: "GET_PROVIDERS",
		4: "FIND_NODE",
		5: "PING",
		6: "PUT_PEER_RECORD",
		7: "GET_PEER_RECORD",
	}
	MessageType_value = map[string]int32{
		"PUT_VALUE":       0,
		"GET_VALUE":       1,
		"ADD_PROVIDER":    2,
		"GET_PROVIDERS":   3,
		"FIND_NODE":       4,
		"PING":            5,
		"PUT_PEER_RECORD": 6,
		"GET_PEER_RECORD": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_dht_dht_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_dht_dht_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_dht_dht_proto_rawDescGZIP(), []int{0}
}

// ConnectionType 连接类型
type ConnectionType int32

const (
	ConnectionType_NOT_CONNECTED  ConnectionType = 0 // 未连接
	ConnectionType_CONNECTED      ConnectionType = 1 // 已连接
	ConnectionType_CAN_CONNECT    ConnectionType = 2 // 可以连接
	ConnectionType_CANNOT_CONNECT ConnectionType = 3 // 无法连接
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "NOT_CONNECTED",
		1: "CONNECTED",
		2: "CAN_CONNECT",
		3: "CANNOT_CONNECT",
	}
	ConnectionType_value = map[string]int32{
		"NOT_CONNECTED":  0,
		"CONNECTED":      1,
		"CAN_CONNECT":    2,
		"CANNOT_CONNECT": 3,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_dht_dht_proto_enumTypes[1].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_dht_dht_proto_enumTypes[1]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_dht_dht_proto_rawDescGZIP(), []int{1}
}

// Peer 节点信息
type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Connection    ConnectionType         `protobuf:"varint,3,opt,name=connection,proto3,enum=dep2p.dht.ConnectionType" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_dht_dht_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_dht_dht_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_dht_dht_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Peer) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Peer) GetConnection() ConnectionType {
	if x != nil {
		return x.Connection
	}
	return ConnectionType_NOT_CONNECTED
}

// Message DHT 协议消息
type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Type        MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.dht.MessageType" json:"type,omitempty"`
	Key         []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                     // 键（用于 PUT/GET）
	Value       []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                 // 值（用于 PUT）
	CloserPeers int32                  `protobuf:"varint,8,opt,name=closer_peers,json=closerPeers,proto3" json:"closer_peers,omitempty"` // 更接近的节点数量
	Providers   []*Peer                `protobuf:"bytes,9,rep,name=providers,proto3" json:"providers,omitempty"`                         // 提供者列表
	Closer      []*Peer                `protobuf:"bytes,10,rep,name=closer,proto3" json:"closer,omitempty"`                              // 更接近的节点列表
	// v2.0 新增：PeerRecord 字段
	SignedPeerRecord []byte `protobuf:"bytes,11,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"` // 签名的 PeerRecord（序列化字节）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_dht_dht_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_dht_dht_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_dht_dht_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PUT_VALUE
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetCloserPeers() int32 {
	if x != nil {
		return x.CloserPeers
	}
	return 0
}

func (x *Message) GetProviders() []*Peer {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *Message) GetCloser() []*Peer {
	if x != nil {
		return x.Closer
	}
	return nil
}

func (x *Message) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

// Record DHT 记录
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Author        []byte                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	TimeReceived  uint64                 `protobuf:"varint,5,opt,name=time_received,json=timeReceived,proto3" json:"time_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_dht_dht_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_dht_dht_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_dht_dht_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Record) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Record) GetTimeReceived() uint64 {
	if x != nil {
		return x.TimeReceived
	}
	return 0
}

var File_dht_dht_proto protoreflect.FileDescriptor

const file_dht_dht_proto_rawDesc = "" +
	"\n" +
	"\rdht/dht.proto\x12\tdep2p.dht\"g\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x129\n" +
	"\n" +
	"connection\x18\x03 \x01(\x0e2\x19.dep2p.dht.ConnectionTypeR\n" +
	"connection\"\x86\x02\n" +
	"\aMessage\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.dep2p.dht.MessageTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12!\n" +
	"\fcloser_peers\x18\b \x01(\x05R\vcloserPeers\x12-\n" +
	"\tproviders\x18\t \x03(\v2\x0f.dep2p.dht.PeerR\tproviders\x12'\n" +
	"\x06closer\x18\n" +
	" \x03(\v2\x0f.dep2p.dht.PeerR\x06closer\x12,\n" +
	"\x12signed_peer_record\x18\v \x01(\fR\x10signedPeerRecord\"\x8b\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06author\x18\x03 \x01(\fR\x06author\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12#\n" +
	"\rtime_received\x18\x05 \x01(\x04R\ftimeReceived*\x93\x01\n" +
	"\vMessageType\x12\r\n" +
	"\tPUT_VALUE\x10\x00\x12\r\n" +
	"\tGET_VALUE\x10\x01\x12\x10\n" +
	"\fADD_PROVIDER\x10\x02\x12\x11\n" +
	"\rGET_PROVIDERS\x10\x03\x12\r\n" +
	"\tFIND_NODE\x10\x04\x12\b\n" +
	"\x04PING\x10\x05\x12\x13\n" +
	"\x0fPUT_PEER_RECORD\x10\x06\x12\x13\n" +
	"\x0fGET_PEER_RECORD\x10\a*W\n" +
	"\x0eConnectionType\x12\x11\n" +
	"\rNOT_CONNECTED\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x0f\n" +
	"\vCAN_CONNECT\x10\x02\x12\x12\n" +
	"\x0eCANNOT_CONNECT\x10\x03B&Z$github.com/dep2p/dep2p/pkg/proto/dhtb\x06proto3"

var (
	file_dht_dht_proto_rawDescOnce sync.Once
	file_dht_dht_proto_rawDescData []byte
)

func file_dht_dht_proto_rawDescGZIP() []byte {
	file_dht_dht_proto_rawDescOnce.Do(func() {
		file_dht_dht_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dht_dht_proto_rawDesc), len(file_dht_dht_proto_rawDesc)))
	})
	return file_dht_dht_proto_rawDescData
}

var file_dht_dht_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dht_dht_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dht_dht_proto_goTypes = []any{
	(MessageType)(0),    // 0: dep2p.dht.MessageType
	(ConnectionType)(0), // 1: dep2p.dht.ConnectionType
	(*Peer)(nil),        // 2: dep2p.dht.Peer
	(*Message)(nil),     // 3: dep2p.dht.Message
	(*Record)(nil),      // 4: dep2p.dht.Record
}
var file_dht_dht_proto_depIdxs = []int32{
	1, // 0: dep2p.dht.Peer.connection:type_name -> dep2p.dht.ConnectionType
	0, // 1: dep2p.dht.Message.type:type_name -> dep2p.dht.MessageType
	2, // 2: dep2p.dht.Message.providers:type_name -> dep2p.dht.Peer
	2, // 3: dep2p.dht.Message.closer:type_name -> dep2p.dht.Peer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dht_dht_proto_init() }
func file_dht_dht_proto_init() {
	if File_dht_dht_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dht_dht_proto_rawDesc), len(file_dht_dht_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dht_dht_proto_goTypes,
		DependencyIndexes: file_dht_dht_proto_depIdxs,
		EnumInfos:         file_dht_dht_proto_enumTypes,
		MessageInfos:      file_dht_dht_proto_msgTypes,
	}.Build()
	File_dht_dht_proto = out.File
	file_dht_dht_proto_goTypes = nil
	file_dht_dht_proto_depIdxs = nil
}
