// DeP2P Realm Protocol Definitions
// Realm 认证协议消息定义
//
// Protocol: /dep2p/realm/<realmID>/auth/1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: realm/realm.proto

package realm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthResponse_Status int32

const (
	AuthResponse_OK               AuthResponse_Status = 0   // 认证成功
	AuthResponse_E_INVALID_REALM  AuthResponse_Status = 100 // 无效的 Realm
	AuthResponse_E_INVALID_PEER   AuthResponse_Status = 101 // 无效的节点
	AuthResponse_E_AUTH_FAILED    AuthResponse_Status = 102 // 认证失败
	AuthResponse_E_EXPIRED        AuthResponse_Status = 103 // 请求过期
	AuthResponse_E_REPLAY_ATTACK  AuthResponse_Status = 104 // 重放攻击
	AuthResponse_E_INTERNAL_ERROR AuthResponse_Status = 200 // 内部错误
)

// Enum value maps for AuthResponse_Status.
var (
	AuthResponse_Status_name = map[int32]string{
		0:   "OK",
		100: "E_INVALID_REALM",
		101: "E_INVALID_PEER",
		102: "E_AUTH_FAILED",
		103: "E_EXPIRED",
		104: "E_REPLAY_ATTACK",
		200: "E_INTERNAL_ERROR",
	}
	AuthResponse_Status_value = map[string]int32{
		"OK":               0,
		"E_INVALID_REALM":  100,
		"E_INVALID_PEER":   101,
		"E_AUTH_FAILED":    102,
		"E_EXPIRED":        103,
		"E_REPLAY_ATTACK":  104,
		"E_INTERNAL_ERROR": 200,
	}
)

func (x AuthResponse_Status) Enum() *AuthResponse_Status {
	p := new(AuthResponse_Status)
	*p = x
	return p
}

func (x AuthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_realm_realm_proto_enumTypes[0].Descriptor()
}

func (AuthResponse_Status) Type() protoreflect.EnumType {
	return &file_realm_realm_proto_enumTypes[0]
}

func (x AuthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthResponse_Status.Descriptor instead.
func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{1, 0}
}

type JoinResponse_Status int32

const (
	JoinResponse_OK            JoinResponse_Status = 0
	JoinResponse_E_INVALID_PSK JoinResponse_Status = 100
	JoinResponse_E_REALM_FULL  JoinResponse_Status = 101
	JoinResponse_E_REJECTED    JoinResponse_Status = 102
)

// Enum value maps for JoinResponse_Status.
var (
	JoinResponse_Status_name = map[int32]string{
		0:   "OK",
		100: "E_INVALID_PSK",
		101: "E_REALM_FULL",
		102: "E_REJECTED",
	}
	JoinResponse_Status_value = map[string]int32{
		"OK":            0,
		"E_INVALID_PSK": 100,
		"E_REALM_FULL":  101,
		"E_REJECTED":    102,
	}
)

func (x JoinResponse_Status) Enum() *JoinResponse_Status {
	p := new(JoinResponse_Status)
	*p = x
	return p
}

func (x JoinResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_realm_realm_proto_enumTypes[1].Descriptor()
}

func (JoinResponse_Status) Type() protoreflect.EnumType {
	return &file_realm_realm_proto_enumTypes[1]
}

func (x JoinResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinResponse_Status.Descriptor instead.
func (JoinResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{3, 0}
}

// AuthRequest Realm 认证请求
type AuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// realm_id Realm ID
	RealmId []byte `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// peer_id 请求者节点 ID
	PeerId []byte `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// challenge_response 质询响应（PSK 派生的签名）
	ChallengeResponse []byte `protobuf:"bytes,3,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"`
	// timestamp 请求时间戳
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// nonce 随机数（防重放）
	Nonce         []byte `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_realm_realm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *AuthRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *AuthRequest) GetChallengeResponse() []byte {
	if x != nil {
		return x.ChallengeResponse
	}
	return nil
}

func (x *AuthRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// AuthResponse Realm 认证响应
type AuthResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Status     AuthResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.realm.AuthResponse_Status" json:"status,omitempty"`
	StatusText string                 `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	// member_token 成员令牌（认证成功时）
	MemberToken []byte `protobuf:"bytes,3,opt,name=member_token,json=memberToken,proto3" json:"member_token,omitempty"`
	// expiration 令牌过期时间
	Expiration    uint64 `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_realm_realm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetStatus() AuthResponse_Status {
	if x != nil {
		return x.Status
	}
	return AuthResponse_OK
}

func (x *AuthResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *AuthResponse) GetMemberToken() []byte {
	if x != nil {
		return x.MemberToken
	}
	return nil
}

func (x *AuthResponse) GetExpiration() uint64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

// JoinRequest 加入 Realm 请求
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       []byte                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	PeerId        []byte                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Psk           []byte                 `protobuf:"bytes,3,opt,name=psk,proto3" json:"psk,omitempty"` // Pre-Shared Key
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_realm_realm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *JoinRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *JoinRequest) GetPsk() []byte {
	if x != nil {
		return x.Psk
	}
	return nil
}

func (x *JoinRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JoinResponse 加入 Realm 响应
type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JoinResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.realm.JoinResponse_Status" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	MemberToken   []byte                 `protobuf:"bytes,3,opt,name=member_token,json=memberToken,proto3" json:"member_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_realm_realm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetStatus() JoinResponse_Status {
	if x != nil {
		return x.Status
	}
	return JoinResponse_OK
}

func (x *JoinResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *JoinResponse) GetMemberToken() []byte {
	if x != nil {
		return x.MemberToken
	}
	return nil
}

// MemberInfo 成员信息
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	JoinedAt      uint64                 `protobuf:"varint,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_realm_realm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{4}
}

func (x *MemberInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *MemberInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *MemberInfo) GetJoinedAt() uint64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *MemberInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MemberList 成员列表
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmId       []byte                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Members       []*MemberInfo          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // 列表版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_realm_realm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_realm_realm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_realm_realm_proto_rawDescGZIP(), []int{5}
}

func (x *MemberList) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *MemberList) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_realm_realm_proto protoreflect.FileDescriptor

const file_realm_realm_proto_rawDesc = "" +
	"\n" +
	"\x11realm/realm.proto\x12\vdep2p.realm\"\xa4\x01\n" +
	"\vAuthRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\fR\arealmId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12-\n" +
	"\x12challenge_response\x18\x03 \x01(\fR\x11challengeResponse\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\"\xb6\x02\n" +
	"\fAuthResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .dep2p.realm.AuthResponse.StatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12!\n" +
	"\fmember_token\x18\x03 \x01(\fR\vmemberToken\x12\x1e\n" +
	"\n" +
	"expiration\x18\x04 \x01(\x04R\n" +
	"expiration\"\x87\x01\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x13\n" +
	"\x0fE_INVALID_REALM\x10d\x12\x12\n" +
	"\x0eE_INVALID_PEER\x10e\x12\x11\n" +
	"\rE_AUTH_FAILED\x10f\x12\r\n" +
	"\tE_EXPIRED\x10g\x12\x13\n" +
	"\x0fE_REPLAY_ATTACK\x10h\x12\x15\n" +
	"\x10E_INTERNAL_ERROR\x10\xc8\x01\"q\n" +
	"\vJoinRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\fR\arealmId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12\x10\n" +
	"\x03psk\x18\x03 \x01(\fR\x03psk\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"\xd3\x01\n" +
	"\fJoinResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .dep2p.realm.JoinResponse.StatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12!\n" +
	"\fmember_token\x18\x03 \x01(\fR\vmemberToken\"E\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\rE_INVALID_PSK\x10d\x12\x10\n" +
	"\fE_REALM_FULL\x10e\x12\x0e\n" +
	"\n" +
	"E_REJECTED\x10f\"\xd8\x01\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\x04R\bjoinedAt\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.dep2p.realm.MemberInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\n" +
	"MemberList\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\fR\arealmId\x121\n" +
	"\amembers\x18\x02 \x03(\v2\x17.dep2p.realm.MemberInfoR\amembers\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversionB(Z&github.com/dep2p/dep2p/pkg/proto/realmb\x06proto3"

var (
	file_realm_realm_proto_rawDescOnce sync.Once
	file_realm_realm_proto_rawDescData []byte
)

func file_realm_realm_proto_rawDescGZIP() []byte {
	file_realm_realm_proto_rawDescOnce.Do(func() {
		file_realm_realm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realm_realm_proto_rawDesc), len(file_realm_realm_proto_rawDesc)))
	})
	return file_realm_realm_proto_rawDescData
}

var file_realm_realm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_realm_realm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_realm_realm_proto_goTypes = []any{
	(AuthResponse_Status)(0), // 0: dep2p.realm.AuthResponse.Status
	(JoinResponse_Status)(0), // 1: dep2p.realm.JoinResponse.Status
	(*AuthRequest)(nil),      // 2: dep2p.realm.AuthRequest
	(*AuthResponse)(nil),     // 3: dep2p.realm.AuthResponse
	(*JoinRequest)(nil),      // 4: dep2p.realm.JoinRequest
	(*JoinResponse)(nil),     // 5: dep2p.realm.JoinResponse
	(*MemberInfo)(nil),       // 6: dep2p.realm.MemberInfo
	(*MemberList)(nil),       // 7: dep2p.realm.MemberList
	nil,                      // 8: dep2p.realm.MemberInfo.MetadataEntry
}
var file_realm_realm_proto_depIdxs = []int32{
	0, // 0: dep2p.realm.AuthResponse.status:type_name -> dep2p.realm.AuthResponse.Status
	1, // 1: dep2p.realm.JoinResponse.status:type_name -> dep2p.realm.JoinResponse.Status
	8, // 2: dep2p.realm.MemberInfo.metadata:type_name -> dep2p.realm.MemberInfo.MetadataEntry
	6, // 3: dep2p.realm.MemberList.members:type_name -> dep2p.realm.MemberInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_realm_realm_proto_init() }
func file_realm_realm_proto_init() {
	if File_realm_realm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realm_realm_proto_rawDesc), len(file_realm_realm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_realm_realm_proto_goTypes,
		DependencyIndexes: file_realm_realm_proto_depIdxs,
		EnumInfos:         file_realm_realm_proto_enumTypes,
		MessageInfos:      file_realm_realm_proto_msgTypes,
	}.Build()
	File_realm_realm_proto = out.File
	file_realm_realm_proto_goTypes = nil
	file_realm_realm_proto_depIdxs = nil
}
