// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/lib/proto/realm/gateway/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelayRequest 中继请求
type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePeerId  []byte                 `protobuf:"bytes,1,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`
	TargetPeerId  []byte                 `protobuf:"bytes,2,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	RealmId       []byte                 `protobuf:"bytes,4,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	AuthProof     []byte                 `protobuf:"bytes,5,opt,name=auth_proof,json=authProof,proto3" json:"auth_proof,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RelayRequest) GetSourcePeerId() []byte {
	if x != nil {
		return x.SourcePeerId
	}
	return nil
}

func (x *RelayRequest) GetTargetPeerId() []byte {
	if x != nil {
		return x.TargetPeerId
	}
	return nil
}

func (x *RelayRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RelayRequest) GetRealmId() []byte {
	if x != nil {
		return x.RealmId
	}
	return nil
}

func (x *RelayRequest) GetAuthProof() []byte {
	if x != nil {
		return x.AuthProof
	}
	return nil
}

func (x *RelayRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// RelayResponse 中继响应
type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RelayNodeId   []byte                 `protobuf:"bytes,3,opt,name=relay_node_id,json=relayNodeId,proto3" json:"relay_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RelayResponse) GetRelayNodeId() []byte {
	if x != nil {
		return x.RelayNodeId
	}
	return nil
}

// GatewayCapacity 网关容量
type GatewayCapacity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections  int32                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	AvailableBandwidth int64                  `protobuf:"varint,2,opt,name=available_bandwidth,json=availableBandwidth,proto3" json:"available_bandwidth,omitempty"`
	CpuUsage           float64                `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	ReachablePeers     []string               `protobuf:"bytes,4,rep,name=reachable_peers,json=reachablePeers,proto3" json:"reachable_peers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GatewayCapacity) Reset() {
	*x = GatewayCapacity{}
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCapacity) ProtoMessage() {}

func (x *GatewayCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCapacity.ProtoReflect.Descriptor instead.
func (*GatewayCapacity) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayCapacity) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GatewayCapacity) GetAvailableBandwidth() int64 {
	if x != nil {
		return x.AvailableBandwidth
	}
	return 0
}

func (x *GatewayCapacity) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GatewayCapacity) GetReachablePeers() []string {
	if x != nil {
		return x.ReachablePeers
	}
	return nil
}

// RelayStats 中继统计
type RelayStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesSent     int64                  `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived int64                  `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	HopCount      int32                  `protobuf:"varint,4,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStats) Reset() {
	*x = RelayStats{}
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStats) ProtoMessage() {}

func (x *RelayStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStats.ProtoReflect.Descriptor instead.
func (*RelayStats) Descriptor() ([]byte, []int) {
	return file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RelayStats) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *RelayStats) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *RelayStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RelayStats) GetHopCount() int32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

var File_pkg_lib_proto_realm_gateway_gateway_proto protoreflect.FileDescriptor

const file_pkg_lib_proto_realm_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	")pkg/lib/proto/realm/gateway/gateway.proto\x12\rrealm.gateway\"\xc4\x01\n" +
	"\fRelayRequest\x12$\n" +
	"\x0esource_peer_id\x18\x01 \x01(\fR\fsourcePeerId\x12$\n" +
	"\x0etarget_peer_id\x18\x02 \x01(\fR\ftargetPeerId\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x19\n" +
	"\brealm_id\x18\x04 \x01(\fR\arealmId\x12\x1d\n" +
	"\n" +
	"auth_proof\x18\x05 \x01(\fR\tauthProof\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"c\n" +
	"\rRelayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\"\n" +
	"\rrelay_node_id\x18\x03 \x01(\fR\vrelayNodeId\"\xb7\x01\n" +
	"\x0fGatewayCapacity\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x05R\x11activeConnections\x12/\n" +
	"\x13available_bandwidth\x18\x02 \x01(\x03R\x12availableBandwidth\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12'\n" +
	"\x0freachable_peers\x18\x04 \x03(\tR\x0ereachablePeers\"\x90\x01\n" +
	"\n" +
	"RelayStats\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x03R\rbytesReceived\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\thop_count\x18\x04 \x01(\x05R\bhopCountBAZ?github.com/dep2p/go-dep2p/pkg/lib/proto/realm/gateway;gatewaypbb\x06proto3"

var (
	file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescOnce sync.Once
	file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescData []byte
)

func file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescGZIP() []byte {
	file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_gateway_gateway_proto_rawDesc), len(file_pkg_lib_proto_realm_gateway_gateway_proto_rawDesc)))
	})
	return file_pkg_lib_proto_realm_gateway_gateway_proto_rawDescData
}

var file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_lib_proto_realm_gateway_gateway_proto_goTypes = []any{
	(*RelayRequest)(nil),    // 0: realm.gateway.RelayRequest
	(*RelayResponse)(nil),   // 1: realm.gateway.RelayResponse
	(*GatewayCapacity)(nil), // 2: realm.gateway.GatewayCapacity
	(*RelayStats)(nil),      // 3: realm.gateway.RelayStats
}
var file_pkg_lib_proto_realm_gateway_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_lib_proto_realm_gateway_gateway_proto_init() }
func file_pkg_lib_proto_realm_gateway_gateway_proto_init() {
	if File_pkg_lib_proto_realm_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_lib_proto_realm_gateway_gateway_proto_rawDesc), len(file_pkg_lib_proto_realm_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_lib_proto_realm_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_lib_proto_realm_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_pkg_lib_proto_realm_gateway_gateway_proto_msgTypes,
	}.Build()
	File_pkg_lib_proto_realm_gateway_gateway_proto = out.File
	file_pkg_lib_proto_realm_gateway_gateway_proto_goTypes = nil
	file_pkg_lib_proto_realm_gateway_gateway_proto_depIdxs = nil
}
