// DeP2P Rendezvous Protocol Definitions
// 命名空间发现协议消息定义
//
// Protocol: /dep2p/sys/rendezvous/1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: rendezvous/rendezvous.proto

package rendezvous

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
type Message_MessageType int32

const (
	Message_REGISTER          Message_MessageType = 0
	Message_REGISTER_RESPONSE Message_MessageType = 1
	Message_UNREGISTER        Message_MessageType = 2
	Message_DISCOVER          Message_MessageType = 3
	Message_DISCOVER_RESPONSE Message_MessageType = 4
)

// Enum value maps for Message_MessageType.
var (
	Message_MessageType_name = map[int32]string{
		0: "REGISTER",
		1: "REGISTER_RESPONSE",
		2: "UNREGISTER",
		3: "DISCOVER",
		4: "DISCOVER_RESPONSE",
	}
	Message_MessageType_value = map[string]int32{
		"REGISTER":          0,
		"REGISTER_RESPONSE": 1,
		"UNREGISTER":        2,
		"DISCOVER":          3,
		"DISCOVER_RESPONSE": 4,
	}
)

func (x Message_MessageType) Enum() *Message_MessageType {
	p := new(Message_MessageType)
	*p = x
	return p
}

func (x Message_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_rendezvous_proto_enumTypes[0].Descriptor()
}

func (Message_MessageType) Type() protoreflect.EnumType {
	return &file_rendezvous_rendezvous_proto_enumTypes[0]
}

func (x Message_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_MessageType.Descriptor instead.
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 0}
}

// ResponseStatus 响应状态
type Message_ResponseStatus int32

const (
	Message_OK                           Message_ResponseStatus = 0
	Message_E_INVALID_NAMESPACE          Message_ResponseStatus = 100
	Message_E_INVALID_SIGNED_PEER_RECORD Message_ResponseStatus = 101
	Message_E_INVALID_TTL                Message_ResponseStatus = 102
	Message_E_INVALID_COOKIE             Message_ResponseStatus = 103
	Message_E_NOT_AUTHORIZED             Message_ResponseStatus = 200
	Message_E_INTERNAL_ERROR             Message_ResponseStatus = 300
	Message_E_UNAVAILABLE                Message_ResponseStatus = 400
)

// Enum value maps for Message_ResponseStatus.
var (
	Message_ResponseStatus_name = map[int32]string{
		0:   "OK",
		100: "E_INVALID_NAMESPACE",
		101: "E_INVALID_SIGNED_PEER_RECORD",
		102: "E_INVALID_TTL",
		103: "E_INVALID_COOKIE",
		200: "E_NOT_AUTHORIZED",
		300: "E_INTERNAL_ERROR",
		400: "E_UNAVAILABLE",
	}
	Message_ResponseStatus_value = map[string]int32{
		"OK":                           0,
		"E_INVALID_NAMESPACE":          100,
		"E_INVALID_SIGNED_PEER_RECORD": 101,
		"E_INVALID_TTL":                102,
		"E_INVALID_COOKIE":             103,
		"E_NOT_AUTHORIZED":             200,
		"E_INTERNAL_ERROR":             300,
		"E_UNAVAILABLE":                400,
	}
)

func (x Message_ResponseStatus) Enum() *Message_ResponseStatus {
	p := new(Message_ResponseStatus)
	*p = x
	return p
}

func (x Message_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rendezvous_rendezvous_proto_enumTypes[1].Descriptor()
}

func (Message_ResponseStatus) Type() protoreflect.EnumType {
	return &file_rendezvous_rendezvous_proto_enumTypes[1]
}

func (x Message_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_ResponseStatus.Descriptor instead.
func (Message_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 1}
}

// Message Rendezvous 消息
type Message struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Type             Message_MessageType       `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.rendezvous.Message_MessageType" json:"type,omitempty"`
	Register         *Message_Register         `protobuf:"bytes,2,opt,name=register,proto3" json:"register,omitempty"`
	RegisterResponse *Message_RegisterResponse `protobuf:"bytes,3,opt,name=register_response,json=registerResponse,proto3" json:"register_response,omitempty"`
	Unregister       *Message_Unregister       `protobuf:"bytes,4,opt,name=unregister,proto3" json:"unregister,omitempty"`
	Discover         *Message_Discover         `protobuf:"bytes,5,opt,name=discover,proto3" json:"discover,omitempty"`
	DiscoverResponse *Message_DiscoverResponse `protobuf:"bytes,6,opt,name=discover_response,json=discoverResponse,proto3" json:"discover_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Message_MessageType {
	if x != nil {
		return x.Type
	}
	return Message_REGISTER
}

func (x *Message) GetRegister() *Message_Register {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *Message) GetRegisterResponse() *Message_RegisterResponse {
	if x != nil {
		return x.RegisterResponse
	}
	return nil
}

func (x *Message) GetUnregister() *Message_Unregister {
	if x != nil {
		return x.Unregister
	}
	return nil
}

func (x *Message) GetDiscover() *Message_Discover {
	if x != nil {
		return x.Discover
	}
	return nil
}

func (x *Message) GetDiscoverResponse() *Message_DiscoverResponse {
	if x != nil {
		return x.DiscoverResponse
	}
	return nil
}

// Register 注册请求
type Message_Register struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ns               string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	SignedPeerRecord []byte                 `protobuf:"bytes,2,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	Ttl              uint64                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message_Register) Reset() {
	*x = Message_Register{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Register) ProtoMessage() {}

func (x *Message_Register) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Register.ProtoReflect.Descriptor instead.
func (*Message_Register) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Register) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Message_Register) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

func (x *Message_Register) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// RegisterResponse 注册响应
type Message_RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Message_ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.rendezvous.Message_ResponseStatus" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	Ttl           uint64                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_RegisterResponse) Reset() {
	*x = Message_RegisterResponse{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_RegisterResponse) ProtoMessage() {}

func (x *Message_RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_RegisterResponse.ProtoReflect.Descriptor instead.
func (*Message_RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_RegisterResponse) GetStatus() Message_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return Message_OK
}

func (x *Message_RegisterResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *Message_RegisterResponse) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// Unregister 取消注册
type Message_Unregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ns            string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Unregister) Reset() {
	*x = Message_Unregister{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Unregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Unregister) ProtoMessage() {}

func (x *Message_Unregister) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Unregister.ProtoReflect.Descriptor instead.
func (*Message_Unregister) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_Unregister) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Message_Unregister) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// Discover 发现请求
type Message_Discover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ns            string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cookie        []byte                 `protobuf:"bytes,3,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Discover) Reset() {
	*x = Message_Discover{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Discover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Discover) ProtoMessage() {}

func (x *Message_Discover) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Discover.ProtoReflect.Descriptor instead.
func (*Message_Discover) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_Discover) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Message_Discover) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Message_Discover) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

// DiscoverResponse 发现响应
type Message_DiscoverResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Registrations []*Message_Registration `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	Cookie        []byte                  `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Status        Message_ResponseStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=dep2p.rendezvous.Message_ResponseStatus" json:"status,omitempty"`
	StatusText    string                  `protobuf:"bytes,4,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_DiscoverResponse) Reset() {
	*x = Message_DiscoverResponse{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_DiscoverResponse) ProtoMessage() {}

func (x *Message_DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_DiscoverResponse.ProtoReflect.Descriptor instead.
func (*Message_DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Message_DiscoverResponse) GetRegistrations() []*Message_Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

func (x *Message_DiscoverResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *Message_DiscoverResponse) GetStatus() Message_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return Message_OK
}

func (x *Message_DiscoverResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

// Registration 注册信息
type Message_Registration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ns               string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	SignedPeerRecord []byte                 `protobuf:"bytes,2,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	Ttl              uint64                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message_Registration) Reset() {
	*x = Message_Registration{}
	mi := &file_rendezvous_rendezvous_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Registration) ProtoMessage() {}

func (x *Message_Registration) ProtoReflect() protoreflect.Message {
	mi := &file_rendezvous_rendezvous_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Registration.ProtoReflect.Descriptor instead.
func (*Message_Registration) Descriptor() ([]byte, []int) {
	return file_rendezvous_rendezvous_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Message_Registration) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Message_Registration) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

func (x *Message_Registration) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_rendezvous_rendezvous_proto protoreflect.FileDescriptor

const file_rendezvous_rendezvous_proto_rawDesc = "" +
	"\n" +
	"\x1brendezvous/rendezvous.proto\x12\x10dep2p.rendezvous\"\x82\v\n" +
	"\aMessage\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.dep2p.rendezvous.Message.MessageTypeR\x04type\x12>\n" +
	"\bregister\x18\x02 \x01(\v2\".dep2p.rendezvous.Message.RegisterR\bregister\x12W\n" +
	"\x11register_response\x18\x03 \x01(\v2*.dep2p.rendezvous.Message.RegisterResponseR\x10registerResponse\x12D\n" +
	"\n" +
	"unregister\x18\x04 \x01(\v2$.dep2p.rendezvous.Message.UnregisterR\n" +
	"unregister\x12>\n" +
	"\bdiscover\x18\x05 \x01(\v2\".dep2p.rendezvous.Message.DiscoverR\bdiscover\x12W\n" +
	"\x11discover_response\x18\x06 \x01(\v2*.dep2p.rendezvous.Message.DiscoverResponseR\x10discoverResponse\x1aZ\n" +
	"\bRegister\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12,\n" +
	"\x12signed_peer_record\x18\x02 \x01(\fR\x10signedPeerRecord\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\x1a\x87\x01\n" +
	"\x10RegisterResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.dep2p.rendezvous.Message.ResponseStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\x1a,\n" +
	"\n" +
	"Unregister\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x1aH\n" +
	"\bDiscover\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06cookie\x18\x03 \x01(\fR\x06cookie\x1a\xdb\x01\n" +
	"\x10DiscoverResponse\x12L\n" +
	"\rregistrations\x18\x01 \x03(\v2&.dep2p.rendezvous.Message.RegistrationR\rregistrations\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\fR\x06cookie\x12@\n" +
	"\x06status\x18\x03 \x01(\x0e2(.dep2p.rendezvous.Message.ResponseStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x04 \x01(\tR\n" +
	"statusText\x1a^\n" +
	"\fRegistration\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12,\n" +
	"\x12signed_peer_record\x18\x02 \x01(\fR\x10signedPeerRecord\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\"g\n" +
	"\vMessageType\x12\f\n" +
	"\bREGISTER\x10\x00\x12\x15\n" +
	"\x11REGISTER_RESPONSE\x10\x01\x12\x0e\n" +
	"\n" +
	"UNREGISTER\x10\x02\x12\f\n" +
	"\bDISCOVER\x10\x03\x12\x15\n" +
	"\x11DISCOVER_RESPONSE\x10\x04\"\xbe\x01\n" +
	"\x0eResponseStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x17\n" +
	"\x13E_INVALID_NAMESPACE\x10d\x12 \n" +
	"\x1cE_INVALID_SIGNED_PEER_RECORD\x10e\x12\x11\n" +
	"\rE_INVALID_TTL\x10f\x12\x14\n" +
	"\x10E_INVALID_COOKIE\x10g\x12\x15\n" +
	"\x10E_NOT_AUTHORIZED\x10\xc8\x01\x12\x15\n" +
	"\x10E_INTERNAL_ERROR\x10\xac\x02\x12\x12\n" +
	"\rE_UNAVAILABLE\x10\x90\x03B-Z+github.com/dep2p/dep2p/pkg/proto/rendezvousb\x06proto3"

var (
	file_rendezvous_rendezvous_proto_rawDescOnce sync.Once
	file_rendezvous_rendezvous_proto_rawDescData []byte
)

func file_rendezvous_rendezvous_proto_rawDescGZIP() []byte {
	file_rendezvous_rendezvous_proto_rawDescOnce.Do(func() {
		file_rendezvous_rendezvous_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rendezvous_rendezvous_proto_rawDesc), len(file_rendezvous_rendezvous_proto_rawDesc)))
	})
	return file_rendezvous_rendezvous_proto_rawDescData
}

var file_rendezvous_rendezvous_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rendezvous_rendezvous_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rendezvous_rendezvous_proto_goTypes = []any{
	(Message_MessageType)(0),         // 0: dep2p.rendezvous.Message.MessageType
	(Message_ResponseStatus)(0),      // 1: dep2p.rendezvous.Message.ResponseStatus
	(*Message)(nil),                  // 2: dep2p.rendezvous.Message
	(*Message_Register)(nil),         // 3: dep2p.rendezvous.Message.Register
	(*Message_RegisterResponse)(nil), // 4: dep2p.rendezvous.Message.RegisterResponse
	(*Message_Unregister)(nil),       // 5: dep2p.rendezvous.Message.Unregister
	(*Message_Discover)(nil),         // 6: dep2p.rendezvous.Message.Discover
	(*Message_DiscoverResponse)(nil), // 7: dep2p.rendezvous.Message.DiscoverResponse
	(*Message_Registration)(nil),     // 8: dep2p.rendezvous.Message.Registration
}
var file_rendezvous_rendezvous_proto_depIdxs = []int32{
	0, // 0: dep2p.rendezvous.Message.type:type_name -> dep2p.rendezvous.Message.MessageType
	3, // 1: dep2p.rendezvous.Message.register:type_name -> dep2p.rendezvous.Message.Register
	4, // 2: dep2p.rendezvous.Message.register_response:type_name -> dep2p.rendezvous.Message.RegisterResponse
	5, // 3: dep2p.rendezvous.Message.unregister:type_name -> dep2p.rendezvous.Message.Unregister
	6, // 4: dep2p.rendezvous.Message.discover:type_name -> dep2p.rendezvous.Message.Discover
	7, // 5: dep2p.rendezvous.Message.discover_response:type_name -> dep2p.rendezvous.Message.DiscoverResponse
	1, // 6: dep2p.rendezvous.Message.RegisterResponse.status:type_name -> dep2p.rendezvous.Message.ResponseStatus
	8, // 7: dep2p.rendezvous.Message.DiscoverResponse.registrations:type_name -> dep2p.rendezvous.Message.Registration
	1, // 8: dep2p.rendezvous.Message.DiscoverResponse.status:type_name -> dep2p.rendezvous.Message.ResponseStatus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_rendezvous_rendezvous_proto_init() }
func file_rendezvous_rendezvous_proto_init() {
	if File_rendezvous_rendezvous_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rendezvous_rendezvous_proto_rawDesc), len(file_rendezvous_rendezvous_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rendezvous_rendezvous_proto_goTypes,
		DependencyIndexes: file_rendezvous_rendezvous_proto_depIdxs,
		EnumInfos:         file_rendezvous_rendezvous_proto_enumTypes,
		MessageInfos:      file_rendezvous_rendezvous_proto_msgTypes,
	}.Build()
	File_rendezvous_rendezvous_proto = out.File
	file_rendezvous_rendezvous_proto_goTypes = nil
	file_rendezvous_rendezvous_proto_depIdxs = nil
}
