// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/proto/key/key.proto

package key

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyType 密钥类型
type KeyType int32

const (
	KeyType_KEY_TYPE_UNSPECIFIED KeyType = 0
	KeyType_KEY_TYPE_ED25519     KeyType = 1
	KeyType_KEY_TYPE_ECDSA       KeyType = 2
	KeyType_KEY_TYPE_RSA         KeyType = 3
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEY_TYPE_UNSPECIFIED",
		1: "KEY_TYPE_ED25519",
		2: "KEY_TYPE_ECDSA",
		3: "KEY_TYPE_RSA",
	}
	KeyType_value = map[string]int32{
		"KEY_TYPE_UNSPECIFIED": 0,
		"KEY_TYPE_ED25519":     1,
		"KEY_TYPE_ECDSA":       2,
		"KEY_TYPE_RSA":         3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_key_key_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_pkg_proto_key_key_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_key_key_proto_rawDescGZIP(), []int{0}
}

// PublicKey 公钥序列化格式
type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 密钥类型
	Type KeyType `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.key.KeyType" json:"type,omitempty"`
	// data 密钥原始字节
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_pkg_proto_key_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_key_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_pkg_proto_key_key_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PublicKey) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PrivateKey 私钥序列化格式
type PrivateKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 密钥类型
	Type KeyType `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.key.KeyType" json:"type,omitempty"`
	// data 密钥原始字节
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	mi := &file_pkg_proto_key_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_key_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_pkg_proto_key_key_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateKey) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

func (x *PrivateKey) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// SignedData 签名数据
type SignedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key 签名者的公钥
	PublicKey *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// payload 被签名的数据
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// signature 签名
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedData) Reset() {
	*x = SignedData{}
	mi := &file_pkg_proto_key_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedData) ProtoMessage() {}

func (x *SignedData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_key_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedData.ProtoReflect.Descriptor instead.
func (*SignedData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_key_key_proto_rawDescGZIP(), []int{2}
}

func (x *SignedData) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pkg_proto_key_key_proto protoreflect.FileDescriptor

const file_pkg_proto_key_key_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/key/key.proto\x12\tdep2p.key\"G\n" +
	"\tPublicKey\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.dep2p.key.KeyTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"H\n" +
	"\n" +
	"PrivateKey\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.dep2p.key.KeyTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"y\n" +
	"\n" +
	"SignedData\x123\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2\x14.dep2p.key.PublicKeyR\tpublicKey\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature*_\n" +
	"\aKeyType\x12\x18\n" +
	"\x14KEY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KEY_TYPE_ED25519\x10\x01\x12\x12\n" +
	"\x0eKEY_TYPE_ECDSA\x10\x02\x12\x10\n" +
	"\fKEY_TYPE_RSA\x10\x03B)Z'github.com/dep2p/go-dep2p/pkg/proto/keyb\x06proto3"

var (
	file_pkg_proto_key_key_proto_rawDescOnce sync.Once
	file_pkg_proto_key_key_proto_rawDescData []byte
)

func file_pkg_proto_key_key_proto_rawDescGZIP() []byte {
	file_pkg_proto_key_key_proto_rawDescOnce.Do(func() {
		file_pkg_proto_key_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_key_key_proto_rawDesc), len(file_pkg_proto_key_key_proto_rawDesc)))
	})
	return file_pkg_proto_key_key_proto_rawDescData
}

var file_pkg_proto_key_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_key_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_key_key_proto_goTypes = []any{
	(KeyType)(0),       // 0: dep2p.key.KeyType
	(*PublicKey)(nil),  // 1: dep2p.key.PublicKey
	(*PrivateKey)(nil), // 2: dep2p.key.PrivateKey
	(*SignedData)(nil), // 3: dep2p.key.SignedData
}
var file_pkg_proto_key_key_proto_depIdxs = []int32{
	0, // 0: dep2p.key.PublicKey.type:type_name -> dep2p.key.KeyType
	0, // 1: dep2p.key.PrivateKey.type:type_name -> dep2p.key.KeyType
	1, // 2: dep2p.key.SignedData.public_key:type_name -> dep2p.key.PublicKey
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_key_key_proto_init() }
func file_pkg_proto_key_key_proto_init() {
	if File_pkg_proto_key_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_key_key_proto_rawDesc), len(file_pkg_proto_key_key_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_key_key_proto_goTypes,
		DependencyIndexes: file_pkg_proto_key_key_proto_depIdxs,
		EnumInfos:         file_pkg_proto_key_key_proto_enumTypes,
		MessageInfos:      file_pkg_proto_key_key_proto_msgTypes,
	}.Build()
	File_pkg_proto_key_key_proto = out.File
	file_pkg_proto_key_key_proto_goTypes = nil
	file_pkg_proto_key_key_proto_depIdxs = nil
}
