// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/proto/peer/peer.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerState 节点状态
type PeerState int32

const (
	PeerState_PEER_STATE_UNSPECIFIED PeerState = 0
	PeerState_PEER_STATE_ONLINE      PeerState = 1
	PeerState_PEER_STATE_DEGRADED    PeerState = 2
	PeerState_PEER_STATE_OFFLINE     PeerState = 3
)

// Enum value maps for PeerState.
var (
	PeerState_name = map[int32]string{
		0: "PEER_STATE_UNSPECIFIED",
		1: "PEER_STATE_ONLINE",
		2: "PEER_STATE_DEGRADED",
		3: "PEER_STATE_OFFLINE",
	}
	PeerState_value = map[string]int32{
		"PEER_STATE_UNSPECIFIED": 0,
		"PEER_STATE_ONLINE":      1,
		"PEER_STATE_DEGRADED":    2,
		"PEER_STATE_OFFLINE":     3,
	}
)

func (x PeerState) Enum() *PeerState {
	p := new(PeerState)
	*p = x
	return p
}

func (x PeerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_peer_peer_proto_enumTypes[0].Descriptor()
}

func (PeerState) Type() protoreflect.EnumType {
	return &file_pkg_proto_peer_peer_proto_enumTypes[0]
}

func (x PeerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerState.Descriptor instead.
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_peer_peer_proto_rawDescGZIP(), []int{0}
}

// AddressInfo 节点地址信息
type AddressInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 节点ID (32字节)
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addrs 地址列表 (multiaddr 格式字符串)
	Addrs         []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_peer_proto_rawDescGZIP(), []int{0}
}

func (x *AddressInfo) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *AddressInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// PeerRecord 节点记录
// 用于在 DHT 中发布和查询节点信息
type PeerRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 节点ID (32字节)
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// realm_id 业务域ID
	RealmId string `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// seq 序列号 (单调递增)
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// addrs 地址列表
	Addrs []string `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// timestamp 记录创建时间
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ttl 记录有效期
	Ttl           *durationpb.Duration `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRecord) Reset() {
	*x = PeerRecord{}
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecord) ProtoMessage() {}

func (x *PeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecord.ProtoReflect.Descriptor instead.
func (*PeerRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PeerRecord) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *PeerRecord) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *PeerRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PeerRecord) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PeerRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PeerRecord) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// SignedPeerRecord 签名的节点记录
type SignedPeerRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// record 节点记录
	Record *PeerRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// signature 签名 (使用节点私钥对 record 签名)
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// public_key 签名者公钥 (可选，用于验证)
	PublicKey     []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPeerRecord) Reset() {
	*x = SignedPeerRecord{}
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPeerRecord) ProtoMessage() {}

func (x *SignedPeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPeerRecord.ProtoReflect.Descriptor instead.
func (*SignedPeerRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_peer_proto_rawDescGZIP(), []int{2}
}

func (x *SignedPeerRecord) GetRecord() *PeerRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *SignedPeerRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPeerRecord) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// PeerInfo 节点详细信息
type PeerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 节点ID
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addrs 地址列表
	Addrs []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// state 节点状态
	State PeerState `protobuf:"varint,3,opt,name=state,proto3,enum=dep2p.peer.PeerState" json:"state,omitempty"`
	// protocols 支持的协议列表
	Protocols []string `protobuf:"bytes,4,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// agent_version 客户端版本
	AgentVersion string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// latency_ms 延迟 (毫秒)
	LatencyMs int64 `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// connected_since 连接建立时间
	ConnectedSince *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_peer_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_peer_peer_proto_rawDescGZIP(), []int{3}
}

func (x *PeerInfo) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *PeerInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PeerInfo) GetState() PeerState {
	if x != nil {
		return x.State
	}
	return PeerState_PEER_STATE_UNSPECIFIED
}

func (x *PeerInfo) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *PeerInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PeerInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PeerInfo) GetConnectedSince() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedSince
	}
	return nil
}

var File_pkg_proto_peer_peer_proto protoreflect.FileDescriptor

const file_pkg_proto_peer_peer_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/peer/peer.proto\x12\n" +
	"dep2p.peer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"<\n" +
	"\vAddressInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"\xcf\x01\n" +
	"\n" +
	"PeerRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05addrs\x18\x04 \x03(\tR\x05addrs\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x03ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x7f\n" +
	"\x10SignedPeerRecord\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.dep2p.peer.PeerRecordR\x06record\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\x8d\x02\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12+\n" +
	"\x05state\x18\x03 \x01(\x0e2\x15.dep2p.peer.PeerStateR\x05state\x12\x1c\n" +
	"\tprotocols\x18\x04 \x03(\tR\tprotocols\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12C\n" +
	"\x0fconnected_since\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0econnectedSince*o\n" +
	"\tPeerState\x12\x1a\n" +
	"\x16PEER_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PEER_STATE_ONLINE\x10\x01\x12\x17\n" +
	"\x13PEER_STATE_DEGRADED\x10\x02\x12\x16\n" +
	"\x12PEER_STATE_OFFLINE\x10\x03B*Z(github.com/dep2p/go-dep2p/pkg/proto/peerb\x06proto3"

var (
	file_pkg_proto_peer_peer_proto_rawDescOnce sync.Once
	file_pkg_proto_peer_peer_proto_rawDescData []byte
)

func file_pkg_proto_peer_peer_proto_rawDescGZIP() []byte {
	file_pkg_proto_peer_peer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_peer_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_peer_peer_proto_rawDesc), len(file_pkg_proto_peer_peer_proto_rawDesc)))
	})
	return file_pkg_proto_peer_peer_proto_rawDescData
}

var file_pkg_proto_peer_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_peer_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_peer_peer_proto_goTypes = []any{
	(PeerState)(0),                // 0: dep2p.peer.PeerState
	(*AddressInfo)(nil),           // 1: dep2p.peer.AddressInfo
	(*PeerRecord)(nil),            // 2: dep2p.peer.PeerRecord
	(*SignedPeerRecord)(nil),      // 3: dep2p.peer.SignedPeerRecord
	(*PeerInfo)(nil),              // 4: dep2p.peer.PeerInfo
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
}
var file_pkg_proto_peer_peer_proto_depIdxs = []int32{
	5, // 0: dep2p.peer.PeerRecord.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: dep2p.peer.PeerRecord.ttl:type_name -> google.protobuf.Duration
	2, // 2: dep2p.peer.SignedPeerRecord.record:type_name -> dep2p.peer.PeerRecord
	0, // 3: dep2p.peer.PeerInfo.state:type_name -> dep2p.peer.PeerState
	5, // 4: dep2p.peer.PeerInfo.connected_since:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_peer_peer_proto_init() }
func file_pkg_proto_peer_peer_proto_init() {
	if File_pkg_proto_peer_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_peer_peer_proto_rawDesc), len(file_pkg_proto_peer_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_peer_peer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_peer_peer_proto_depIdxs,
		EnumInfos:         file_pkg_proto_peer_peer_proto_enumTypes,
		MessageInfos:      file_pkg_proto_peer_peer_proto_msgTypes,
	}.Build()
	File_pkg_proto_peer_peer_proto = out.File
	file_pkg_proto_peer_peer_proto_goTypes = nil
	file_pkg_proto_peer_peer_proto_depIdxs = nil
}
