// DeP2P AddressBook Protocol Definitions
// 地址簿协议消息定义（Realm 成员地址发现）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: addressbook/addressbook.proto

package addressbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NATType NAT 类型枚举
type NATType int32

const (
	NATType_NAT_TYPE_UNKNOWN         NATType = 0 // 未知
	NATType_NAT_TYPE_NONE            NATType = 1 // 无 NAT（公网）
	NATType_NAT_TYPE_FULL_CONE       NATType = 2 // 完全锥形 NAT
	NATType_NAT_TYPE_RESTRICTED      NATType = 3 // 受限锥形 NAT
	NATType_NAT_TYPE_PORT_RESTRICTED NATType = 4 // 端口受限锥形 NAT
	NATType_NAT_TYPE_SYMMETRIC       NATType = 5 // 对称型 NAT
)

// Enum value maps for NATType.
var (
	NATType_name = map[int32]string{
		0: "NAT_TYPE_UNKNOWN",
		1: "NAT_TYPE_NONE",
		2: "NAT_TYPE_FULL_CONE",
		3: "NAT_TYPE_RESTRICTED",
		4: "NAT_TYPE_PORT_RESTRICTED",
		5: "NAT_TYPE_SYMMETRIC",
	}
	NATType_value = map[string]int32{
		"NAT_TYPE_UNKNOWN":         0,
		"NAT_TYPE_NONE":            1,
		"NAT_TYPE_FULL_CONE":       2,
		"NAT_TYPE_RESTRICTED":      3,
		"NAT_TYPE_PORT_RESTRICTED": 4,
		"NAT_TYPE_SYMMETRIC":       5,
	}
)

func (x NATType) Enum() *NATType {
	p := new(NATType)
	*p = x
	return p
}

func (x NATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATType) Descriptor() protoreflect.EnumDescriptor {
	return file_addressbook_addressbook_proto_enumTypes[0].Descriptor()
}

func (NATType) Type() protoreflect.EnumType {
	return &file_addressbook_addressbook_proto_enumTypes[0]
}

func (x NATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATType.Descriptor instead.
func (NATType) EnumDescriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{0}
}

// UpdateType 地址更新类型枚举
type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNKNOWN UpdateType = 0 // 未知
	UpdateType_UPDATE_TYPE_ADD     UpdateType = 1 // 新增地址
	UpdateType_UPDATE_TYPE_REMOVE  UpdateType = 2 // 移除地址
	UpdateType_UPDATE_TYPE_REPLACE UpdateType = 3 // 替换全部地址
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNKNOWN",
		1: "UPDATE_TYPE_ADD",
		2: "UPDATE_TYPE_REMOVE",
		3: "UPDATE_TYPE_REPLACE",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNKNOWN": 0,
		"UPDATE_TYPE_ADD":     1,
		"UPDATE_TYPE_REMOVE":  2,
		"UPDATE_TYPE_REPLACE": 3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_addressbook_addressbook_proto_enumTypes[1].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_addressbook_addressbook_proto_enumTypes[1]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{1}
}

// MessageType 消息类型
type AddressBookMessage_MessageType int32

const (
	AddressBookMessage_UNKNOWN           AddressBookMessage_MessageType = 0
	AddressBookMessage_REGISTER          AddressBookMessage_MessageType = 1 // 注册请求
	AddressBookMessage_REGISTER_RESPONSE AddressBookMessage_MessageType = 2 // 注册响应
	AddressBookMessage_QUERY             AddressBookMessage_MessageType = 3 // 查询请求
	AddressBookMessage_RESPONSE          AddressBookMessage_MessageType = 4 // 查询响应
	AddressBookMessage_BATCH_QUERY       AddressBookMessage_MessageType = 5 // 批量查询请求
	AddressBookMessage_BATCH_RESPONSE    AddressBookMessage_MessageType = 6 // 批量查询响应
	AddressBookMessage_UPDATE            AddressBookMessage_MessageType = 7 // 更新通知
)

// Enum value maps for AddressBookMessage_MessageType.
var (
	AddressBookMessage_MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "REGISTER",
		2: "REGISTER_RESPONSE",
		3: "QUERY",
		4: "RESPONSE",
		5: "BATCH_QUERY",
		6: "BATCH_RESPONSE",
		7: "UPDATE",
	}
	AddressBookMessage_MessageType_value = map[string]int32{
		"UNKNOWN":           0,
		"REGISTER":          1,
		"REGISTER_RESPONSE": 2,
		"QUERY":             3,
		"RESPONSE":          4,
		"BATCH_QUERY":       5,
		"BATCH_RESPONSE":    6,
		"UPDATE":            7,
	}
)

func (x AddressBookMessage_MessageType) Enum() *AddressBookMessage_MessageType {
	p := new(AddressBookMessage_MessageType)
	*p = x
	return p
}

func (x AddressBookMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressBookMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_addressbook_addressbook_proto_enumTypes[2].Descriptor()
}

func (AddressBookMessage_MessageType) Type() protoreflect.EnumType {
	return &file_addressbook_addressbook_proto_enumTypes[2]
}

func (x AddressBookMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressBookMessage_MessageType.Descriptor instead.
func (AddressBookMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{8, 0}
}

// MemberEntry 成员地址条目
//
// 存储 Realm 成员的地址信息，用于"仅 ID 连接"时的地址发现。
type MemberEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 成员节点 ID
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addrs 直连地址列表（Multiaddr 编码）
	Addrs [][]byte `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// nat_type NAT 类型
	NatType NATType `protobuf:"varint,3,opt,name=nat_type,json=natType,proto3,enum=dep2p.addressbook.NATType" json:"nat_type,omitempty"`
	// capabilities 能力标签
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// online 是否在线
	Online bool `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	// last_seen 最后活跃时间（Unix 时间戳，秒）
	LastSeen int64 `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// last_update 最后更新时间（Unix 时间戳，秒）
	LastUpdate    int64 `protobuf:"varint,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberEntry) Reset() {
	*x = MemberEntry{}
	mi := &file_addressbook_addressbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEntry) ProtoMessage() {}

func (x *MemberEntry) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEntry.ProtoReflect.Descriptor instead.
func (*MemberEntry) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{0}
}

func (x *MemberEntry) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *MemberEntry) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *MemberEntry) GetNatType() NATType {
	if x != nil {
		return x.NatType
	}
	return NATType_NAT_TYPE_UNKNOWN
}

func (x *MemberEntry) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MemberEntry) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *MemberEntry) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *MemberEntry) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

// AddressRegister 地址注册请求
//
// 成员向 Relay 注册其地址信息。
type AddressRegister struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 注册节点的 ID
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// addrs 节点地址列表（Multiaddr 编码）
	Addrs [][]byte `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// nat_type 节点的 NAT 类型
	NatType NATType `protobuf:"varint,3,opt,name=nat_type,json=natType,proto3,enum=dep2p.addressbook.NATType" json:"nat_type,omitempty"`
	// capabilities 节点能力标签
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// signature 消息签名（使用节点私钥签名）
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// timestamp 消息时间戳（Unix 时间戳，秒）
	Timestamp     int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRegister) Reset() {
	*x = AddressRegister{}
	mi := &file_addressbook_addressbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRegister) ProtoMessage() {}

func (x *AddressRegister) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRegister.ProtoReflect.Descriptor instead.
func (*AddressRegister) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{1}
}

func (x *AddressRegister) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *AddressRegister) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *AddressRegister) GetNatType() NATType {
	if x != nil {
		return x.NatType
	}
	return NATType_NAT_TYPE_UNKNOWN
}

func (x *AddressRegister) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AddressRegister) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AddressRegister) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AddressRegisterResponse 地址注册响应
type AddressRegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error 错误信息（仅失败时）
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// ttl 建议的续期时间（秒）
	Ttl           int64 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRegisterResponse) Reset() {
	*x = AddressRegisterResponse{}
	mi := &file_addressbook_addressbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRegisterResponse) ProtoMessage() {}

func (x *AddressRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRegisterResponse.ProtoReflect.Descriptor instead.
func (*AddressRegisterResponse) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{2}
}

func (x *AddressRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddressRegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddressRegisterResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// AddressQuery 地址查询请求
//
// 向 Relay 查询目标成员的地址。
type AddressQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_node_id 目标节点 ID
	TargetNodeId []byte `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// requestor_id 请求者节点 ID
	RequestorId   []byte `protobuf:"bytes,2,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressQuery) Reset() {
	*x = AddressQuery{}
	mi := &file_addressbook_addressbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressQuery) ProtoMessage() {}

func (x *AddressQuery) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressQuery.ProtoReflect.Descriptor instead.
func (*AddressQuery) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{3}
}

func (x *AddressQuery) GetTargetNodeId() []byte {
	if x != nil {
		return x.TargetNodeId
	}
	return nil
}

func (x *AddressQuery) GetRequestorId() []byte {
	if x != nil {
		return x.RequestorId
	}
	return nil
}

// AddressResponse 地址查询响应
type AddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found 是否找到
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// entry 成员条目（仅找到时）
	Entry *MemberEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	// error 错误信息（仅失败时）
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_addressbook_addressbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{4}
}

func (x *AddressResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AddressResponse) GetEntry() *MemberEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *AddressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchAddressQuery 批量地址查询请求
type BatchAddressQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_node_ids 目标节点 ID 列表
	TargetNodeIds [][]byte `protobuf:"bytes,1,rep,name=target_node_ids,json=targetNodeIds,proto3" json:"target_node_ids,omitempty"`
	// requestor_id 请求者节点 ID
	RequestorId   []byte `protobuf:"bytes,2,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddressQuery) Reset() {
	*x = BatchAddressQuery{}
	mi := &file_addressbook_addressbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddressQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddressQuery) ProtoMessage() {}

func (x *BatchAddressQuery) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddressQuery.ProtoReflect.Descriptor instead.
func (*BatchAddressQuery) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{5}
}

func (x *BatchAddressQuery) GetTargetNodeIds() [][]byte {
	if x != nil {
		return x.TargetNodeIds
	}
	return nil
}

func (x *BatchAddressQuery) GetRequestorId() []byte {
	if x != nil {
		return x.RequestorId
	}
	return nil
}

// BatchAddressResponse 批量地址查询响应
type BatchAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries 查询结果列表
	Entries       []*AddressResponse `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddressResponse) Reset() {
	*x = BatchAddressResponse{}
	mi := &file_addressbook_addressbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddressResponse) ProtoMessage() {}

func (x *BatchAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddressResponse.ProtoReflect.Descriptor instead.
func (*BatchAddressResponse) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{6}
}

func (x *BatchAddressResponse) GetEntries() []*AddressResponse {
	if x != nil {
		return x.Entries
	}
	return nil
}

// AddressUpdate 地址更新通知
//
// 当成员地址发生变化时，Relay 向其他成员广播更新。
type AddressUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id 更新的节点 ID
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// new_addrs 新增的地址列表
	NewAddrs [][]byte `protobuf:"bytes,2,rep,name=new_addrs,json=newAddrs,proto3" json:"new_addrs,omitempty"`
	// old_addrs 移除的地址列表
	OldAddrs [][]byte `protobuf:"bytes,3,rep,name=old_addrs,json=oldAddrs,proto3" json:"old_addrs,omitempty"`
	// update_type 更新类型
	UpdateType UpdateType `protobuf:"varint,4,opt,name=update_type,json=updateType,proto3,enum=dep2p.addressbook.UpdateType" json:"update_type,omitempty"`
	// timestamp 更新时间戳
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// signature Relay 签名（证明更新来源可信）
	Signature     []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressUpdate) Reset() {
	*x = AddressUpdate{}
	mi := &file_addressbook_addressbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressUpdate) ProtoMessage() {}

func (x *AddressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressUpdate.ProtoReflect.Descriptor instead.
func (*AddressUpdate) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{7}
}

func (x *AddressUpdate) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *AddressUpdate) GetNewAddrs() [][]byte {
	if x != nil {
		return x.NewAddrs
	}
	return nil
}

func (x *AddressUpdate) GetOldAddrs() [][]byte {
	if x != nil {
		return x.OldAddrs
	}
	return nil
}

func (x *AddressUpdate) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_UPDATE_TYPE_UNKNOWN
}

func (x *AddressUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AddressUpdate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AddressBookMessage 地址簿协议消息封装
//
// 用于在单一流上复用多种消息类型。
type AddressBookMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type 消息类型
	Type AddressBookMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.addressbook.AddressBookMessage_MessageType" json:"type,omitempty"`
	// 消息体（根据 type 选择）
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*AddressBookMessage_Register
	//	*AddressBookMessage_RegisterResponse
	//	*AddressBookMessage_Query
	//	*AddressBookMessage_Response
	//	*AddressBookMessage_BatchQuery
	//	*AddressBookMessage_BatchResponse
	//	*AddressBookMessage_Update
	Payload       isAddressBookMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressBookMessage) Reset() {
	*x = AddressBookMessage{}
	mi := &file_addressbook_addressbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressBookMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookMessage) ProtoMessage() {}

func (x *AddressBookMessage) ProtoReflect() protoreflect.Message {
	mi := &file_addressbook_addressbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookMessage.ProtoReflect.Descriptor instead.
func (*AddressBookMessage) Descriptor() ([]byte, []int) {
	return file_addressbook_addressbook_proto_rawDescGZIP(), []int{8}
}

func (x *AddressBookMessage) GetType() AddressBookMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return AddressBookMessage_UNKNOWN
}

func (x *AddressBookMessage) GetPayload() isAddressBookMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AddressBookMessage) GetRegister() *AddressRegister {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AddressBookMessage) GetRegisterResponse() *AddressRegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *AddressBookMessage) GetQuery() *AddressQuery {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *AddressBookMessage) GetResponse() *AddressResponse {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *AddressBookMessage) GetBatchQuery() *BatchAddressQuery {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_BatchQuery); ok {
			return x.BatchQuery
		}
	}
	return nil
}

func (x *AddressBookMessage) GetBatchResponse() *BatchAddressResponse {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_BatchResponse); ok {
			return x.BatchResponse
		}
	}
	return nil
}

func (x *AddressBookMessage) GetUpdate() *AddressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AddressBookMessage_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isAddressBookMessage_Payload interface {
	isAddressBookMessage_Payload()
}

type AddressBookMessage_Register struct {
	Register *AddressRegister `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AddressBookMessage_RegisterResponse struct {
	RegisterResponse *AddressRegisterResponse `protobuf:"bytes,3,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type AddressBookMessage_Query struct {
	Query *AddressQuery `protobuf:"bytes,4,opt,name=query,proto3,oneof"`
}

type AddressBookMessage_Response struct {
	Response *AddressResponse `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

type AddressBookMessage_BatchQuery struct {
	BatchQuery *BatchAddressQuery `protobuf:"bytes,6,opt,name=batch_query,json=batchQuery,proto3,oneof"`
}

type AddressBookMessage_BatchResponse struct {
	BatchResponse *BatchAddressResponse `protobuf:"bytes,7,opt,name=batch_response,json=batchResponse,proto3,oneof"`
}

type AddressBookMessage_Update struct {
	Update *AddressUpdate `protobuf:"bytes,8,opt,name=update,proto3,oneof"`
}

func (*AddressBookMessage_Register) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_RegisterResponse) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_Query) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_Response) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_BatchQuery) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_BatchResponse) isAddressBookMessage_Payload() {}

func (*AddressBookMessage_Update) isAddressBookMessage_Payload() {}

var File_addressbook_addressbook_proto protoreflect.FileDescriptor

const file_addressbook_addressbook_proto_rawDesc = "" +
	"\n" +
	"\x1daddressbook/addressbook.proto\x12\x11dep2p.addressbook\"\xed\x01\n" +
	"\vMemberEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x125\n" +
	"\bnat_type\x18\x03 \x01(\x0e2\x1a.dep2p.addressbook.NATTypeR\anatType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x1f\n" +
	"\vlast_update\x18\a \x01(\x03R\n" +
	"lastUpdate\"\xd7\x01\n" +
	"\x0fAddressRegister\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x125\n" +
	"\bnat_type\x18\x03 \x01(\x0e2\x1a.dep2p.addressbook.NATTypeR\anatType\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"[\n" +
	"\x17AddressRegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\"W\n" +
	"\fAddressQuery\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\fR\ftargetNodeId\x12!\n" +
	"\frequestor_id\x18\x02 \x01(\fR\vrequestorId\"s\n" +
	"\x0fAddressResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x124\n" +
	"\x05entry\x18\x02 \x01(\v2\x1e.dep2p.addressbook.MemberEntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\x11BatchAddressQuery\x12&\n" +
	"\x0ftarget_node_ids\x18\x01 \x03(\fR\rtargetNodeIds\x12!\n" +
	"\frequestor_id\x18\x02 \x01(\fR\vrequestorId\"T\n" +
	"\x14BatchAddressResponse\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".dep2p.addressbook.AddressResponseR\aentries\"\xde\x01\n" +
	"\rAddressUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\fR\x06nodeId\x12\x1b\n" +
	"\tnew_addrs\x18\x02 \x03(\fR\bnewAddrs\x12\x1b\n" +
	"\told_addrs\x18\x03 \x03(\fR\boldAddrs\x12>\n" +
	"\vupdate_type\x18\x04 \x01(\x0e2\x1d.dep2p.addressbook.UpdateTypeR\n" +
	"updateType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xe1\x05\n" +
	"\x12AddressBookMessage\x12E\n" +
	"\x04type\x18\x01 \x01(\x0e21.dep2p.addressbook.AddressBookMessage.MessageTypeR\x04type\x12@\n" +
	"\bregister\x18\x02 \x01(\v2\".dep2p.addressbook.AddressRegisterH\x00R\bregister\x12Y\n" +
	"\x11register_response\x18\x03 \x01(\v2*.dep2p.addressbook.AddressRegisterResponseH\x00R\x10registerResponse\x127\n" +
	"\x05query\x18\x04 \x01(\v2\x1f.dep2p.addressbook.AddressQueryH\x00R\x05query\x12@\n" +
	"\bresponse\x18\x05 \x01(\v2\".dep2p.addressbook.AddressResponseH\x00R\bresponse\x12G\n" +
	"\vbatch_query\x18\x06 \x01(\v2$.dep2p.addressbook.BatchAddressQueryH\x00R\n" +
	"batchQuery\x12P\n" +
	"\x0ebatch_response\x18\a \x01(\v2'.dep2p.addressbook.BatchAddressResponseH\x00R\rbatchResponse\x12:\n" +
	"\x06update\x18\b \x01(\v2 .dep2p.addressbook.AddressUpdateH\x00R\x06update\"\x89\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\x15\n" +
	"\x11REGISTER_RESPONSE\x10\x02\x12\t\n" +
	"\x05QUERY\x10\x03\x12\f\n" +
	"\bRESPONSE\x10\x04\x12\x0f\n" +
	"\vBATCH_QUERY\x10\x05\x12\x12\n" +
	"\x0eBATCH_RESPONSE\x10\x06\x12\n" +
	"\n" +
	"\x06UPDATE\x10\aB\t\n" +
	"\apayload*\x99\x01\n" +
	"\aNATType\x12\x14\n" +
	"\x10NAT_TYPE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rNAT_TYPE_NONE\x10\x01\x12\x16\n" +
	"\x12NAT_TYPE_FULL_CONE\x10\x02\x12\x17\n" +
	"\x13NAT_TYPE_RESTRICTED\x10\x03\x12\x1c\n" +
	"\x18NAT_TYPE_PORT_RESTRICTED\x10\x04\x12\x16\n" +
	"\x12NAT_TYPE_SYMMETRIC\x10\x05*k\n" +
	"\n" +
	"UpdateType\x12\x17\n" +
	"\x13UPDATE_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fUPDATE_TYPE_ADD\x10\x01\x12\x16\n" +
	"\x12UPDATE_TYPE_REMOVE\x10\x02\x12\x17\n" +
	"\x13UPDATE_TYPE_REPLACE\x10\x03B.Z,github.com/dep2p/dep2p/pkg/proto/addressbookb\x06proto3"

var (
	file_addressbook_addressbook_proto_rawDescOnce sync.Once
	file_addressbook_addressbook_proto_rawDescData []byte
)

func file_addressbook_addressbook_proto_rawDescGZIP() []byte {
	file_addressbook_addressbook_proto_rawDescOnce.Do(func() {
		file_addressbook_addressbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_addressbook_addressbook_proto_rawDesc), len(file_addressbook_addressbook_proto_rawDesc)))
	})
	return file_addressbook_addressbook_proto_rawDescData
}

var file_addressbook_addressbook_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_addressbook_addressbook_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_addressbook_addressbook_proto_goTypes = []any{
	(NATType)(0),                        // 0: dep2p.addressbook.NATType
	(UpdateType)(0),                     // 1: dep2p.addressbook.UpdateType
	(AddressBookMessage_MessageType)(0), // 2: dep2p.addressbook.AddressBookMessage.MessageType
	(*MemberEntry)(nil),                 // 3: dep2p.addressbook.MemberEntry
	(*AddressRegister)(nil),             // 4: dep2p.addressbook.AddressRegister
	(*AddressRegisterResponse)(nil),     // 5: dep2p.addressbook.AddressRegisterResponse
	(*AddressQuery)(nil),                // 6: dep2p.addressbook.AddressQuery
	(*AddressResponse)(nil),             // 7: dep2p.addressbook.AddressResponse
	(*BatchAddressQuery)(nil),           // 8: dep2p.addressbook.BatchAddressQuery
	(*BatchAddressResponse)(nil),        // 9: dep2p.addressbook.BatchAddressResponse
	(*AddressUpdate)(nil),               // 10: dep2p.addressbook.AddressUpdate
	(*AddressBookMessage)(nil),          // 11: dep2p.addressbook.AddressBookMessage
}
var file_addressbook_addressbook_proto_depIdxs = []int32{
	0,  // 0: dep2p.addressbook.MemberEntry.nat_type:type_name -> dep2p.addressbook.NATType
	0,  // 1: dep2p.addressbook.AddressRegister.nat_type:type_name -> dep2p.addressbook.NATType
	3,  // 2: dep2p.addressbook.AddressResponse.entry:type_name -> dep2p.addressbook.MemberEntry
	7,  // 3: dep2p.addressbook.BatchAddressResponse.entries:type_name -> dep2p.addressbook.AddressResponse
	1,  // 4: dep2p.addressbook.AddressUpdate.update_type:type_name -> dep2p.addressbook.UpdateType
	2,  // 5: dep2p.addressbook.AddressBookMessage.type:type_name -> dep2p.addressbook.AddressBookMessage.MessageType
	4,  // 6: dep2p.addressbook.AddressBookMessage.register:type_name -> dep2p.addressbook.AddressRegister
	5,  // 7: dep2p.addressbook.AddressBookMessage.register_response:type_name -> dep2p.addressbook.AddressRegisterResponse
	6,  // 8: dep2p.addressbook.AddressBookMessage.query:type_name -> dep2p.addressbook.AddressQuery
	7,  // 9: dep2p.addressbook.AddressBookMessage.response:type_name -> dep2p.addressbook.AddressResponse
	8,  // 10: dep2p.addressbook.AddressBookMessage.batch_query:type_name -> dep2p.addressbook.BatchAddressQuery
	9,  // 11: dep2p.addressbook.AddressBookMessage.batch_response:type_name -> dep2p.addressbook.BatchAddressResponse
	10, // 12: dep2p.addressbook.AddressBookMessage.update:type_name -> dep2p.addressbook.AddressUpdate
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_addressbook_addressbook_proto_init() }
func file_addressbook_addressbook_proto_init() {
	if File_addressbook_addressbook_proto != nil {
		return
	}
	file_addressbook_addressbook_proto_msgTypes[8].OneofWrappers = []any{
		(*AddressBookMessage_Register)(nil),
		(*AddressBookMessage_RegisterResponse)(nil),
		(*AddressBookMessage_Query)(nil),
		(*AddressBookMessage_Response)(nil),
		(*AddressBookMessage_BatchQuery)(nil),
		(*AddressBookMessage_BatchResponse)(nil),
		(*AddressBookMessage_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_addressbook_addressbook_proto_rawDesc), len(file_addressbook_addressbook_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_addressbook_addressbook_proto_goTypes,
		DependencyIndexes: file_addressbook_addressbook_proto_depIdxs,
		EnumInfos:         file_addressbook_addressbook_proto_enumTypes,
		MessageInfos:      file_addressbook_addressbook_proto_msgTypes,
	}.Build()
	File_addressbook_addressbook_proto = out.File
	file_addressbook_addressbook_proto_goTypes = nil
	file_addressbook_addressbook_proto_depIdxs = nil
}
