// DeP2P Identify Protocol Definitions
// 身份识别协议消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: identify/identify.proto

package identify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identify 身份识别消息
// 用于节点间交换基本信息
type Identify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version 协议版本（如 "dep2p/1.0.0"）
	ProtocolVersion []byte `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// agent_version 代理版本（如 "go-dep2p/1.0.0"）
	AgentVersion []byte `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// public_key 节点公钥
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// listen_addrs 监听地址列表（multiaddr 格式）
	ListenAddrs [][]byte `protobuf:"bytes,4,rep,name=listen_addrs,json=listenAddrs,proto3" json:"listen_addrs,omitempty"`
	// observed_addr 对端观察到的本节点地址
	ObservedAddr []byte `protobuf:"bytes,5,opt,name=observed_addr,json=observedAddr,proto3" json:"observed_addr,omitempty"`
	// protocols 支持的协议列表
	Protocols []string `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// signed_peer_record 签名的节点记录
	SignedPeerRecord []byte `protobuf:"bytes,8,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Identify) Reset() {
	*x = Identify{}
	mi := &file_identify_identify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identify) ProtoMessage() {}

func (x *Identify) ProtoReflect() protoreflect.Message {
	mi := &file_identify_identify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identify.ProtoReflect.Descriptor instead.
func (*Identify) Descriptor() ([]byte, []int) {
	return file_identify_identify_proto_rawDescGZIP(), []int{0}
}

func (x *Identify) GetProtocolVersion() []byte {
	if x != nil {
		return x.ProtocolVersion
	}
	return nil
}

func (x *Identify) GetAgentVersion() []byte {
	if x != nil {
		return x.AgentVersion
	}
	return nil
}

func (x *Identify) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Identify) GetListenAddrs() [][]byte {
	if x != nil {
		return x.ListenAddrs
	}
	return nil
}

func (x *Identify) GetObservedAddr() []byte {
	if x != nil {
		return x.ObservedAddr
	}
	return nil
}

func (x *Identify) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Identify) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

// Push 身份推送消息
// 用于通知对端地址变更
type Push struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocols 新增的协议列表
	Protocols []string `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// signed_peer_record 更新的签名节点记录
	SignedPeerRecord []byte `protobuf:"bytes,2,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Push) Reset() {
	*x = Push{}
	mi := &file_identify_identify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_identify_identify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push.ProtoReflect.Descriptor instead.
func (*Push) Descriptor() ([]byte, []int) {
	return file_identify_identify_proto_rawDescGZIP(), []int{1}
}

func (x *Push) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Push) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

var File_identify_identify_proto protoreflect.FileDescriptor

const file_identify_identify_proto_rawDesc = "" +
	"\n" +
	"\x17identify/identify.proto\x12\x0edep2p.identify\"\x8d\x02\n" +
	"\bIdentify\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\fR\x0fprotocolVersion\x12#\n" +
	"\ragent_version\x18\x02 \x01(\fR\fagentVersion\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12!\n" +
	"\flisten_addrs\x18\x04 \x03(\fR\vlistenAddrs\x12#\n" +
	"\robserved_addr\x18\x05 \x01(\fR\fobservedAddr\x12\x1c\n" +
	"\tprotocols\x18\x06 \x03(\tR\tprotocols\x12,\n" +
	"\x12signed_peer_record\x18\b \x01(\fR\x10signedPeerRecord\"R\n" +
	"\x04Push\x12\x1c\n" +
	"\tprotocols\x18\x01 \x03(\tR\tprotocols\x12,\n" +
	"\x12signed_peer_record\x18\x02 \x01(\fR\x10signedPeerRecordB+Z)github.com/dep2p/dep2p/pkg/proto/identifyb\x06proto3"

var (
	file_identify_identify_proto_rawDescOnce sync.Once
	file_identify_identify_proto_rawDescData []byte
)

func file_identify_identify_proto_rawDescGZIP() []byte {
	file_identify_identify_proto_rawDescOnce.Do(func() {
		file_identify_identify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identify_identify_proto_rawDesc), len(file_identify_identify_proto_rawDesc)))
	})
	return file_identify_identify_proto_rawDescData
}

var file_identify_identify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identify_identify_proto_goTypes = []any{
	(*Identify)(nil), // 0: dep2p.identify.Identify
	(*Push)(nil),     // 1: dep2p.identify.Push
}
var file_identify_identify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identify_identify_proto_init() }
func file_identify_identify_proto_init() {
	if File_identify_identify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identify_identify_proto_rawDesc), len(file_identify_identify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identify_identify_proto_goTypes,
		DependencyIndexes: file_identify_identify_proto_depIdxs,
		MessageInfos:      file_identify_identify_proto_msgTypes,
	}.Build()
	File_identify_identify_proto = out.File
	file_identify_identify_proto_goTypes = nil
	file_identify_identify_proto_depIdxs = nil
}
