// DeP2P GossipSub Protocol Definitions
// GossipSub 发布订阅协议消息定义
//
// Protocol: /dep2p/app/<realmID>/pubsub/1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: gossipsub/gossipsub.proto

package gossipsub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthOpts_AuthMode int32

const (
	AuthOpts_NONE AuthOpts_AuthMode = 0
	AuthOpts_KEY  AuthOpts_AuthMode = 1
	AuthOpts_WOT  AuthOpts_AuthMode = 2
)

// Enum value maps for AuthOpts_AuthMode.
var (
	AuthOpts_AuthMode_name = map[int32]string{
		0: "NONE",
		1: "KEY",
		2: "WOT",
	}
	AuthOpts_AuthMode_value = map[string]int32{
		"NONE": 0,
		"KEY":  1,
		"WOT":  2,
	}
)

func (x AuthOpts_AuthMode) Enum() *AuthOpts_AuthMode {
	p := new(AuthOpts_AuthMode)
	*p = x
	return p
}

func (x AuthOpts_AuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthOpts_AuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gossipsub_gossipsub_proto_enumTypes[0].Descriptor()
}

func (AuthOpts_AuthMode) Type() protoreflect.EnumType {
	return &file_gossipsub_gossipsub_proto_enumTypes[0]
}

func (x AuthOpts_AuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthOpts_AuthMode.Descriptor instead.
func (AuthOpts_AuthMode) EnumDescriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{10, 0}
}

type EncOpts_EncMode int32

const (
	EncOpts_NONE      EncOpts_EncMode = 0
	EncOpts_SHAREDKEY EncOpts_EncMode = 1
	EncOpts_WOT       EncOpts_EncMode = 2
)

// Enum value maps for EncOpts_EncMode.
var (
	EncOpts_EncMode_name = map[int32]string{
		0: "NONE",
		1: "SHAREDKEY",
		2: "WOT",
	}
	EncOpts_EncMode_value = map[string]int32{
		"NONE":      0,
		"SHAREDKEY": 1,
		"WOT":       2,
	}
)

func (x EncOpts_EncMode) Enum() *EncOpts_EncMode {
	p := new(EncOpts_EncMode)
	*p = x
	return p
}

func (x EncOpts_EncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncOpts_EncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gossipsub_gossipsub_proto_enumTypes[1].Descriptor()
}

func (EncOpts_EncMode) Type() protoreflect.EnumType {
	return &file_gossipsub_gossipsub_proto_enumTypes[1]
}

func (x EncOpts_EncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncOpts_EncMode.Descriptor instead.
func (EncOpts_EncMode) EnumDescriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{11, 0}
}

// RPC GossipSub RPC 消息
type RPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubOpts             `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Publish       []*Message             `protobuf:"bytes,2,rep,name=publish,proto3" json:"publish,omitempty"`
	Control       *ControlMessage        `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC) Reset() {
	*x = RPC{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{0}
}

func (x *RPC) GetSubscriptions() []*SubOpts {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *RPC) GetPublish() []*Message {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *RPC) GetControl() *ControlMessage {
	if x != nil {
		return x.Control
	}
	return nil
}

// SubOpts 订阅选项
type SubOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribe     bool                   `protobuf:"varint,1,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	TopicId       string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubOpts) Reset() {
	*x = SubOpts{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubOpts) ProtoMessage() {}

func (x *SubOpts) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubOpts.ProtoReflect.Descriptor instead.
func (*SubOpts) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{1}
}

func (x *SubOpts) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *SubOpts) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// Message 消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Seqno         []byte                 `protobuf:"bytes,3,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Key           []byte                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetSeqno() []byte {
	if x != nil {
		return x.Seqno
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// ControlMessage 控制消息
type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ihave         []*ControlIHave        `protobuf:"bytes,1,rep,name=ihave,proto3" json:"ihave,omitempty"`
	Iwant         []*ControlIWant        `protobuf:"bytes,2,rep,name=iwant,proto3" json:"iwant,omitempty"`
	Graft         []*ControlGraft        `protobuf:"bytes,3,rep,name=graft,proto3" json:"graft,omitempty"`
	Prune         []*ControlPrune        `protobuf:"bytes,4,rep,name=prune,proto3" json:"prune,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetIhave() []*ControlIHave {
	if x != nil {
		return x.Ihave
	}
	return nil
}

func (x *ControlMessage) GetIwant() []*ControlIWant {
	if x != nil {
		return x.Iwant
	}
	return nil
}

func (x *ControlMessage) GetGraft() []*ControlGraft {
	if x != nil {
		return x.Graft
	}
	return nil
}

func (x *ControlMessage) GetPrune() []*ControlPrune {
	if x != nil {
		return x.Prune
	}
	return nil
}

// ControlIHave IHAVE 消息
type ControlIHave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageIds    [][]byte               `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlIHave) Reset() {
	*x = ControlIHave{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlIHave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlIHave) ProtoMessage() {}

func (x *ControlIHave) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlIHave.ProtoReflect.Descriptor instead.
func (*ControlIHave) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{4}
}

func (x *ControlIHave) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *ControlIHave) GetMessageIds() [][]byte {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// ControlIWant IWANT 消息
type ControlIWant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    [][]byte               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlIWant) Reset() {
	*x = ControlIWant{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlIWant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlIWant) ProtoMessage() {}

func (x *ControlIWant) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlIWant.ProtoReflect.Descriptor instead.
func (*ControlIWant) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{5}
}

func (x *ControlIWant) GetMessageIds() [][]byte {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// ControlGraft GRAFT 消息
type ControlGraft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlGraft) Reset() {
	*x = ControlGraft{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlGraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlGraft) ProtoMessage() {}

func (x *ControlGraft) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlGraft.ProtoReflect.Descriptor instead.
func (*ControlGraft) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{6}
}

func (x *ControlGraft) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// ControlPrune PRUNE 消息
type ControlPrune struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Peers         []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Backoff       uint64                 `protobuf:"varint,3,opt,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPrune) Reset() {
	*x = ControlPrune{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPrune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPrune) ProtoMessage() {}

func (x *ControlPrune) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPrune.ProtoReflect.Descriptor instead.
func (*ControlPrune) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{7}
}

func (x *ControlPrune) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *ControlPrune) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ControlPrune) GetBackoff() uint64 {
	if x != nil {
		return x.Backoff
	}
	return 0
}

// PeerInfo 节点信息
type PeerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerId           []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SignedPeerRecord []byte                 `protobuf:"bytes,2,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{8}
}

func (x *PeerInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerInfo) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

// TopicDescriptor 主题描述
type TopicDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Auth          *AuthOpts              `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Enc           *EncOpts               `protobuf:"bytes,3,opt,name=enc,proto3" json:"enc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicDescriptor) Reset() {
	*x = TopicDescriptor{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicDescriptor) ProtoMessage() {}

func (x *TopicDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicDescriptor.ProtoReflect.Descriptor instead.
func (*TopicDescriptor) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{9}
}

func (x *TopicDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicDescriptor) GetAuth() *AuthOpts {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *TopicDescriptor) GetEnc() *EncOpts {
	if x != nil {
		return x.Enc
	}
	return nil
}

// AuthOpts 认证选项
type AuthOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          AuthOpts_AuthMode      `protobuf:"varint,1,opt,name=mode,proto3,enum=dep2p.gossipsub.AuthOpts_AuthMode" json:"mode,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOpts) Reset() {
	*x = AuthOpts{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOpts) ProtoMessage() {}

func (x *AuthOpts) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOpts.ProtoReflect.Descriptor instead.
func (*AuthOpts) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{10}
}

func (x *AuthOpts) GetMode() AuthOpts_AuthMode {
	if x != nil {
		return x.Mode
	}
	return AuthOpts_NONE
}

func (x *AuthOpts) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// EncOpts 加密选项
type EncOpts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          EncOpts_EncMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=dep2p.gossipsub.EncOpts_EncMode" json:"mode,omitempty"`
	KeyHashes     [][]byte               `protobuf:"bytes,2,rep,name=key_hashes,json=keyHashes,proto3" json:"key_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncOpts) Reset() {
	*x = EncOpts{}
	mi := &file_gossipsub_gossipsub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncOpts) ProtoMessage() {}

func (x *EncOpts) ProtoReflect() protoreflect.Message {
	mi := &file_gossipsub_gossipsub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncOpts.ProtoReflect.Descriptor instead.
func (*EncOpts) Descriptor() ([]byte, []int) {
	return file_gossipsub_gossipsub_proto_rawDescGZIP(), []int{11}
}

func (x *EncOpts) GetMode() EncOpts_EncMode {
	if x != nil {
		return x.Mode
	}
	return EncOpts_NONE
}

func (x *EncOpts) GetKeyHashes() [][]byte {
	if x != nil {
		return x.KeyHashes
	}
	return nil
}

var File_gossipsub_gossipsub_proto protoreflect.FileDescriptor

const file_gossipsub_gossipsub_proto_rawDesc = "" +
	"\n" +
	"\x19gossipsub/gossipsub.proto\x12\x0fdep2p.gossipsub\"\xb4\x01\n" +
	"\x03RPC\x12>\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x18.dep2p.gossipsub.SubOptsR\rsubscriptions\x122\n" +
	"\apublish\x18\x02 \x03(\v2\x18.dep2p.gossipsub.MessageR\apublish\x129\n" +
	"\acontrol\x18\x03 \x01(\v2\x1f.dep2p.gossipsub.ControlMessageR\acontrol\"B\n" +
	"\aSubOpts\x12\x1c\n" +
	"\tsubscribe\x18\x01 \x01(\bR\tsubscribe\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\"\x8d\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\fR\x05seqno\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x10\n" +
	"\x03key\x18\x06 \x01(\fR\x03key\"\xe4\x01\n" +
	"\x0eControlMessage\x123\n" +
	"\x05ihave\x18\x01 \x03(\v2\x1d.dep2p.gossipsub.ControlIHaveR\x05ihave\x123\n" +
	"\x05iwant\x18\x02 \x03(\v2\x1d.dep2p.gossipsub.ControlIWantR\x05iwant\x123\n" +
	"\x05graft\x18\x03 \x03(\v2\x1d.dep2p.gossipsub.ControlGraftR\x05graft\x123\n" +
	"\x05prune\x18\x04 \x03(\v2\x1d.dep2p.gossipsub.ControlPruneR\x05prune\"J\n" +
	"\fControlIHave\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\fR\n" +
	"messageIds\"/\n" +
	"\fControlIWant\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\fR\n" +
	"messageIds\")\n" +
	"\fControlGraft\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"t\n" +
	"\fControlPrune\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12/\n" +
	"\x05peers\x18\x02 \x03(\v2\x19.dep2p.gossipsub.PeerInfoR\x05peers\x12\x18\n" +
	"\abackoff\x18\x03 \x01(\x04R\abackoff\"Q\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12,\n" +
	"\x12signed_peer_record\x18\x02 \x01(\fR\x10signedPeerRecord\"\x80\x01\n" +
	"\x0fTopicDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04auth\x18\x02 \x01(\v2\x19.dep2p.gossipsub.AuthOptsR\x04auth\x12*\n" +
	"\x03enc\x18\x03 \x01(\v2\x18.dep2p.gossipsub.EncOptsR\x03enc\"~\n" +
	"\bAuthOpts\x126\n" +
	"\x04mode\x18\x01 \x01(\x0e2\".dep2p.gossipsub.AuthOpts.AuthModeR\x04mode\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"&\n" +
	"\bAuthMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03KEY\x10\x01\x12\a\n" +
	"\x03WOT\x10\x02\"\x8b\x01\n" +
	"\aEncOpts\x124\n" +
	"\x04mode\x18\x01 \x01(\x0e2 .dep2p.gossipsub.EncOpts.EncModeR\x04mode\x12\x1d\n" +
	"\n" +
	"key_hashes\x18\x02 \x03(\fR\tkeyHashes\"+\n" +
	"\aEncMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tSHAREDKEY\x10\x01\x12\a\n" +
	"\x03WOT\x10\x02B,Z*github.com/dep2p/dep2p/pkg/proto/gossipsubb\x06proto3"

var (
	file_gossipsub_gossipsub_proto_rawDescOnce sync.Once
	file_gossipsub_gossipsub_proto_rawDescData []byte
)

func file_gossipsub_gossipsub_proto_rawDescGZIP() []byte {
	file_gossipsub_gossipsub_proto_rawDescOnce.Do(func() {
		file_gossipsub_gossipsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossipsub_gossipsub_proto_rawDesc), len(file_gossipsub_gossipsub_proto_rawDesc)))
	})
	return file_gossipsub_gossipsub_proto_rawDescData
}

var file_gossipsub_gossipsub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gossipsub_gossipsub_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gossipsub_gossipsub_proto_goTypes = []any{
	(AuthOpts_AuthMode)(0),  // 0: dep2p.gossipsub.AuthOpts.AuthMode
	(EncOpts_EncMode)(0),    // 1: dep2p.gossipsub.EncOpts.EncMode
	(*RPC)(nil),             // 2: dep2p.gossipsub.RPC
	(*SubOpts)(nil),         // 3: dep2p.gossipsub.SubOpts
	(*Message)(nil),         // 4: dep2p.gossipsub.Message
	(*ControlMessage)(nil),  // 5: dep2p.gossipsub.ControlMessage
	(*ControlIHave)(nil),    // 6: dep2p.gossipsub.ControlIHave
	(*ControlIWant)(nil),    // 7: dep2p.gossipsub.ControlIWant
	(*ControlGraft)(nil),    // 8: dep2p.gossipsub.ControlGraft
	(*ControlPrune)(nil),    // 9: dep2p.gossipsub.ControlPrune
	(*PeerInfo)(nil),        // 10: dep2p.gossipsub.PeerInfo
	(*TopicDescriptor)(nil), // 11: dep2p.gossipsub.TopicDescriptor
	(*AuthOpts)(nil),        // 12: dep2p.gossipsub.AuthOpts
	(*EncOpts)(nil),         // 13: dep2p.gossipsub.EncOpts
}
var file_gossipsub_gossipsub_proto_depIdxs = []int32{
	3,  // 0: dep2p.gossipsub.RPC.subscriptions:type_name -> dep2p.gossipsub.SubOpts
	4,  // 1: dep2p.gossipsub.RPC.publish:type_name -> dep2p.gossipsub.Message
	5,  // 2: dep2p.gossipsub.RPC.control:type_name -> dep2p.gossipsub.ControlMessage
	6,  // 3: dep2p.gossipsub.ControlMessage.ihave:type_name -> dep2p.gossipsub.ControlIHave
	7,  // 4: dep2p.gossipsub.ControlMessage.iwant:type_name -> dep2p.gossipsub.ControlIWant
	8,  // 5: dep2p.gossipsub.ControlMessage.graft:type_name -> dep2p.gossipsub.ControlGraft
	9,  // 6: dep2p.gossipsub.ControlMessage.prune:type_name -> dep2p.gossipsub.ControlPrune
	10, // 7: dep2p.gossipsub.ControlPrune.peers:type_name -> dep2p.gossipsub.PeerInfo
	12, // 8: dep2p.gossipsub.TopicDescriptor.auth:type_name -> dep2p.gossipsub.AuthOpts
	13, // 9: dep2p.gossipsub.TopicDescriptor.enc:type_name -> dep2p.gossipsub.EncOpts
	0,  // 10: dep2p.gossipsub.AuthOpts.mode:type_name -> dep2p.gossipsub.AuthOpts.AuthMode
	1,  // 11: dep2p.gossipsub.EncOpts.mode:type_name -> dep2p.gossipsub.EncOpts.EncMode
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gossipsub_gossipsub_proto_init() }
func file_gossipsub_gossipsub_proto_init() {
	if File_gossipsub_gossipsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossipsub_gossipsub_proto_rawDesc), len(file_gossipsub_gossipsub_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossipsub_gossipsub_proto_goTypes,
		DependencyIndexes: file_gossipsub_gossipsub_proto_depIdxs,
		EnumInfos:         file_gossipsub_gossipsub_proto_enumTypes,
		MessageInfos:      file_gossipsub_gossipsub_proto_msgTypes,
	}.Build()
	File_gossipsub_gossipsub_proto = out.File
	file_gossipsub_gossipsub_proto_goTypes = nil
	file_gossipsub_gossipsub_proto_depIdxs = nil
}
