// DeP2P AutoNAT Protocol Definitions
// 自动 NAT 类型检测协议消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: autonat/autonat.proto

package autonat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
type MessageType int32

const (
	MessageType_DIAL          MessageType = 0
	MessageType_DIAL_RESPONSE MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "DIAL",
		1: "DIAL_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"DIAL":          0,
		"DIAL_RESPONSE": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_autonat_autonat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_autonat_autonat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{0}
}

// ResponseStatus 响应状态
type ResponseStatus int32

const (
	ResponseStatus_OK               ResponseStatus = 0
	ResponseStatus_E_DIAL_ERROR     ResponseStatus = 100
	ResponseStatus_E_DIAL_REFUSED   ResponseStatus = 101
	ResponseStatus_E_BAD_REQUEST    ResponseStatus = 200
	ResponseStatus_E_INTERNAL_ERROR ResponseStatus = 300
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0:   "OK",
		100: "E_DIAL_ERROR",
		101: "E_DIAL_REFUSED",
		200: "E_BAD_REQUEST",
		300: "E_INTERNAL_ERROR",
	}
	ResponseStatus_value = map[string]int32{
		"OK":               0,
		"E_DIAL_ERROR":     100,
		"E_DIAL_REFUSED":   101,
		"E_BAD_REQUEST":    200,
		"E_INTERNAL_ERROR": 300,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_autonat_autonat_proto_enumTypes[1].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_autonat_autonat_proto_enumTypes[1]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{1}
}

// PeerInfo 节点信息
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_autonat_autonat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_autonat_autonat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PeerInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// Dial 拨号请求
type Dial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dial) Reset() {
	*x = Dial{}
	mi := &file_autonat_autonat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dial) ProtoMessage() {}

func (x *Dial) ProtoReflect() protoreflect.Message {
	mi := &file_autonat_autonat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dial.ProtoReflect.Descriptor instead.
func (*Dial) Descriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{1}
}

func (x *Dial) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

// DialResponse 拨号响应
type DialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=dep2p.autonat.ResponseStatus" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	Addr          []byte                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	mi := &file_autonat_autonat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autonat_autonat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{2}
}

func (x *DialResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_OK
}

func (x *DialResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *DialResponse) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

// Message AutoNAT 协议消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.autonat.MessageType" json:"type,omitempty"`
	Dial          *Dial                  `protobuf:"bytes,2,opt,name=dial,proto3" json:"dial,omitempty"`
	DialResponse  *DialResponse          `protobuf:"bytes,3,opt,name=dial_response,json=dialResponse,proto3" json:"dial_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_autonat_autonat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_autonat_autonat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_autonat_autonat_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_DIAL
}

func (x *Message) GetDial() *Dial {
	if x != nil {
		return x.Dial
	}
	return nil
}

func (x *Message) GetDialResponse() *DialResponse {
	if x != nil {
		return x.DialResponse
	}
	return nil
}

var File_autonat_autonat_proto protoreflect.FileDescriptor

const file_autonat_autonat_proto_rawDesc = "" +
	"\n" +
	"\x15autonat/autonat.proto\x12\rdep2p.autonat\"0\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\"3\n" +
	"\x04Dial\x12+\n" +
	"\x04peer\x18\x01 \x01(\v2\x17.dep2p.autonat.PeerInfoR\x04peer\"z\n" +
	"\fDialResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.dep2p.autonat.ResponseStatusR\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\fR\x04addr\"\xa4\x01\n" +
	"\aMessage\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.dep2p.autonat.MessageTypeR\x04type\x12'\n" +
	"\x04dial\x18\x02 \x01(\v2\x13.dep2p.autonat.DialR\x04dial\x12@\n" +
	"\rdial_response\x18\x03 \x01(\v2\x1b.dep2p.autonat.DialResponseR\fdialResponse**\n" +
	"\vMessageType\x12\b\n" +
	"\x04DIAL\x10\x00\x12\x11\n" +
	"\rDIAL_RESPONSE\x10\x01*i\n" +
	"\x0eResponseStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fE_DIAL_ERROR\x10d\x12\x12\n" +
	"\x0eE_DIAL_REFUSED\x10e\x12\x12\n" +
	"\rE_BAD_REQUEST\x10\xc8\x01\x12\x15\n" +
	"\x10E_INTERNAL_ERROR\x10\xac\x02B*Z(github.com/dep2p/dep2p/pkg/proto/autonatb\x06proto3"

var (
	file_autonat_autonat_proto_rawDescOnce sync.Once
	file_autonat_autonat_proto_rawDescData []byte
)

func file_autonat_autonat_proto_rawDescGZIP() []byte {
	file_autonat_autonat_proto_rawDescOnce.Do(func() {
		file_autonat_autonat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autonat_autonat_proto_rawDesc), len(file_autonat_autonat_proto_rawDesc)))
	})
	return file_autonat_autonat_proto_rawDescData
}

var file_autonat_autonat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_autonat_autonat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_autonat_autonat_proto_goTypes = []any{
	(MessageType)(0),     // 0: dep2p.autonat.MessageType
	(ResponseStatus)(0),  // 1: dep2p.autonat.ResponseStatus
	(*PeerInfo)(nil),     // 2: dep2p.autonat.PeerInfo
	(*Dial)(nil),         // 3: dep2p.autonat.Dial
	(*DialResponse)(nil), // 4: dep2p.autonat.DialResponse
	(*Message)(nil),      // 5: dep2p.autonat.Message
}
var file_autonat_autonat_proto_depIdxs = []int32{
	2, // 0: dep2p.autonat.Dial.peer:type_name -> dep2p.autonat.PeerInfo
	1, // 1: dep2p.autonat.DialResponse.status:type_name -> dep2p.autonat.ResponseStatus
	0, // 2: dep2p.autonat.Message.type:type_name -> dep2p.autonat.MessageType
	3, // 3: dep2p.autonat.Message.dial:type_name -> dep2p.autonat.Dial
	4, // 4: dep2p.autonat.Message.dial_response:type_name -> dep2p.autonat.DialResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_autonat_autonat_proto_init() }
func file_autonat_autonat_proto_init() {
	if File_autonat_autonat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autonat_autonat_proto_rawDesc), len(file_autonat_autonat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_autonat_autonat_proto_goTypes,
		DependencyIndexes: file_autonat_autonat_proto_depIdxs,
		EnumInfos:         file_autonat_autonat_proto_enumTypes,
		MessageInfos:      file_autonat_autonat_proto_msgTypes,
	}.Build()
	File_autonat_autonat_proto = out.File
	file_autonat_autonat_proto_goTypes = nil
	file_autonat_autonat_proto_depIdxs = nil
}
