// DeP2P Relay Protocol Definitions
// 中继协议消息定义（Circuit Relay v2）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: relay/relay.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status 状态码
type Status int32

const (
	Status_UNUSED                  Status = 0   // 未使用（proto3 兼容）
	Status_OK                      Status = 100 // 成功
	Status_RESERVATION_REFUSED     Status = 200 // 预留被拒绝
	Status_RESOURCE_LIMIT_EXCEEDED Status = 201 // 资源限制超出
	Status_PERMISSION_DENIED       Status = 202 // 权限拒绝
	Status_CONNECTION_FAILED       Status = 203 // 连接失败
	Status_NO_RESERVATION          Status = 204 // 无预留
	Status_MALFORMED_MESSAGE       Status = 400 // 消息格式错误
	Status_UNEXPECTED_MESSAGE      Status = 401 // 意外的消息
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:   "UNUSED",
		100: "OK",
		200: "RESERVATION_REFUSED",
		201: "RESOURCE_LIMIT_EXCEEDED",
		202: "PERMISSION_DENIED",
		203: "CONNECTION_FAILED",
		204: "NO_RESERVATION",
		400: "MALFORMED_MESSAGE",
		401: "UNEXPECTED_MESSAGE",
	}
	Status_value = map[string]int32{
		"UNUSED":                  0,
		"OK":                      100,
		"RESERVATION_REFUSED":     200,
		"RESOURCE_LIMIT_EXCEEDED": 201,
		"PERMISSION_DENIED":       202,
		"CONNECTION_FAILED":       203,
		"NO_RESERVATION":          204,
		"MALFORMED_MESSAGE":       400,
		"UNEXPECTED_MESSAGE":      401,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_relay_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_relay_relay_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{0}
}

type HopMessage_Type int32

const (
	HopMessage_RESERVE HopMessage_Type = 0 // 预留请求
	HopMessage_CONNECT HopMessage_Type = 1 // 连接请求
	HopMessage_STATUS  HopMessage_Type = 2 // 状态响应
)

// Enum value maps for HopMessage_Type.
var (
	HopMessage_Type_name = map[int32]string{
		0: "RESERVE",
		1: "CONNECT",
		2: "STATUS",
	}
	HopMessage_Type_value = map[string]int32{
		"RESERVE": 0,
		"CONNECT": 1,
		"STATUS":  2,
	}
)

func (x HopMessage_Type) Enum() *HopMessage_Type {
	p := new(HopMessage_Type)
	*p = x
	return p
}

func (x HopMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HopMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_relay_proto_enumTypes[1].Descriptor()
}

func (HopMessage_Type) Type() protoreflect.EnumType {
	return &file_relay_relay_proto_enumTypes[1]
}

func (x HopMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HopMessage_Type.Descriptor instead.
func (HopMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{0, 0}
}

type StopMessage_Type int32

const (
	StopMessage_CONNECT StopMessage_Type = 0 // 连接请求
	StopMessage_STATUS  StopMessage_Type = 1 // 状态响应
)

// Enum value maps for StopMessage_Type.
var (
	StopMessage_Type_name = map[int32]string{
		0: "CONNECT",
		1: "STATUS",
	}
	StopMessage_Type_value = map[string]int32{
		"CONNECT": 0,
		"STATUS":  1,
	}
)

func (x StopMessage_Type) Enum() *StopMessage_Type {
	p := new(StopMessage_Type)
	*p = x
	return p
}

func (x StopMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_relay_proto_enumTypes[2].Descriptor()
}

func (StopMessage_Type) Type() protoreflect.EnumType {
	return &file_relay_relay_proto_enumTypes[2]
}

func (x StopMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopMessage_Type.Descriptor instead.
func (StopMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{1, 0}
}

// HopMessage 中继跳消息（relay 端）
type HopMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HopMessage_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.relay.HopMessage_Type" json:"type,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Reservation   *Reservation           `protobuf:"bytes,3,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Limit         *Limit                 `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=dep2p.relay.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HopMessage) Reset() {
	*x = HopMessage{}
	mi := &file_relay_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopMessage) ProtoMessage() {}

func (x *HopMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopMessage.ProtoReflect.Descriptor instead.
func (*HopMessage) Descriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{0}
}

func (x *HopMessage) GetType() HopMessage_Type {
	if x != nil {
		return x.Type
	}
	return HopMessage_RESERVE
}

func (x *HopMessage) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *HopMessage) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *HopMessage) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *HopMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNUSED
}

// StopMessage 停止消息（客户端）
type StopMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StopMessage_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=dep2p.relay.StopMessage_Type" json:"type,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Limit         *Limit                 `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=dep2p.relay.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMessage) Reset() {
	*x = StopMessage{}
	mi := &file_relay_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMessage) ProtoMessage() {}

func (x *StopMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMessage.ProtoReflect.Descriptor instead.
func (*StopMessage) Descriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{1}
}

func (x *StopMessage) GetType() StopMessage_Type {
	if x != nil {
		return x.Type
	}
	return StopMessage_CONNECT
}

func (x *StopMessage) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *StopMessage) GetLimit() *Limit {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *StopMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNUSED
}

// Peer 节点信息
type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_relay_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_relay_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Peer) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// Reservation 预留信息
type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expire        uint64                 `protobuf:"varint,1,opt,name=expire,proto3" json:"expire,omitempty"`  // Unix 过期时间（UTC）
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`     // 中继地址
	Voucher       []byte                 `protobuf:"bytes,3,opt,name=voucher,proto3" json:"voucher,omitempty"` // 预留凭证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_relay_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_relay_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{3}
}

func (x *Reservation) GetExpire() uint64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *Reservation) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Reservation) GetVoucher() []byte {
	if x != nil {
		return x.Voucher
	}
	return nil
}

// Limit 限制信息
type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      uint32                 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"` // 持续时间（秒）
	Data          uint64                 `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`         // 数据量（字节）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_relay_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_relay_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_relay_relay_proto_rawDescGZIP(), []int{4}
}

func (x *Limit) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Limit) GetData() uint64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_relay_relay_proto protoreflect.FileDescriptor

const file_relay_relay_proto_rawDesc = "" +
	"\n" +
	"\x11relay/relay.proto\x12\vdep2p.relay\"\xa6\x02\n" +
	"\n" +
	"HopMessage\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.dep2p.relay.HopMessage.TypeR\x04type\x12%\n" +
	"\x04peer\x18\x02 \x01(\v2\x11.dep2p.relay.PeerR\x04peer\x12:\n" +
	"\vreservation\x18\x03 \x01(\v2\x18.dep2p.relay.ReservationR\vreservation\x12(\n" +
	"\x05limit\x18\x04 \x01(\v2\x12.dep2p.relay.LimitR\x05limit\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.dep2p.relay.StatusR\x06status\",\n" +
	"\x04Type\x12\v\n" +
	"\aRESERVE\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x02\"\xdf\x01\n" +
	"\vStopMessage\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.dep2p.relay.StopMessage.TypeR\x04type\x12%\n" +
	"\x04peer\x18\x02 \x01(\v2\x11.dep2p.relay.PeerR\x04peer\x12(\n" +
	"\x05limit\x18\x03 \x01(\v2\x12.dep2p.relay.LimitR\x05limit\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.dep2p.relay.StatusR\x06status\"\x1f\n" +
	"\x04Type\x12\v\n" +
	"\aCONNECT\x10\x00\x12\n" +
	"\n" +
	"\x06STATUS\x10\x01\",\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\"U\n" +
	"\vReservation\x12\x16\n" +
	"\x06expire\x18\x01 \x01(\x04R\x06expire\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x12\x18\n" +
	"\avoucher\x18\x03 \x01(\fR\avoucher\"7\n" +
	"\x05Limit\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\rR\bduration\x12\x12\n" +
	"\x04data\x18\x02 \x01(\x04R\x04data*\xca\x01\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x00\x12\x06\n" +
	"\x02OK\x10d\x12\x18\n" +
	"\x13RESERVATION_REFUSED\x10\xc8\x01\x12\x1c\n" +
	"\x17RESOURCE_LIMIT_EXCEEDED\x10\xc9\x01\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\xca\x01\x12\x16\n" +
	"\x11CONNECTION_FAILED\x10\xcb\x01\x12\x13\n" +
	"\x0eNO_RESERVATION\x10\xcc\x01\x12\x16\n" +
	"\x11MALFORMED_MESSAGE\x10\x90\x03\x12\x17\n" +
	"\x12UNEXPECTED_MESSAGE\x10\x91\x03B(Z&github.com/dep2p/dep2p/pkg/proto/relayb\x06proto3"

var (
	file_relay_relay_proto_rawDescOnce sync.Once
	file_relay_relay_proto_rawDescData []byte
)

func file_relay_relay_proto_rawDescGZIP() []byte {
	file_relay_relay_proto_rawDescOnce.Do(func() {
		file_relay_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_relay_proto_rawDesc), len(file_relay_relay_proto_rawDesc)))
	})
	return file_relay_relay_proto_rawDescData
}

var file_relay_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_relay_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relay_relay_proto_goTypes = []any{
	(Status)(0),           // 0: dep2p.relay.Status
	(HopMessage_Type)(0),  // 1: dep2p.relay.HopMessage.Type
	(StopMessage_Type)(0), // 2: dep2p.relay.StopMessage.Type
	(*HopMessage)(nil),    // 3: dep2p.relay.HopMessage
	(*StopMessage)(nil),   // 4: dep2p.relay.StopMessage
	(*Peer)(nil),          // 5: dep2p.relay.Peer
	(*Reservation)(nil),   // 6: dep2p.relay.Reservation
	(*Limit)(nil),         // 7: dep2p.relay.Limit
}
var file_relay_relay_proto_depIdxs = []int32{
	1, // 0: dep2p.relay.HopMessage.type:type_name -> dep2p.relay.HopMessage.Type
	5, // 1: dep2p.relay.HopMessage.peer:type_name -> dep2p.relay.Peer
	6, // 2: dep2p.relay.HopMessage.reservation:type_name -> dep2p.relay.Reservation
	7, // 3: dep2p.relay.HopMessage.limit:type_name -> dep2p.relay.Limit
	0, // 4: dep2p.relay.HopMessage.status:type_name -> dep2p.relay.Status
	2, // 5: dep2p.relay.StopMessage.type:type_name -> dep2p.relay.StopMessage.Type
	5, // 6: dep2p.relay.StopMessage.peer:type_name -> dep2p.relay.Peer
	7, // 7: dep2p.relay.StopMessage.limit:type_name -> dep2p.relay.Limit
	0, // 8: dep2p.relay.StopMessage.status:type_name -> dep2p.relay.Status
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_relay_relay_proto_init() }
func file_relay_relay_proto_init() {
	if File_relay_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_relay_proto_rawDesc), len(file_relay_relay_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_relay_proto_goTypes,
		DependencyIndexes: file_relay_relay_proto_depIdxs,
		EnumInfos:         file_relay_relay_proto_enumTypes,
		MessageInfos:      file_relay_relay_proto_msgTypes,
	}.Build()
	File_relay_relay_proto = out.File
	file_relay_relay_proto_goTypes = nil
	file_relay_relay_proto_depIdxs = nil
}
