// DeP2P Relay Voucher Definitions
// 中继凭证消息定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: relay/voucher.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReservationVoucher 预留凭证
type ReservationVoucher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relay         []byte                 `protobuf:"bytes,1,opt,name=relay,proto3" json:"relay,omitempty"`            // 中继节点 ID
	Peer          []byte                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`              // 预留者节点 ID
	Expiration    uint64                 `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"` // 过期时间（Unix 时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationVoucher) Reset() {
	*x = ReservationVoucher{}
	mi := &file_relay_voucher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationVoucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationVoucher) ProtoMessage() {}

func (x *ReservationVoucher) ProtoReflect() protoreflect.Message {
	mi := &file_relay_voucher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationVoucher.ProtoReflect.Descriptor instead.
func (*ReservationVoucher) Descriptor() ([]byte, []int) {
	return file_relay_voucher_proto_rawDescGZIP(), []int{0}
}

func (x *ReservationVoucher) GetRelay() []byte {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *ReservationVoucher) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ReservationVoucher) GetExpiration() uint64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

var File_relay_voucher_proto protoreflect.FileDescriptor

const file_relay_voucher_proto_rawDesc = "" +
	"\n" +
	"\x13relay/voucher.proto\x12\vdep2p.relay\"^\n" +
	"\x12ReservationVoucher\x12\x14\n" +
	"\x05relay\x18\x01 \x01(\fR\x05relay\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\fR\x04peer\x12\x1e\n" +
	"\n" +
	"expiration\x18\x03 \x01(\x04R\n" +
	"expirationB(Z&github.com/dep2p/dep2p/pkg/proto/relayb\x06proto3"

var (
	file_relay_voucher_proto_rawDescOnce sync.Once
	file_relay_voucher_proto_rawDescData []byte
)

func file_relay_voucher_proto_rawDescGZIP() []byte {
	file_relay_voucher_proto_rawDescOnce.Do(func() {
		file_relay_voucher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_voucher_proto_rawDesc), len(file_relay_voucher_proto_rawDesc)))
	})
	return file_relay_voucher_proto_rawDescData
}

var file_relay_voucher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relay_voucher_proto_goTypes = []any{
	(*ReservationVoucher)(nil), // 0: dep2p.relay.ReservationVoucher
}
var file_relay_voucher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_voucher_proto_init() }
func file_relay_voucher_proto_init() {
	if File_relay_voucher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_voucher_proto_rawDesc), len(file_relay_voucher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_voucher_proto_goTypes,
		DependencyIndexes: file_relay_voucher_proto_depIdxs,
		MessageInfos:      file_relay_voucher_proto_msgTypes,
	}.Build()
	File_relay_voucher_proto = out.File
	file_relay_voucher_proto_goTypes = nil
	file_relay_voucher_proto_depIdxs = nil
}
