// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: pkg/proto/gossipsub/gossipsub.proto

package gossipsub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthMode 认证模式
type AuthMode int32

const (
	// NONE 无认证
	AuthMode_AUTH_MODE_NONE AuthMode = 0
	// KEY 基于密钥的认证
	AuthMode_AUTH_MODE_KEY AuthMode = 1
	// WOT 信任网络认证
	AuthMode_AUTH_MODE_WOT AuthMode = 2
)

// Enum value maps for AuthMode.
var (
	AuthMode_name = map[int32]string{
		0: "AUTH_MODE_NONE",
		1: "AUTH_MODE_KEY",
		2: "AUTH_MODE_WOT",
	}
	AuthMode_value = map[string]int32{
		"AUTH_MODE_NONE": 0,
		"AUTH_MODE_KEY":  1,
		"AUTH_MODE_WOT":  2,
	}
)

func (x AuthMode) Enum() *AuthMode {
	p := new(AuthMode)
	*p = x
	return p
}

func (x AuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_gossipsub_gossipsub_proto_enumTypes[0].Descriptor()
}

func (AuthMode) Type() protoreflect.EnumType {
	return &file_pkg_proto_gossipsub_gossipsub_proto_enumTypes[0]
}

func (x AuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMode.Descriptor instead.
func (AuthMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{0}
}

// EncMode 加密模式
type EncMode int32

const (
	// NONE 不加密
	EncMode_ENC_MODE_NONE EncMode = 0
	// SHARED_KEY 共享密钥加密
	EncMode_ENC_MODE_SHARED_KEY EncMode = 1
	// WOT 信任网络加密
	EncMode_ENC_MODE_WOT EncMode = 2
)

// Enum value maps for EncMode.
var (
	EncMode_name = map[int32]string{
		0: "ENC_MODE_NONE",
		1: "ENC_MODE_SHARED_KEY",
		2: "ENC_MODE_WOT",
	}
	EncMode_value = map[string]int32{
		"ENC_MODE_NONE":       0,
		"ENC_MODE_SHARED_KEY": 1,
		"ENC_MODE_WOT":        2,
	}
)

func (x EncMode) Enum() *EncMode {
	p := new(EncMode)
	*p = x
	return p
}

func (x EncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_gossipsub_gossipsub_proto_enumTypes[1].Descriptor()
}

func (EncMode) Type() protoreflect.EnumType {
	return &file_pkg_proto_gossipsub_gossipsub_proto_enumTypes[1]
}

func (x EncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncMode.Descriptor instead.
func (EncMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{1}
}

// RPC GossipSub 协议消息
type RPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscriptions 订阅变更列表
	Subscriptions []*SubOpts `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// publish 数据消息列表
	Publish []*Message `protobuf:"bytes,2,rep,name=publish,proto3" json:"publish,omitempty"`
	// control 控制消息
	Control       *ControlMessage `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC) Reset() {
	*x = RPC{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC) ProtoMessage() {}

func (x *RPC) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC.ProtoReflect.Descriptor instead.
func (*RPC) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{0}
}

func (x *RPC) GetSubscriptions() []*SubOpts {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *RPC) GetPublish() []*Message {
	if x != nil {
		return x.Publish
	}
	return nil
}

func (x *RPC) GetControl() *ControlMessage {
	if x != nil {
		return x.Control
	}
	return nil
}

// SubOpts 订阅选项
type SubOpts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscribe true=订阅, false=取消订阅
	Subscribe bool `protobuf:"varint,1,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	// topic 主题
	Topic         string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubOpts) Reset() {
	*x = SubOpts{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubOpts) ProtoMessage() {}

func (x *SubOpts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubOpts.ProtoReflect.Descriptor instead.
func (*SubOpts) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{1}
}

func (x *SubOpts) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *SubOpts) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// Message 发布订阅消息
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from 发送者节点 ID (32字节)
	From []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// data 消息内容
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// seqno 序列号 (8字节, 大端序)
	Seqno []byte `protobuf:"bytes,3,opt,name=seqno,proto3" json:"seqno,omitempty"`
	// topic 主题
	Topic string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	// signature 签名 (可选)
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// key 签名者公钥 (可选)
	Key           []byte `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetSeqno() []byte {
	if x != nil {
		return x.Seqno
	}
	return nil
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// ControlMessage 控制消息
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ihave 通知有消息
	Ihave []*ControlIHave `protobuf:"bytes,1,rep,name=ihave,proto3" json:"ihave,omitempty"`
	// iwant 请求消息
	Iwant []*ControlIWant `protobuf:"bytes,2,rep,name=iwant,proto3" json:"iwant,omitempty"`
	// graft 请求加入 mesh
	Graft []*ControlGraft `protobuf:"bytes,3,rep,name=graft,proto3" json:"graft,omitempty"`
	// prune 移出 mesh
	Prune         []*ControlPrune `protobuf:"bytes,4,rep,name=prune,proto3" json:"prune,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetIhave() []*ControlIHave {
	if x != nil {
		return x.Ihave
	}
	return nil
}

func (x *ControlMessage) GetIwant() []*ControlIWant {
	if x != nil {
		return x.Iwant
	}
	return nil
}

func (x *ControlMessage) GetGraft() []*ControlGraft {
	if x != nil {
		return x.Graft
	}
	return nil
}

func (x *ControlMessage) GetPrune() []*ControlPrune {
	if x != nil {
		return x.Prune
	}
	return nil
}

// ControlIHave IHAVE 消息 - 通知 peer 本节点拥有的消息
type ControlIHave struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic 主题
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// message_ids 消息 ID 列表
	MessageIds    [][]byte `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlIHave) Reset() {
	*x = ControlIHave{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlIHave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlIHave) ProtoMessage() {}

func (x *ControlIHave) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlIHave.ProtoReflect.Descriptor instead.
func (*ControlIHave) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{4}
}

func (x *ControlIHave) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ControlIHave) GetMessageIds() [][]byte {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// ControlIWant IWANT 消息 - 请求 peer 发送指定消息
type ControlIWant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_ids 请求的消息 ID 列表
	MessageIds    [][]byte `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlIWant) Reset() {
	*x = ControlIWant{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlIWant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlIWant) ProtoMessage() {}

func (x *ControlIWant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlIWant.ProtoReflect.Descriptor instead.
func (*ControlIWant) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{5}
}

func (x *ControlIWant) GetMessageIds() [][]byte {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// ControlGraft GRAFT 消息 - 请求加入 mesh
type ControlGraft struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic 主题
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlGraft) Reset() {
	*x = ControlGraft{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlGraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlGraft) ProtoMessage() {}

func (x *ControlGraft) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlGraft.ProtoReflect.Descriptor instead.
func (*ControlGraft) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{6}
}

func (x *ControlGraft) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// ControlPrune PRUNE 消息 - 从 mesh 移除
type ControlPrune struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic 主题
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// peers 推荐的其他 peers（PX - Peer Exchange）
	Peers []*PeerInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	// backoff 退避时间（秒）
	Backoff       uint64 `protobuf:"varint,3,opt,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPrune) Reset() {
	*x = ControlPrune{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPrune) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPrune) ProtoMessage() {}

func (x *ControlPrune) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPrune.ProtoReflect.Descriptor instead.
func (*ControlPrune) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{7}
}

func (x *ControlPrune) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ControlPrune) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ControlPrune) GetBackoff() uint64 {
	if x != nil {
		return x.Backoff
	}
	return 0
}

// PeerInfo Peer 信息（用于 PX）
type PeerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peer_id 节点 ID (32字节)
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// signed_peer_record 签名的 peer 记录（可选）
	SignedPeerRecord []byte `protobuf:"bytes,2,opt,name=signed_peer_record,json=signedPeerRecord,proto3" json:"signed_peer_record,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{8}
}

func (x *PeerInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerInfo) GetSignedPeerRecord() []byte {
	if x != nil {
		return x.SignedPeerRecord
	}
	return nil
}

// TopicDescriptor 主题描述符
type TopicDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 主题名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// auth 认证配置
	Auth *AuthOpts `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	// enc 加密配置
	Enc           *EncOpts `protobuf:"bytes,3,opt,name=enc,proto3" json:"enc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicDescriptor) Reset() {
	*x = TopicDescriptor{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicDescriptor) ProtoMessage() {}

func (x *TopicDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicDescriptor.ProtoReflect.Descriptor instead.
func (*TopicDescriptor) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{9}
}

func (x *TopicDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicDescriptor) GetAuth() *AuthOpts {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *TopicDescriptor) GetEnc() *EncOpts {
	if x != nil {
		return x.Enc
	}
	return nil
}

// AuthOpts 认证选项
type AuthOpts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode 认证模式
	Mode AuthMode `protobuf:"varint,1,opt,name=mode,proto3,enum=dep2p.gossipsub.AuthMode" json:"mode,omitempty"`
	// keys 授权的公钥列表
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOpts) Reset() {
	*x = AuthOpts{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOpts) ProtoMessage() {}

func (x *AuthOpts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOpts.ProtoReflect.Descriptor instead.
func (*AuthOpts) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{10}
}

func (x *AuthOpts) GetMode() AuthMode {
	if x != nil {
		return x.Mode
	}
	return AuthMode_AUTH_MODE_NONE
}

func (x *AuthOpts) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// EncOpts 加密选项
type EncOpts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode 加密模式
	Mode EncMode `protobuf:"varint,1,opt,name=mode,proto3,enum=dep2p.gossipsub.EncMode" json:"mode,omitempty"`
	// key_hashes 密钥哈希列表
	KeyHashes     [][]byte `protobuf:"bytes,2,rep,name=key_hashes,json=keyHashes,proto3" json:"key_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncOpts) Reset() {
	*x = EncOpts{}
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncOpts) ProtoMessage() {}

func (x *EncOpts) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gossipsub_gossipsub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncOpts.ProtoReflect.Descriptor instead.
func (*EncOpts) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP(), []int{11}
}

func (x *EncOpts) GetMode() EncMode {
	if x != nil {
		return x.Mode
	}
	return EncMode_ENC_MODE_NONE
}

func (x *EncOpts) GetKeyHashes() [][]byte {
	if x != nil {
		return x.KeyHashes
	}
	return nil
}

var File_pkg_proto_gossipsub_gossipsub_proto protoreflect.FileDescriptor

const file_pkg_proto_gossipsub_gossipsub_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/gossipsub/gossipsub.proto\x12\x0fdep2p.gossipsub\"\xb4\x01\n" +
	"\x03RPC\x12>\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x18.dep2p.gossipsub.SubOptsR\rsubscriptions\x122\n" +
	"\apublish\x18\x02 \x03(\v2\x18.dep2p.gossipsub.MessageR\apublish\x129\n" +
	"\acontrol\x18\x03 \x01(\v2\x1f.dep2p.gossipsub.ControlMessageR\acontrol\"=\n" +
	"\aSubOpts\x12\x1c\n" +
	"\tsubscribe\x18\x01 \x01(\bR\tsubscribe\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x8d\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\fR\x05seqno\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x10\n" +
	"\x03key\x18\x06 \x01(\fR\x03key\"\xe4\x01\n" +
	"\x0eControlMessage\x123\n" +
	"\x05ihave\x18\x01 \x03(\v2\x1d.dep2p.gossipsub.ControlIHaveR\x05ihave\x123\n" +
	"\x05iwant\x18\x02 \x03(\v2\x1d.dep2p.gossipsub.ControlIWantR\x05iwant\x123\n" +
	"\x05graft\x18\x03 \x03(\v2\x1d.dep2p.gossipsub.ControlGraftR\x05graft\x123\n" +
	"\x05prune\x18\x04 \x03(\v2\x1d.dep2p.gossipsub.ControlPruneR\x05prune\"E\n" +
	"\fControlIHave\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\fR\n" +
	"messageIds\"/\n" +
	"\fControlIWant\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\fR\n" +
	"messageIds\"$\n" +
	"\fControlGraft\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"o\n" +
	"\fControlPrune\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12/\n" +
	"\x05peers\x18\x02 \x03(\v2\x19.dep2p.gossipsub.PeerInfoR\x05peers\x12\x18\n" +
	"\abackoff\x18\x03 \x01(\x04R\abackoff\"Q\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12,\n" +
	"\x12signed_peer_record\x18\x02 \x01(\fR\x10signedPeerRecord\"\x80\x01\n" +
	"\x0fTopicDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x04auth\x18\x02 \x01(\v2\x19.dep2p.gossipsub.AuthOptsR\x04auth\x12*\n" +
	"\x03enc\x18\x03 \x01(\v2\x18.dep2p.gossipsub.EncOptsR\x03enc\"M\n" +
	"\bAuthOpts\x12-\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x19.dep2p.gossipsub.AuthModeR\x04mode\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"V\n" +
	"\aEncOpts\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.dep2p.gossipsub.EncModeR\x04mode\x12\x1d\n" +
	"\n" +
	"key_hashes\x18\x02 \x03(\fR\tkeyHashes*D\n" +
	"\bAuthMode\x12\x12\n" +
	"\x0eAUTH_MODE_NONE\x10\x00\x12\x11\n" +
	"\rAUTH_MODE_KEY\x10\x01\x12\x11\n" +
	"\rAUTH_MODE_WOT\x10\x02*G\n" +
	"\aEncMode\x12\x11\n" +
	"\rENC_MODE_NONE\x10\x00\x12\x17\n" +
	"\x13ENC_MODE_SHARED_KEY\x10\x01\x12\x10\n" +
	"\fENC_MODE_WOT\x10\x02B/Z-github.com/dep2p/go-dep2p/pkg/proto/gossipsubb\x06proto3"

var (
	file_pkg_proto_gossipsub_gossipsub_proto_rawDescOnce sync.Once
	file_pkg_proto_gossipsub_gossipsub_proto_rawDescData []byte
)

func file_pkg_proto_gossipsub_gossipsub_proto_rawDescGZIP() []byte {
	file_pkg_proto_gossipsub_gossipsub_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gossipsub_gossipsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gossipsub_gossipsub_proto_rawDesc), len(file_pkg_proto_gossipsub_gossipsub_proto_rawDesc)))
	})
	return file_pkg_proto_gossipsub_gossipsub_proto_rawDescData
}

var file_pkg_proto_gossipsub_gossipsub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_gossipsub_gossipsub_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_gossipsub_gossipsub_proto_goTypes = []any{
	(AuthMode)(0),           // 0: dep2p.gossipsub.AuthMode
	(EncMode)(0),            // 1: dep2p.gossipsub.EncMode
	(*RPC)(nil),             // 2: dep2p.gossipsub.RPC
	(*SubOpts)(nil),         // 3: dep2p.gossipsub.SubOpts
	(*Message)(nil),         // 4: dep2p.gossipsub.Message
	(*ControlMessage)(nil),  // 5: dep2p.gossipsub.ControlMessage
	(*ControlIHave)(nil),    // 6: dep2p.gossipsub.ControlIHave
	(*ControlIWant)(nil),    // 7: dep2p.gossipsub.ControlIWant
	(*ControlGraft)(nil),    // 8: dep2p.gossipsub.ControlGraft
	(*ControlPrune)(nil),    // 9: dep2p.gossipsub.ControlPrune
	(*PeerInfo)(nil),        // 10: dep2p.gossipsub.PeerInfo
	(*TopicDescriptor)(nil), // 11: dep2p.gossipsub.TopicDescriptor
	(*AuthOpts)(nil),        // 12: dep2p.gossipsub.AuthOpts
	(*EncOpts)(nil),         // 13: dep2p.gossipsub.EncOpts
}
var file_pkg_proto_gossipsub_gossipsub_proto_depIdxs = []int32{
	3,  // 0: dep2p.gossipsub.RPC.subscriptions:type_name -> dep2p.gossipsub.SubOpts
	4,  // 1: dep2p.gossipsub.RPC.publish:type_name -> dep2p.gossipsub.Message
	5,  // 2: dep2p.gossipsub.RPC.control:type_name -> dep2p.gossipsub.ControlMessage
	6,  // 3: dep2p.gossipsub.ControlMessage.ihave:type_name -> dep2p.gossipsub.ControlIHave
	7,  // 4: dep2p.gossipsub.ControlMessage.iwant:type_name -> dep2p.gossipsub.ControlIWant
	8,  // 5: dep2p.gossipsub.ControlMessage.graft:type_name -> dep2p.gossipsub.ControlGraft
	9,  // 6: dep2p.gossipsub.ControlMessage.prune:type_name -> dep2p.gossipsub.ControlPrune
	10, // 7: dep2p.gossipsub.ControlPrune.peers:type_name -> dep2p.gossipsub.PeerInfo
	12, // 8: dep2p.gossipsub.TopicDescriptor.auth:type_name -> dep2p.gossipsub.AuthOpts
	13, // 9: dep2p.gossipsub.TopicDescriptor.enc:type_name -> dep2p.gossipsub.EncOpts
	0,  // 10: dep2p.gossipsub.AuthOpts.mode:type_name -> dep2p.gossipsub.AuthMode
	1,  // 11: dep2p.gossipsub.EncOpts.mode:type_name -> dep2p.gossipsub.EncMode
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_gossipsub_gossipsub_proto_init() }
func file_pkg_proto_gossipsub_gossipsub_proto_init() {
	if File_pkg_proto_gossipsub_gossipsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gossipsub_gossipsub_proto_rawDesc), len(file_pkg_proto_gossipsub_gossipsub_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_gossipsub_gossipsub_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gossipsub_gossipsub_proto_depIdxs,
		EnumInfos:         file_pkg_proto_gossipsub_gossipsub_proto_enumTypes,
		MessageInfos:      file_pkg_proto_gossipsub_gossipsub_proto_msgTypes,
	}.Build()
	File_pkg_proto_gossipsub_gossipsub_proto = out.File
	file_pkg_proto_gossipsub_gossipsub_proto_goTypes = nil
	file_pkg_proto_gossipsub_gossipsub_proto_depIdxs = nil
}
